### ISSUE TITLE
Annot-SV 2.3.2 crashes in the running exomiser step

### ISSUE THREAD

**Issue by archanaraja** [lgmgeo/AnnotSV#10]
Hi , Im trying to run the latest annot-sv with HPO terms and it crashes as it can't find json package. Would be great if you can help.  I've pasted the error below.
..running Exomiser
can't find package json 1.3.3
  while executing
"package require json 1.3.3"
  (procedure "runExomiser" line 9)
  invoked from within
"runExomiser "$L_allGenesOverlapped" "$g_AnnotSV(hpo)""
  (procedure "refGeneAnnotation" line 262)
  invoked from within
"refGeneAnnotation"

Thanks,
Archana

**Comment by lgmgeo** [comment]
Hi Archana,

AnnotSV requires the latest release of the Tcl distribution starting with version 8.5 as well as the following 4 packages “http”, “json”, "tar" and "csv".
The “http” and the “json” packages are used for the phenotype-driven analysis.
The "tar" and "csv" packages are used only when data sources are updated.
(please look at the "2. INSTALLATION/REQUIREMENTS" section in the README)

**How to install the Tcl package json?**
1. Download tcllib: https://core.tcl-lang.org/tcllib/wiki?name=Downloads
2. Install: https://wiki.tcl-lang.org/page/Tcllib+Installation
Or local install: http://eggwiki.org/Local_Tcl
3. Set TCLLIBPATH to tcllib installation directory.

Concerning these 4 Tcl packages needed, I will try for the next major release to integrate them in the AnnotSV distribution and so remove them from the requirements.

Best,

Véronique

**Comment by archanaraja** [comment]
Thank you so much for the solution . I’m able to run the latest annot sv except for phenotype driven analysis . Can you point me to the exact http and Json packages that I should download for the phenotypic analysis ? That’s my only bottleneck now ?

Thanks a lot .

Archana

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lgmgeo** [comment]
Ok, I'm integrating the different packages in AnnotSV.
Can you contact me directly by email? (so I could send you a patch)
veronique.geoffroy@inserm.fr

**Comment by archanaraja** [comment]
Thank you . I just sent  you an email.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lgmgeo** [comment]
The Tcl packages needed are now integrated in AnnotSV.
