### ISSUE TITLE
truncated gzip input

### ISSUE THREAD

**Issue by ThuongHa** [lgmgeo/AnnotSV#11]
Hello,

I'm trying to install AnnotSV 2.3 but had problems with the installation of human annotation:

tar -xf Annotations_Human_2.3.2.tar.gz -C /usr/local/usr/local/share/AnnotSV/
Annotations_Human/BreakpointsAnnotations/GCcontent/GRCh38/GRCh38_chromFa.fasta: truncated gzip input
tar: Error exit delayed from previous errors.
make: *** [install-human-annotation] Error 1 

Can you please advise on how to resolve this error.

**Comment by lgmgeo** [comment]
Hi Thuong, 

It sounds like the "Annotations_Human_2.3.2.tar.gz" file might be corrupted. 
Can you try getting it manually from the original source again:
cd $ANNOTSV
curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_2.3.2.tar.gz

Then you can finish the installation:
make PREFIX=. install-human-annotation

Let me know if it works,

Véronique
