### ISSUE TITLE
SV type of version 3.1.1 

### ISSUE THREAD

**Issue by charliechen912ilovbash** [lgmgeo/AnnotSV#116]
I am not sure if this is an issue. Previously I was using version 3.0.9, the output SV type include BND, DEL,DUP and INV. But recently I tried with version 3.1.1, only DEL,DUP and INV are included, the BND disappeared. Is there any changes about sv type between these two version?

**Comment by lgmgeo** [comment]
Hi,
Could you give me an example of an input line (extracted from your VCF input file), which was `BND` annotated in 3.0.9 and not in 3.1.1?
Best,
Véronique

**Comment by lgmgeo** [comment]
Any news?
