### ISSUE TITLE
-reciprocal

### ISSUE THREAD

**Issue by Qijie0615** [lgmgeo/AnnotSV#119]
Use of a reciprocal overlap between SV and user features (only for annotations with features overlapping the SV); Values: 0 (default) or 1
I don't quite understand this sentence, can you explain in detail；
If I choose -reciprocal 1, it will only annotate SVs that have overlap with the database?  even 1bp or depend on the value of reciprocal overlap.

**Comment by lgmgeo** [comment]
Hi @Qijie0615,

It is to notice that the `-reciprocal` option can only be used with custom annotations.

Users need to place the BED file in the “SVincludedInFt” directory. By default, only the features overlapping 100% of the SV will be reported. But a reciprocal overlap can also be used (to modify the default behaviour of the overlap by using a different percentage)

`-reciprocal`: Use of a reciprocal overlap between SV and user features (only for annotations with features overlapping the SV)
Values: 0 (default) or 1

`-overlap`: Minimum overlap (%) between user features (User BED) and the annotated SV to be reported
Range values: [0;100], default = 100

Best regards,
Véronique

**Comment by Jixin-Cao** [comment]
So, what will happen if I put my annotation file in 'AnyOverlap', and set the -reciprocal 1 and -overlap 100 ? I see the default value of -overlap is 100. Does it change the basic function of 'AnyOverlap'(overlap even 1 bp)?

**Comment by lgmgeo** [comment]
if you put your annotation file in 'AnyOverlap'... all overlaps will be reported (regardless of the -reciprocal and -overlap options)
