### ISSUE TITLE
Issue about hg38

### ISSUE THREAD

**Issue by renzilin** [lgmgeo/AnnotSV#12]
Hi,
I'm trying to use your software. But I found that the database was downloading while I was installing the software. However, I want to handle some SVs in hg38. The database downloaded by your software is like hg19.
There are only hg19 in the pic. So is the hg38 annotations here? Or which parameter should I set to have a hg38 annotation?
![image](https://user-images.githubusercontent.com/17135904/81627335-f36ef200-93cb-11ea-8a9e-204bb33ea301.png)

Thanks for your help!

**Comment by lgmgeo** [comment]
Hi,
Don't worry, your installation is correct for hg38.
You just need to use the following option : -genomeBuild GRCh38 
Regarding the Exomiser analyses, it's independent of the genome build. The Exomiser module only uses the name of the genes (and not the position of the genes).

Have great analyses with AnnotSV,
Best regards,
Véronique

**Comment by renzilin** [comment]
> Hi,
> Don't worry, your installation is correct for hg38.
> You just need to use the following option : -genomeBuild GRCh38
> Regarding the Exomiser analyses, it's independent of the genome build. The Exomiser module only uses the name of the genes (and not the position of the genes).
> 
> Have great analyses with AnnotSV,
> Best regards,
> Véronique

Thank you for your quick reply. I'll try it.
