### ISSUE TITLE
allele specific annotation?

### ISSUE THREAD

**Issue by charliechen912ilovbash** [lgmgeo/AnnotSV#120]
Hi,
In the future, is it possible to use AnnotSV to annotate SV in allele 1 and allele 2 separately?
For an example, one deletion happened homozygously -> both allele 1 and allele2; one inversion happened heterozygously -> only allele 1 or allele2.
Maybe use BAM as input.
Since if only one allele is deleted, the gene in this region may still be able to express normally, the deletion may not  seriously affect the gene function. 

I would appreciate if you have any suggestion about annotating SV separately on each allele for human genome.

Thank you very much.

**Comment by lgmgeo** [comment]
Hi @charliechen912ilovbash,

You're rigth, the genotype (heterozygous or homozygous status) is essential in determining whether the gene function is affected or not.
Currently, the genotype (GT in VCF) is determined from BAM by some SV callers or by specific tools (Nebula...).
But it should be noted that AnnotSV is not dedicated to parsing BAM files (like SV callers). AnnotSV is dedicated to annotation. It is good to know that by default, AnnotSV extracts the additional SV input fields and insert the data in the output file (-SVinputInfo 1). The GT is so reported in the output.

If your SV callers are not reporting GT in the output, then my advice is to use a specific tool like [Nebula](https://academic.oup.com/nar/article/49/8/e47/6121467). 

Hope this can help,
Best,
Véronique
