### ISSUE TITLE
Gene annotations

### ISSUE THREAD

**Issue by Madelinehazel** [lgmgeo/AnnotSV#121]
Hello, 

Is there any kind of padding taken into account when SVs are annotated against genes/transcripts? E.g. if an SV breakpoint falls 2000 bp upstream of a transcription start site, will it be annotated against that transcript?

Thanks,
Madeline

**Comment by lgmgeo** [comment]
Hi Madeline,

Currently, the only paddings considered are the `CIPOS` and `CIEND` features of the VCF input file:
```
-includeCI: To expand the "start" and "end" SV positions with the VCF confidence intervals (CIPOS, CIEND) around the breakpoints
            Values: yes (default) or no
```
In the futur (not near), I plan to add new annotations in AnnotSV: the closest genes upstream and downstream of the SV to annotate. 

Best regards,
Véronique

**Comment by Madelinehazel** [comment]
OK, thank you Véronique!
