### ISSUE TITLE
Possible AF_max bug

### ISSUE THREAD

**Issue by gevro** [lgmgeo/AnnotSV#122]
Hi, There are a small number of AF_max values > 1.0.

**Comment by lgmgeo** [comment]
Hi, Can you give some SV coordinates (chrom strat end) and type (del dup...) with such AF_max values > 1.0 ?

**Comment by gevro** [comment]
Attached
[AF 1.3 example.xlsx](https://github.com/lgmgeo/AnnotSV/files/8632529/AF.1.3.example.xlsx)

**Comment by lgmgeo** [comment]
Hi @gevro,

Here is your example:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/VERONI~1.GEO/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/VERONI~1.GEO/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



AnnotSV_ID | B_loss_source | B_loss_AFmax
-- | -- | --
X_55675946_55683373_DEL_1 | CMRI:4_pbsv.DEL.785_duplicate9;DDD:57613;IMH;esv2658420;gnomAD-SV_v2.1_DEL_X_186407 | 1,3044



</body>
</html>


You have a deletion (X:55675946-55683373) with indeed AF_max value > 1.0 

You can get back this value from your AnnotSV install (`$ANNOTSV/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh37/benign_Loss_SV_GRCh37.sorted.bed`):
X      55702378        55709806        gnomAD-SV_v2.1_DEL_X_186407     X:55702378-55709806     1.3044

And so you can determine that this frequency (1.3044) comes from gnomAD SVs v2.1.

OK, let's have a look at the `DEL_X_186407` ID in the gnomAD SVs v2.1 database:
https://gnomad.broadinstitute.org/variant/DEL_X_186407?dataset=gnomad_sv_r2_1
![image](https://user-images.githubusercontent.com/49909073/167081588-046e81cd-112d-44fa-9def-281df27998f0.png)

Indeed, you recover the origin of this strange frequency > 1.

Finally, no bug in AnnotSV.

Hope this is clearer,
Best,
Véronique
