### ISSUE TITLE
WARNING: No GeneHancer annotations available

### ISSUE THREAD

**Issue by wx904** [lgmgeo/AnnotSV#124]
Hi,

As suggested, I put the five unzipped Genehancer files in the following directory: $ANNOTSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements. 
![image](https://user-images.githubusercontent.com/53553660/167750590-1ff42495-5262-4c7a-b687-560361c9a7c4.png)

However, when running AnnotSV on the test.bed file, I got this WARNING message:
WARNING: No GeneHancer annotations available.
(Please, see in the README file how to add these annotations. Users need to contact the GeneCards team.)

I've no idea what is going wrong.

Best,
Xiao

**Comment by lgmgeo** [comment]
Hi Xiao,

Can you tell me which “GeneHancer_**version**_for_annotsv.zip” file you used?
The latest available is `GeneHancer-v5.9-for-AnnotSV.zip`.

From what I can see, there is a typo in the file `GeneHancer_gene_associations_scores.txt` (the "s" is missing at the end of `association`). Can you run:
```
mv GeneHancer_gene_association_scores.txt GeneHancer_gene_associations_scores.txt
```
Best,
Véronique

**Comment by wx904** [comment]
Hi Véronique,

Yes, you are quite right. I'm using v5.9 data. Thank you sooo much for pointing this typo for me. The warning message didn't show up any more and everything seems going well.

BTW, can I ask another question? Since I'm quite unexperienced, I've no idea how to make the input BED file with SV types.  Do you have any suggestion on which software can do this?


Thanks,
Xiao

**Comment by lgmgeo** [comment]
> I've no idea how to make the input BED file with SV types. 

With AnnotSV, you can use either BED or VCF input file.

> Do you have any suggestion on which software can do this?

You mean, which SV callers to use?

It depends on your sequencing data (WES, WGS, RNAseq, CGHarray...). Best is to use several SV callers. 
For example, with WGS data, among others:
- CNVpytor, Delly_SV, Dysgu, Manta, smoove for DEL, DUP, INS, INV, TRA, BND
- ExpansionHunter for repetitions of short unit sequence
- Melt for MEI (Mobile Element Insertion)

Perhaps just begin with one and then use AnnotSV to annotate the VCF output files.

**Comment by wx904** [comment]
Hi Véronique,

I truly appreciate your timely help and suggestion, which means a lot to me. Thank you.

Sincerely,
Xiao
