### ISSUE TITLE
Output file is .tmp.tsv file and .unannotated.tsv file

### ISSUE THREAD

**Issue by minn333** [lgmgeo/AnnotSV#125]
Dear @lgmgeo
Thanks for your kindly reply. I had met another problem while running smaller VCF files. The log file as below:
the problem is that
it produced two files, 
1. $SampleID.tsv.tmp   <<< this temporary file!!
2. $SampleID.unannotated.tsv

Thanks..

----------------------------------------------------------------

...checking the annotation data sources

WARNING: No GeneHancer annotations available.
(Please, see in the README file how to add these annotations. Users need to contact the GeneCards team.)

...listing arguments
******************************************
AnnotSV has been run with these arguments:
******************************************
-REreport no
-SVinputFile /$path/Delly_smallfiles/$sampleID_delly_sv.vcf
-SVinputInfo 1
-SVminSize 50
-annotationMode both
-annotationsDir /$path/AnnotSV/AnnotSV_v3.0.9/share/AnnotSV
-bcftools bcftools
-bedtools bedtools
-candidateGenesFiltering no
-genomeBuild GRCh37
-includeCI no
-metrics us
-minTotalNumber 500
-organism Human
-outputDir /path/Delly_smallfiles
-outputFile $sampleID_delly_sv_output_t3.tsv
-overlap 100
-overwrite yes
-promoterSize 500
-rankFiltering 1 2 3 4 5 NA
-reciprocal no
-samplesidBEDcol -1
-snvIndelPASS 0
-svtBEDcol 4
-tx RefSeq
******************************************

...searching for SV overlaps with a gene or a regulatory elements
...28035 genes overlapped with an SV

**Comment by lgmgeo** [comment]
I'm quite surprised by your log file...
Anything else after "...28035 genes overlapped with an SV"?
Does the tool stop rigth after writing this ? No error message?

In so, can you send me:
- your VCF input file zipped to veronique.geoffroy@inserm.fr
- your command line
- the version of AnnotSV you used
so that I can reproduce the bug.
