### ISSUE TITLE
Transcript version

### ISSUE THREAD

**Issue by Akazhiel** [lgmgeo/AnnotSV#126]
Hello,

I'm trying to generate HVGSg notation from some structural variants and translating them into HGVSc but for this I need the transcripts with the corresponding version, meaning the number after the dot, like so `ENST00000463781.8`. Is there perhaps an option I can enable for this or it has to be implemented?

Best regards,

Jonatan

**Comment by lgmgeo** [comment]
Hi Jonathan,

Actually, as described in the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf),  the data source from ENSEMBL comes from:
- GRCH37: http://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz
- GRCh38: http://ftp.ensembl.org/pub/current_gtf/homo_sapiens/Homo_sapiens.GRCh38.104.chr.gtf.gz
- 
And if you look at these files:
![image](https://user-images.githubusercontent.com/49909073/168291238-e8781851-df77-4cb3-bcc9-6fb93626173f.png)
you see that the transcripts version is not reported... 
So currently, no way for AnnotSV to enable this.

Do you have any other ENSEMBL data sources to propose (with transcript versions)?

Best,
Véronique

**Comment by Akazhiel** [comment]
Hello, 

I did download the most recent GTF and there is indeed a field where the `transcript_version` is included. Perhaps in the image snippet that's attached it doesn't show up because they are exon records. And there is an option to include the transcript version if available in the gtftoGenePred software. Probably this would just be a matter on adding that option for ENSEMBL, while for RefSeq as far as I know there are no reference files that include this transcript version, I'll look more into the matter and get back to you since the tool I use for generating these HGVS only works with RefSeq.

Best regards,

Jonatan

**Comment by lgmgeo** [comment]
> I did download the most recent GTF and there is indeed a field where the transcript_version is included.
Can you give me the http address of this file?

**Comment by Akazhiel** [comment]
Hello,

This is the one I downloaded http://ftp.ensembl.org/pub/release-106/gtf/homo_sapiens/Homo_sapiens.GRCh38.106.gtf.gz

As you can see the transcript version is included in the file, it may be the case that some don't actually have a transcript version, but for the most part there seems to be one.

```
3       ensembl_havana  gene    195746765       195811973       .       -       .       gene_id "ENSG00000145113"; gene_version "22"; gene_name "MUC4"; gene_source "ensembl_havana"; gene_biotype "protein_coding";
3       havana  transcript      195746765       195778810       .       -       .       gene_id "ENSG00000145113"; gene_version "22"; transcript_id "ENST00000308466"; transcript_version "12"; gene_name "MUC4"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "MUC4-201"; transcript_source "havana"; transcript_biotype "nonsense_mediated_decay"; tag "cds_start_NF"; tag "mRNA_start_NF"; transcript_support_level "1";
3       havana  exon    195778790       195778810       .       -       .       gene_id "ENSG00000145113"; gene_version "22"; transcript_id "ENST00000308466"; transcript_version "12"; exon_number "1"; gene_name "MUC4"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "MUC4-201"; transcript_source "havana"; transcript_biotype "nonsense_mediated_decay"; exon_id "ENSE00001648952"; exon_version "1"; tag "cds_start_NF"; tag "mRNA_start_NF"; transcript_support_level "1";
3       havana  CDS     195778790       195778810       .       -       2       gene_id "ENSG00000145113"; gene_version "22"; transcript_id "ENST00000308466"; transcript_version "12"; exon_number "1"; gene_name "MUC4"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "MUC4-201"; transcript_source "havana"; transcript_biotype "nonsense_mediated_decay"; protein_id "ENSP00000310528"; protein_version "8"; tag "cds_start_NF"; tag "mRNA_start_NF"; transcript_support_level "1";
3       havana  exon    195778289       195778455       .       -       .       gene_id "ENSG00000145113"; gene_version "22"; transcript_id "ENST00000308466"; transcript_version "12"; exon_number "2"; gene_name "MUC4"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "MUC4-201"; transcript_source "havana"; transcript_biotype "nonsense_mediated_decay"; exon_id "ENSE00001790212"; exon_version "1"; tag "cds_start_NF"; tag "mRNA_start_NF"; transcript_support_level "1";
3       havana  CDS     195778289       195778455       .       -       2       gene_id "ENSG00000145113"; gene_version "22"; transcript_id "ENST00000308466"; transcript_version "12"; exon_number "2"; gene_name "MUC4"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "MUC4-201"; transcript_source "havana"; transcript_biotype "nonsense_mediated_decay"; protein_id "ENSP00000310528"; protein_version "8"; tag "cds_start_NF"; tag "mRNA_start_NF"; transcript_support_level "1";
3       havana  exon    195774172       195774305       .       -       .       gene_id "ENSG00000145113"; gene_version "22"; transcript_id "ENST00000308466"; transcript_version "12"; exon_number "3"; gene_name "MUC4"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "MUC4-201"; transcript_source "havana"; transcript_biotype "nonsense_mediated_decay"; exon_id "ENSE00003469066"; exon_version "1"; tag "cds_start_NF"; tag "mRNA_start_NF"; transcript_support_level "1";
3       havana  CDS     195774172       195774305       .       -       0       gene_id "ENSG00000145113"; gene_version "22"; transcript_id "ENST00000308466"; transcript_version "12"; exon_number "3"; gene_name "MUC4"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "MUC4-201"; transcript_source "havana"; transcript_biotype "nonsense_mediated_decay"; protein_id "ENSP00000310528"; protein_version "8"; tag "cds_start_NF"; tag "mRNA_start_NF"; transcript_support_level "1";
3       havana  exon    195771652       195771816       .       -       .       gene_id "ENSG00000145113"; gene_version "22"; transcript_id "ENST00000308466"; transcript_version "12"; exon_number "4"; gene_name "MUC4"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "MUC4-201"; transcript_source "havana"; transcript_biotype "nonsense_mediated_decay"; exon_id "ENSE00003651795"; exon_version "1"; tag "cds_start_NF"; tag "mRNA_start_NF"; transcript_support_level "1";
3       havana  CDS     195771652       195771816       .       -       1       gene_id "ENSG00000145113"; gene_version "22"; transcript_id "ENST00000308466"; transcript_version "12"; exon_number "4"; gene_name "MUC4"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "MUC4-201"; transcript_source "havana"; transcript_biotype "nonsense_mediated_decay"; protein_id "ENSP00000310528"; protein_version "8"; tag "cds_start_NF"; tag "mRNA_start_NF"; transcript_support_level "1";
```

As for the processing with the gtfToGenePred this option should be included `-includeVersion - it gene_version and/or transcript_version attributes exist, include the version in the corresponding identifiers.`

For RefSeq I'm not sure if there is any solution. I did want to ask if there is any reason as to why the RefSeq and ENSEMBL processing is done from different sources before including it in AnnotSV?

Best regards,
Jonatan

**Comment by Akazhiel** [comment]
For RefSeq I've found this file http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz would need to cut out the first column but aside from that seems like the `BED` file that is in the annotation directory of AnnotSV.

**Comment by lgmgeo** [comment]
Ok
- With ENSEMBL data, the `transcript_version` feature is only available for GRCh38 (not for GRCh37).
GRCH37: http://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz
GRCh38: http://ftp.ensembl.org/pub/current_gtf/homo_sapiens/Homo_sapiens.GRCh38.106.chr.gtf.gz
- With RefSeq data, the `transcript_version` feature is available for both GRCh37 and GRCh38
GRCh37: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ncbiRefSeq.txt.gz
GRCH38: http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz

NOTE: Some transcripts don't have a transcript version.

Thanks for pointing this out. I will add a `transcript_id` output annotation column in a future release.
This feature will be filled only when available, otherwise it will be empty.

**Comment by lgmgeo** [comment]
My apologies, I realize that this issue has completely been overlooked...
I will add the `transcript_version` feature for the next release.

**Comment by lgmgeo** [comment]
AnnotSV 3.4 is posted. The `Tx_version` feature was added.
Let me know if everything works well on your side.
