### ISSUE TITLE
can not install human annotation 

### ISSUE THREAD

**Issue by gaom001** [lgmgeo/AnnotSV#129]
Hi, do you know why I can not downlad human annotation now?   Please advise it!   Thank you!  

`$ make PREFIX=… install-human-annotation 

Download AnnotSV supporting data files:

curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'www.lbgi.fr'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
make: *** [Makefile:176: Annotations_Human_3.1.1.tar.gz] Error 60`

**Comment by xiucz** [comment]
Hi, @gaom001 
 
Not an author but I will try to help you ! You can download the database manually,

```
wget -c https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.1.tar.gz --no-check-certificate
```
and then,
tar -xf Annotations_Human_$(VERSION).tar.gz -C $(DESTDIR)$(SHAREDIR)/$(ANNOTSV)/
```
from the source file:

https://github.com/lgmgeo/AnnotSV/blob/7973cc4725f548cac3f9cd2dc843ed47c5b3f1e0/Makefile#L139-L140

**Comment by oguzhankalyon** [comment]
Hi, @xiucz, @gaom001 and @KevinMer 

I have been trying to download the database as well but had the same issue and I think so it is due to a database connection issue.

Would be appreciated any given solution!

Oguzhan

**Comment by gaom001** [comment]
I also tried, yes, the downloaded database was not able to unzip. It is not a gzip fomat file. Looking for any possible soultions. Thanks in advance. 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by nehasanghi** [comment]
> I also tried, yes, the downloaded database was not able to unzip. It is not a gzip fomat file. Looking for any possible soultions. Thanks in advance.

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

I am also facing the same issue. Any help would be of great help!!
Thanks

**Comment by lgmgeo** [comment]
Hi everyone,

Sorry for the delay of my answer, I was out of my lab the last week.
Currently, I can't reproduce this problem. Can you confirm that you are still facing this issue?

Véronique

**Comment by KevinMer** [comment]
Hi Véronique,

I am not facing this issue anymore. Seems like it was a temporary bug.

Thanks for your reply.

Kevin
