### ISSUE TITLE
Issue with mouse-annotation

### ISSUE THREAD

**Issue by azzatha** [lgmgeo/AnnotSV#13]
Hello,

I got an issue with (`make PREFIX=. install-mouse-annotation`) it seems that the file `Annotations Mouse 2.3.2.tar.gz` does not exist.

`make PREFIX=. install-mouse-annotation`

> Installation of mouse annotation:
> 
> install -d ./share/AnnotSV/
> tar -xf Annotations_Mouse_2.3.2.tar.gz -C ./share/AnnotSV/
> tar: This does not look like a tar archive
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> Makefile:164: recipe for target 'install-mouse-annotation' failed
> make: *** [install-mouse-annotation] Error 2

Thanks,

**Comment by lgmgeo** [comment]
Sorry, it should work now.
