### ISSUE TITLE
How about to get more annotations?

### ISSUE THREAD

**Issue by xiucz** [lgmgeo/AnnotSV#130]
Hi,
For `omim database`, is it possible to get the `Omim Genes Symbol` column,  `OMIM_ID /OMIM_phenotype / OMIM_inheritance /       OMIM_morbid  /   OMIM_morbid_candidate`  are already in the headers.

For `ClinGene data`, also is it possible to get the `ClinGene  Genes Symbol`  column?

For `Cosmic data`,  also is it possible to get the `Cosmic  Genes Symbol`  column?

Best,
xiucz

**Comment by lgmgeo** [comment]
Hi Xiucz,

The "split lines" are based on each gene overlapped with the SV. 
And in each split line, you can retrieve the Gene symbol in the `Gene_name` output column.

Best,
Véronique

**Comment by xiucz** [comment]
Yes, the `Gene_name` column contains all the genes, but is it possible to categorize them into `cosmic gene`, `omim gene` ?

Best,
xiucz

**Comment by lgmgeo** [comment]
Not sure to well understand.

In a full line, the `Gene_name` column contains all the gene names overlapped with the SV. 
But in a split line, the `Gene_name` column contains only 1 gene name, the one that is specifically described with OMIM annotation, Cosmic annotation, and so on.

**Comment by xiucz** [comment]
@lgmgeo 
Thank you,  these are precisely what I want, but which columns are often used to refer to this information?

Best, 
xiucz

**Comment by lgmgeo** [comment]
All the columns are described in the "Annotation columns available in the output file" section from the [README ](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf)file.
