### ISSUE TITLE
Error: 20220701-145510_sort.tmp.bash: No such file or directory

### ISSUE THREAD

**Issue by v-lakhujani** [lgmgeo/AnnotSV#131]
I am executing AnnotSV 3.0.5 and encountering this error frequently

![image](https://user-images.githubusercontent.com/84500633/176870274-9f120cdb-5ed6-4c19-8cbd-5e7eaa733891.png)

If I re run the same command, it gets executed without any issue. Any ideas ?

**Comment by lgmgeo** [comment]
Hi Vijay,
Sorry, I've never encountered this problem. And it seems hard to replicate...
Is it completely random?
Can you have a network access problem on your server?
Best,
Véronique

**Comment by lgmgeo** [comment]
Hi Vijay,
Any news about this problem?
