### ISSUE TITLE
Pathogenic SV source coordinates on Hg19 reference.

### ISSUE THREAD

**Issue by Mkddb** [lgmgeo/AnnotSV#132]
Hello Veronique,

Hope you are doing great. 

In annotations, I have noted that certain P_loss_coordinates are coming from Hg19 reference coordinates, despite I have provided the Hg38 mode in the annotation.
For example, I annotated this deletion on chr11_63361790_63445978, DEL in Hg38 mode (Job ID: AnnotSV_z2NapwjvZt in hg38). In the "pathogenic_SV" column, P_loss_source is morbid ATL3 and the coordinates are 11:63391558-63439446 (which are on Hg19 reference). 
Although, the Hg38 coordinates for ATL3 gene are chr11:63,624,087-63,671,974. Which appears to be outside the coordinates of my deletion and might not be having this gene as P_loss_source. 

Can you please check this and help me out for its better understanding. 

Thanks in advance,
Mkd

**Comment by Mkddb** [comment]
Hello Veronique,

This would be really helpful to have a fix with the new version at the earliest possible. Meanwhile, can you suggest an alternative way to check such wrong entries for Pathogenic SVs, since I have 100s of variants to screen through for now? or do I have to manually check for each entry?

Looking forward to the fix. 

Thanks again,
Mkd

**Comment by lgmgeo** [comment]
Hi Mkb,
I couldn't leave such a bug, just added a fix.
You need to update AnnotSV to v3.1.2.
I'm really sorry for the inconvenience.
Let me know if everything is working now (should be)
Best,
Véronique

**Comment by Mkddb** [comment]
Hello Veronique,

Thanks for the fix and update. Everything else looks fine now, except for one discrepancy.

Sorry to disturb you again. There's a discrepancy for one variant: chr19:39727656-39735580, Deletion on Hg38 coordinates. (Job ID: AnnotSV_AQMOqJLGYB in hg38). There's no overlapped P_loss_source for it, and the gene Gene affected is CLC (CHARCOT-LEYDEN CRYSTAL PROTEIN).
but the OMIM annotation in AnnotSV appeared as Cold-induced sweating syndrome 2, 610313 (3) AR, which is linked with a different gene CLCF1 (CARDIOTROPHIN-LIKE CYTOKINE FACTOR 1). 

Can you please check for the same and find a fix for it ?

With kind regards,
Mkd

**Comment by lgmgeo** [comment]
Hi Mkd,

Great if the fix works! Thanks for the feedback.
Regarding your discrepancy, I don't think it's a bug.
If you look at the OMIM ID [607672](https://www.omim.org/entry/607672), CLC and CLCF1 are alternative gene symbols.
So everything seems fine to me.

Best,
Véronique

**Comment by lgmgeo** [comment]
cf https://github.com/lgmgeo/AnnotSV/issues/156

**Comment by lgmgeo** [comment]
Hi Tejas,

Thanks for reporting with this specific “ASPA” example.
New annotations are expected to be released in January. I keep this bug in mind to check the new update.

Sorry for the delay, I'm chasing time...

Best,
Véronique

**Comment by lgmgeo** [comment]
I have added a fix for misleading OMIM annotation in the dev branch.
This will be distributed soon with the next annotation release.

@Mkddb 
`chr19:39727656-39735580`
=> Ok, no more bad OMIM_ID annotation (607672 no longer reported)

@tejas-j 
Still in process (not a misleading OMIM )

**Comment by Mkddb** [comment]
Hi Véronique,

That sounds great.
Thanks for the fix for the misleading OMIM annotation.
Looking forward for the next annotation release.

Best regards,
MKd

**Comment by lgmgeo** [comment]
**@tejas-j**
> **Variant on hg38 annotated with OMIM information from hg19:**
grep -i canavan Annotations_Human/FtIncludedInSV/PathogenicSV/GRCh38/pathogenic_Loss_SV_GRCh38.sorted.bed
grep -i canavan Annotations_Human/FtIncludedInSV/PathogenicSV/GRCh37/pathogenic_Loss_SV_GRCh37.sorted.bed
Both return the same coordinates:
17	3379290	3406699	Canavan disease, 271900 (3) AR		morbid:ASPA	17:3379290-3406699

I have added a fix for this bug in the dev branch.
This will be distributed soon with the next annotation release.
Thank you very much for the report and sorry for the long delay.
