### ISSUE TITLE
AnnotSV changed the start position in VCF?

### ISSUE THREAD

**Issue by xiucz** [lgmgeo/AnnotSV#135]
Hi, 

When I use AnnotSV to annotate my SV file from Lumpy, I find the start positions were changed in the AnnotSV result.
For example, `chr7:73743401-116381161` is the vcf file, however, the output is changed to `chr7:73743177-116381348`

Can you please check this and help me out？
Thank you.

My command here,
```
export ANNOTSV=~AnnotSV/AnnotSV-3.1/AnnotSV
~/AnnotSV/bin/AnnotSV \
-bedtools ~/bedtools/bedtools-2.30.0/bin/bedtools \
-bcftools ~/bcftools-1.12/bin/bcftools -annotationMode both -overlap 100 -benignAF 0.001 -overwrite 1 -genomeBuild GRCh37 \
-SVinputFile lumpy.gt.vcf -outputFile lumpy -outputDir .
```

I attach my vcf.txt file here.

![image](https://user-images.githubusercontent.com/12706146/183028540-ae01653d-7116-4e65-be76-bced72e6f731.png)
![image](https://user-images.githubusercontent.com/12706146/183029305-662b97b9-035b-4c0a-a8fb-66afd6aaa453.png)
[test.vcf.txt](https://github.com/lgmgeo/AnnotSV/files/9266616/test.vcf.txt)

xiucz

**Comment by xiucz** [comment]
SV type BND has the same start and end position,  however, the <DUP> type is not.

**Comment by lgmgeo** [comment]
Hi Xiucz,

To keep the same start and end positions in the AnnotSV results, please set the `includeCI` option to "no":
```
-includeCI: To expand the "start" and "end" SV positions with the VCF confidence intervals (CIPOS, CIEND) around the breakpoints
            Values: yes (default) or no
```

You can be interested in https://github.com/lgmgeo/AnnotSV/issues/37, https://github.com/lgmgeo/AnnotSV/issues/63, https://github.com/lgmgeo/AnnotSV/issues/73

Best regards,
Véronique

**Comment by xiucz** [comment]
@lgmgeo 

 Thank you very much. And in version 3.1, the option should be `-includeCI 0`, if set to `-includeCI no` or `-includeCI=no`, it will report an error.

And I will close this issue.

Best,
xiucz

**Comment by lgmgeo** [comment]
Hi Xiucz,

I can't reproduce your example bug. On my side, the `-includeCI 0` option works fine.
Can you please run your example on the [web server](https://lbgi.fr/AnnotSV/runjob) and send me the job ID ?

Best,
Véronique
