### ISSUE TITLE
make: *** [install-human-annotation] Error 2

### ISSUE THREAD

**Issue by CLAIRE-cuhk** [lgmgeo/AnnotSV#136]
Hi,

I am trying to install AnnotSV. The make PREFIX=. install-mouse-annotation worked fine, but then I got a gzip error with make PREFIX=. install-human-annotation.

$make PREFIX=. install-human-annotation

Download Exomiser supporting data files:

curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/2109_hg19.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  111M  100  111M    0     0  3408k      0  0:00:33  0:00:33 --:--:-- 7292k
curl -C - -LO https://data.monarchinitiative.org/exomiser/data/2109_phenotype.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2674M  100 2674M    0     0   139M      0  0:00:19  0:00:19 --:--:--  150M

Installation of Exomiser data:

install -d -p ./share/AnnotSV/Annotations_Exomiser/2109
tar -xf 2109_hg19.tar.gz -C ./share/AnnotSV/Annotations_Exomiser/2109/
unzip 2109_phenotype.zip -d ./share/AnnotSV/Annotations_Exomiser/2109/
Archive:  2109_phenotype.zip
   creating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/2109_phenotype.h2.db  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/hp.obo  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/rw_string_10.mv  
   creating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/
   creating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/4.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/10.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/20.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/17_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/3_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/15.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/11.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/4_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/16.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/5_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/12.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/12_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/17.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/13.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/11_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/15_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/14_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/16_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/18.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/7_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/14.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/10_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/3.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/19.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/18_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/2.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/9_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/9.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/1.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/20_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/8.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/7.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/2_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/6_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/13_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/6.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/8_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/1_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/19_symmetric.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/out/5.out  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/hp.obo  
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype/phenix/ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt 
  inflating: ./share/AnnotSV/Annotations_Exomiser/2109/2109_phenotype.sha256  
/bin/rm -rf 2109_phenotype.zip
/bin/rm -rf 2109_hg19.tar.gz

--> Exomiser data installed

Installation of human annotation:

tar -xf Annotations_Human_3.1.2.tar.gz -C ./share/AnnotSV/

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
make: *** [install-human-annotation] Error 2

Can you please check this and help me out？

Thanks in advance.

**Comment by lgmgeo** [comment]
Hi Claire,

I just tried a new install on my server, everything seems OK on my side:
![image](https://user-images.githubusercontent.com/49909073/184700691-ec1b5224-0190-4fc3-a6d4-0ed7752e9378.png)
...
![image](https://user-images.githubusercontent.com/49909073/184700773-485dc5b6-fe32-484f-84b4-b8b2c50a4be8.png)

Can you show me the result of the following commands:
```
ls -l Annotations_Human_3.1.2.tar.gz
ls -l ./share/AnnotSV/
```
Next, can you show me the result of the following command:
```
curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.2.tar.gz
```
Best,
Véronique

**Comment by CLAIRE-cuhk** [comment]
Hi Véronique,

Thank you so much for your reply. Here are the results:

[image: image.png]

[image: image.png]

Many thanks.
Claire

Geoffroy Véronique ***@***.***> 于2022年8月16日周二 03:14写道：

**Comment by lgmgeo** [comment]
Hi Claire,

The size of your file `Annotations_Human_3.1.2.tar.gz` is correct (2173675441).
So I'm quite surprised by your error message ("gzip: stdin: unexpected end of file").
Can you run the following command:
```
tar -xf Annotations_Human_3.1.2.tar.gz -C ./share/AnnotSV/
```
Do you still have the same message?
If yes, can you redo the following steps:
```
rm Annotations_Human_3.1.2.tar.gz
curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.2.tar.gz
tar -xf Annotations_Human_3.1.2.tar.gz -C ./share/AnnotSV/
```
In my opinion, the bug is in curl. But I don't really understand...
On my side, I use an old curl version: 
![image](https://user-images.githubusercontent.com/49909073/184881134-646d373e-6b44-4a53-9ec2-755e99379145.png)


Véronique

**Comment by lgmgeo** [comment]
cf ["Curl : (33) HTTP server doesn't seem to support byte ranges. Cannot resume."](https://stackoverflow.com/questions/23586214/curl-33-http-server-doesnt-seem-to-support-byte-ranges-cannot-resume)

"Existing file will not tell you if complete or incomplete, which is the cause of the bug. "
"It's not the bug explanation but a quick workaround to solve the problem and continue"

**Comment by CLAIRE-cuhk** [comment]
Hi Véronique,

I just repeated this command make PREFIX=. install-human-annotation, and the package was installed successfully. Thank you so much.

Installation of human annotation:

tar -xf Annotations_Human_3.1.2.tar.gz -C ./share/AnnotSV/
/bin/rm -rf Annotations_Human_3.1.2.tar.gz

--> Human annotation installed

Great thanks.

**Comment by lgmgeo** [comment]
Great!
Have fun with AnnotSV ;o)
