### ISSUE TITLE
make: *** [install-human-annotation] Error 1

### ISSUE THREAD

**Issue by mvergara89** [lgmgeo/AnnotSV#137]
Hi!!
I'm having trouble installing the human annotation:

![Screen Shot 2022-09-09 at 2 21 08 PM](https://user-images.githubusercontent.com/21294033/189418303-cb726dc7-ce75-4159-b6d2-bc7b4671d495.png)

Any ideas of what is happening?

Thank you so much!
Matías

**Comment by lgmgeo** [comment]
Hi Matias,
It looks like another errors occured before ("previous error").
Can you copy/paste all the output here?
Best,
Véronique

**Comment by mvergara89** [comment]
Hi Veronique,

I'm attaching the screenshots


![Screen Shot 2022-09-13 at 6 02 54 PM](https://user-images.githubusercontent.com/21294033/190017351-4ec89918-e7d9-4c44-b903-e579c530a3f2.png)

![Screen Shot 2022-09-13 at 6 03 38 PM](https://user-images.githubusercontent.com/21294033/190017440-81307cf9-8ae4-4d07-b6b2-f0f127cef4bc.png)


Thanks for your help!
Matías

**Comment by lgmgeo** [comment]
```
curl: (56) LibreSSL SSL_read: error:02FFF036:system library:func(4095):Connection reset by peer
```
This looks like an issue downloading via curl, and not an AnnotSV issue.
I really don't know what should be the reason for this problem...

Please, If you solve this problem, give the explanation here.

**Comment by lgmgeo** [comment]
Does the download work if you run the following command line directly?
```
curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.3.tar.gz
```
Else, can you try:
```
wget  https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.3.tar.gz
```

**Comment by gavinmonahan** [comment]
I'm having the same issue when running `make PREFIX=. install-human-annotation`:
```curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'www.lbgi.fr'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

I added the `-k` flag to the `curl` call to allow unsecure connections and it's downlaoding now. What are the steps after that?

**Comment by lgmgeo** [comment]
Can you just re-run `make PREFIX=. install-human-annotation` ?

**Comment by gavinmonahan** [comment]
That worked, thank you @lgmgeo. I only had the curl SSL issue with the first file, all others worked fine.

**Comment by lgmgeo** [comment]
Great!

Anyway, thank you for the report. I contacted the host administrator and he fixed the "www.lbgi.fr" certificate (it was a certificate renewal bug). 
Currently, the `curl: (60) SSL: no alternative certificate subject name matches target host name 'www.lbgi.fr'`bug should no longer occur.

Have fun with AnnotSV!

**Comment by oquenez** [comment]
Hi,

it seems the problem is still there when I try to install AnnotSV 3.1.3 human-annotation today (`make PREFIX=. install-human-annotation`) but with a small difference:
message is now certificate has expired (see below)

Best,
Olivier

```
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle" of Certificate Authority (CA) public keys (CA certs). If the default bundle file isn't adequate, you can specify an alternate file using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in the bundle, the certificate verification probably failed due to a problem with the certificate (it might be expired, or the name might\n not match the domain name in the URL)
```

**Comment by lgmgeo** [comment]
Hi Olivier, 
Thanks for the report!
I contacted the host administrator, I come back to you asap.
Véronique

**Comment by lgmgeo** [comment]
Olivier, can you please check again and tell me if it works ?

**Comment by oquenez** [comment]
I  just check and it seems that there is a ssl cache or a similar problem : when I try earlier to download Annotations_Human_3.1.3.tar.gz with my firefox browser, I got the certificate error, and it has now disappears and the download starts.

I check and the result is different depending on the server I tried. 

 i will work on the problem on our side but it seems OK from yours.
 Thanks a lot !

**Comment by lgmgeo** [comment]
Thank you for this detailed answer. 
If you have any tips for other users, feel free to add a new comment.

Have a nice day!

**Comment by oquenez** [comment]
One way to correct the problem of ssl cache is to use the update certificate method

`sudo update-ca-certificates --fresh ` (for ubuntu)

Best,
Olivier

**Comment by lgmgeo** [comment]
Thanks

**Comment by pblaney** [comment]
Hello Véronique,

I recently tried to pull down the annotation files and received a similar certificate issue using both ```curl``` and ```wget```.

```
curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.3.tar.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

curl: (51) SSL: certificate subject name (lbgi.fr) does not match target host name 'www.lbgi.fr'
```

```
wget https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.1.tar.gz

--2022-11-02 16:47:51--  https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.1.tar.gz
Resolving www.lbgi.fr (www.lbgi.fr)... 185.155.94.20
Connecting to www.lbgi.fr (www.lbgi.fr)|185.155.94.20|:443... connected.
ERROR: cannot verify www.lbgi.fr's certificate, issued by 'CN=R3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.
ERROR: no certificate subject alternative name matches
	requested host name 'www.lbgi.fr'.
To connect to www.lbgi.fr insecurely, use `--no-check-certificate'.
```

I also encountered the certificate issue when I first traveled to the ```https://www.lbgi.fr/~geoffroy/Annotations/``` site but after accepting to continue to the site, I can download the files without issue.


**UPDATE**: The issue was resolved after modifying the target name to ```https://lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.1.tar.gz```

**Comment by lgmgeo** [comment]
According to @oquenez:
> it seems that there is a ssl cache or a similar problem
> I check and the result is different depending on the server I tried.

> One way to correct the problem of ssl cache is to use the update certificate method
> 
> `sudo update-ca-certificates --fresh ` (for ubuntu)

@pblaney , can you try to update your certificate method?

**Comment by pblaney** [comment]
@lgmgeo I did try running this code snippet before 
```curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.1.3.tar.gz```
However, this did not resolve the issue.

I was able to fix the problem by removing the ```www.``` from the target path.

**Comment by lgmgeo** [comment]
Interesting, thanks for the feedback!

**Comment by lgmgeo** [comment]
The following files are now distributed with AnnotSV:
$ANNOTSV/bin/INSTALL_code.sh
$ANNOTSV/bin/INSTALL_annotations.sh
