### ISSUE TITLE
VCF annotation using web-interface and assembly build used for annotation

### ISSUE THREAD

**Issue by priyambial123** [lgmgeo/AnnotSV#142]
Hello

I have annotated the files by running Annot SV analysis in the command line. Are the VCFs annotated using GRCh38 or GRCh37 assembly build here? 

Thanks

**Comment by lgmgeo** [comment]
Hi @priyambial123,

By default, AnnotSV is running with the genome build GRCh38:
![image](https://user-images.githubusercontent.com/49909073/196716486-e1985c65-28bc-4eb2-b262-6d1ba213dbed.png)

FYI, like AnnotSV, knotAnnotSV can be run locally.

Best,
Véronique
