### ISSUE TITLE
Reference source used for annotation

### ISSUE THREAD

**Issue by priyambial123** [lgmgeo/AnnotSV#143]
Hello

I have annotated the files using ANNOTSV which has been generated as a tsv file. Using BCF tools, I want to sort the columns and rows to plot and visualise. To use it in BCFtools, I have to convert the tsv to vcf.gz file. I need fasta.reference file to do this conversion.  Can you provide the source or link from where the GRCh38 reference fasta file was used for annotation.

`bcftools convert -f 23andme-ref.fa --tsv2vcf 23andme.txt -Oz -o out.vcf.gz`

Thanks

Priya

**Comment by lgmgeo** [comment]
Hi @priyambial123,

The GRCh38 reference fasta file is only used in AnnotSV for the GC content annotations. The [README ](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf)file indicates the sources:
![image](https://user-images.githubusercontent.com/49909073/196917998-faa4c383-8f1a-4bf9-ae90-7023c4d5923a.png)

Else, each annotation comes from different sources.
For example, for the ClinVar benign SV annotations:
![image](https://user-images.githubusercontent.com/49909073/196918590-8a2e97ea-6274-4b87-8224-4de82ef44bdc.png)

Best,
Véronique

FYI: a VCF output format will be added in AnnotSV in a few months.

**Comment by priyambial123** [comment]
I could get the o/p in vcf.gz format. I tried it. Thanks for the links as well

` "/AnnotSV/bin/AnnotSV" -SVinputFile "/AnnotSV/share/doc/AnnotSV/Example/test.bed" -outputFile ./test.annotated.vcf.gz -svtBEDcol 4
`

**Comment by lgmgeo** [comment]
Mmm... currently, AnnotSV doesn't provide a VCF output format (only a tsv output format).
This command `-outputFile ./test.annotated.vcf.gz` can't work.

**Comment by priyambial123** [comment]
Yes you are right. The command ran but the file was saved as tsv.

**Comment by lgmgeo** [comment]
Hi @priyambial123,

A new VCF output format is now available in AnnotSV 3.2.1 (only when using a VCF input file).
To convert the output format from tsv to VCF, AnnotSV relies on the variantconvert tool. A minimal Python 3.8 installation is required, as well as the natsort, panda and pyfaidx Python modules.

Best regards,

Véronique
