### ISSUE TITLE
What does it mean to be simultaneously located at a intron(Location) and a CDS(Location2)?

### ISSUE THREAD

**Issue by hd00ljy** [lgmgeo/AnnotSV#144]
I observed so many annotations that are annotated as both CDS and intron, especially contained within a single intron

I was expecting that variants annotated as CDS were disrupting CDS but it seems not to be the case for AnnotSV output.

![image](https://user-images.githubusercontent.com/13775022/202324037-c73a89d3-8aba-4724-906e-7ed59da4ec4a.png)

Could you help me understand the output?

**Comment by lgmgeo** [comment]
Hi @hd00ljy,

In your example lines, all SV are annotated: `Overlapped_CDS_length = 0`
Which means that your SV do not overlap CDS. Indeed, the `location`is in intron10.

Concerning, `Location2 = CDS`, please look at the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf) file. Here are the corresponding feature definitions:
```
Location2 = SV location in the gene’s coding regions
Values: UTR (no CDS in the gene)
5’UTR (before the CDS start),
3’UTR (after the CDS end)
CDS (between the CDS start and the CDS end, can be in an exon or an intron).
```

FYI, `Frameshift` indicates if the `Overlapped_CDS_length` is not divisible by three (yes or no).

Best regards,
Véronique

**Comment by hd00ljy** [comment]
Thank you @lgmgeo,

I thought that meant the position on the transcript.

It make sense if that is based on the genomic coordinate.

Thank you for tje clarification!
