### ISSUE TITLE
Input bed file format

### ISSUE THREAD

**Issue by amy-houseman** [lgmgeo/AnnotSV#146]
Hello!

I just had a query about the input format, I have my list of CNVs from ClinCNV which also has a copy number change column, showing how many copy numbers were duplicated or deleted. I was wondering if that was required for input into AnnotSV or whether it is simply stating deletion or duplication?

Thanks!!
Amy

**Comment by lgmgeo** [comment]
Hi Amy,

Can you please show an extract of your list of CNVs from ClinCNV?
It would be easier to answer.

Best,
Véronique

**Comment by amy-houseman** [comment]
Hi Véronique, 

No problem!

So for example: 

#chr | start | end | CN_change | loglikelihood | no_of_regions | length_KB | potential_AF | qvalue
-- | -- | -- | -- | -- | -- | -- | -- | --
chr16 | 11761 | 13339 | 0 | 38 | 2 | 1.578 | 0.242 | 0.0008
chr1 | 13163 | 13658 | 0 | 23 | 1 | 0.495 | 0.303 | 0.00206
chr1 | 13331 | 786538 | 3 | 21 | 5 | 773.207 | 0.146 | 0.06736
chr16 | 14379 | 15633 | 1 | 28 | 3 | 1.254 | 0.238 | 0.00002

With CN_change being 0 = both copies deleted, 3 = one extra copy, 1 = one copy delete. 
These numbers vary more than this for example I have some duplications that are 4, 8 etc or 2 on the X chromosome for males. 

Hope this makes sense!
Amy :)

**Comment by lgmgeo** [comment]
The CN_change is not a usable format with VCF or AnnotSV.
But you can easily put it in VCF format:
CN_change = 1   <=> <CN1>
CN_change = 0   <=> <CN0>
CN_change = 3   <=> <CN3>
etc

You can then use your modified ClinCN (tab separated values) output as the AnnotSV input (with the option: `-svtBEDcol 4`)
I hope that it's clearer.

Best

**Comment by amy-houseman** [comment]
Hi Véronique,

Very clear, thank you! I'll have a go!

BW,
Amy

**Comment by lgmgeo** [comment]
Great, have fun with AnnotSV :o)

PS : AnnotSV can't deal with 2 on the X chromosome for males (as gender is not given)
