### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by lmanchon** [lgmgeo/AnnotSV#147]
Hi,

installation failed with:
make PREFIX=. install

Installation of AnnotSV-3.2:
----------------------------
DESTDIR=
PREFIX=.
TCLVERSION=tcl8.6

/bin/mv  ./share/doc/AnnotSV
/bin/mv: opérande de fichier cible manquant après './share/doc/AnnotSV'
Saisissez « /bin/mv --help » pour plus d'informations.
make: *** [Makefile:75 : install-documentationlight] Erreur 1

**Comment by lgmgeo** [comment]
Hi @lmanchon ,

Is it your first installation of AnnotSV on your machine?
Or have you already successfully installed AnnotSV with an older version?

Here is (I think) the buggy Makefile command:
```
	$(MV) $^ $(DESTDIR)$(DOCDIR)/$(ANNOTSV)
```
Can you please give me the result of the following commands:
```
ls -l $ANNOTSV
ls -l $ANNOTSV/share/doc
```
Best,
Véronique

**Comment by lmanchon** [comment]
hello,

i have changed $(MV) $^ $(DESTDIR)$(DOCDIR)/$(ANNOTSV)
to $(MV) $^ $(DESTDIR)$(DOCDIR)/$(ANNOTSV) .
in a Makefile and it works now.

(cos' the mv command need a target) 

ls -l $ANNOTSV
total 60
drwxrwxr-x 4 laurent laurent  4096 déc.  20 09:58 AnnotSV
drwxrwxr-x 2 laurent laurent  4096 déc.  20 09:57 bin
drwxrwxr-x 3 laurent laurent  4096 déc.  20 09:57 etc
-rw-rw-r-- 1 laurent laurent  8983 déc.  20 10:12 Makefile
-rw-rw-r-- 1 laurent laurent  1266 déc.  20 09:57 README.md
-rwxrwxr-x 1 laurent laurent 25183 déc.  20 09:57 Scoring_Criteria_AnnotSV_v3.2.xlsx
drwxrwxr-x 7 laurent laurent  4096 déc.  20 10:12 share

ls -l share/doc
total 0

**Comment by lgmgeo** [comment]
Sorry, I'm not sure I understand your edit... I can't see any difference.
Can you check what is written in your previous message?

Something went wrong with your installation. After the git clone, you should have the following files (License.txt, changeLog.txt, commandLineOptions.txt, README.AnnotSV_*.pdf) in the $ANNOTSV directory.
And after the `make PREFIX=. install` command, these files should be in the $ANNOTSV/share/doc/AnnotSV/ directory.

**Comment by lgmgeo** [comment]
In the following Makefile command:
```$(MV) $^ $(DESTDIR)$(DOCDIR)/$(ANNOTSV)```
`$^` refers to the License.txt, changeLog.txt, commandLineOptions.txt and README.AnnotSV_3.2.pdf files

**Comment by lmanchon** [comment]
I don't know what happened during my first installation, problem is over now,
I've just re-downloaded the git repository and re-install it.
ticket can be closed
thx

**Comment by lgmgeo** [comment]
Great!
