### ISSUE TITLE
not a known SV format

### ISSUE THREAD

**Issue by genegogo2019** [lgmgeo/AnnotSV#149]
format is wrong!

**Comment by genegogo2019** [comment]
I had check my input VCF format (edited and integrated), it is the same with the original VCFs. However, i still met the problem.

log file:
############################################################################
No SV to annotate in the SVinputFile - Exit without error.
############################################################################

unannotated tsv file:
1_ 1598573___1: not a known SV format
1_ 1599072__ALU_1: not a known SV format
1_ 7078188___1: not a known SV format
1_ 7078188_7078204_INS:ME:ALU_1: not a known SV format
1_ 8277046__ALU_1: not a known SV format
1_ 8277051___1: not a known SV format
1_ 8446627___1: not a known SV format
1_ 8446627_8446635_INS:ME:ALU_1: not a known SV format
1_ 8446628___1: not a known SV format
1_ 8446635__ALU_1: not a known SV format
1_ 12737561_12737575_INS:ME:ALU_1: not a known SV format

**Comment by genegogo2019** [comment]
Dear author:

This time, the log file wrote No SV to annotate, and the unannotated tsv wasn't written.

Could you tell me which part I have to check?

Thanks


---------------------------------------
log file
---------------------------------------
AnnotSV 3.0.9

Copyright (C) 2017-2021 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.5

Application name used (defined with the "ANNOTSV" environment variable):
/opt/ohpc/Taiwania3/pkg/biology/AnnotSV/AnnotSV_v3.0.9


...downloading the configuration data (January 01 2023 - 23:58)
        ...configuration data by default
        ...configuration data from /opt/ohpc/Taiwania3/pkg/biology/AnnotSV/AnnotSV_v3.0.9/etc/AnnotSV/configfile
        ...configuration data given in arguments
        ...checking all these configuration data

############################################################################
No SV to annotate in the SVinputFile - Exit without error.
############################################################################


－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
Below is my VCF input files
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

##INFO=<ID=RD_CLUSTER,Number=1,Type=String,Description="Right discordant formed cluster in consensus">
##INFO=<ID=NINDEL,Number=1,Type=Integer,Description="Number of large indel (or with several mismatches) reads">
##INFO=<ID=CLIP_LEN,Number=1,Type=String,Description="Clip reads length">
##INFO=<ID=INS_INV,Number=1,Type=String,Description="5 prime inversion">
##INFO=<ID=REF_REP,Number=1,Type=String,Description="Fall in reference repeat copy or not">
##INFO=<ID=GENE_INFO,Number=1,Type=String,Description="Fall in gene region">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  TAAD0007-LCL6989_combined
chr1     1598573         INS:ME  C       <INS:ME:ALU>    60.636791229248         PASS    MEINFO=chr1:1598573_ALU_Plus,1598573,1598574,+;caller=scramble  .       .
chr1     1599072         .       g       <INS:ME:ALU>    .       ac0     TSD=null;ASSESS=1;INTERNAL=NM_001110781,INTRONIC;SVTYPE=ALU;SVLEN=278;MEINFO=AluY,2,280,+;DIFF=0:g9a,c10t,t17a,c48t,g58a,g65a;LP=2;RP=4;RA=-1;PRIOR=false;SR=0;caller=melt      GT:GL:DP:AD     0/0:-0,-12.04,-233.9:20:0
chr1     7078188         INS:ME  T       <INS:ME:ALU>    105.503662109375        PASS    MEINFO=chr1:7078188_ALU_Minus,7078188,7078189,-;caller=scramble         .       .
chr1     7078188         .       a       <INS:ME:ALU>    .       PASS    SVTYPE=INS:ME:ALU;SVLEN=84;END=7078204;TSD=+aatGCCAGGGCTTTTT;TSDLEN=16;SUBTYPE=one_half_side_tprt_both;TD_SRC=not_transduction;STRAND=-;AF=0.4482758620689655;LCLIP=11;RCLIP=3;LDISC=7;RDISC=1;LPOLYA=0;RPOLYA=3;LRAWCLIP=13;RRAWCLIP=5;AF_CLIP=13;AF_FMAP=16;AF_DISC=27;AF_CONCORDNT=54;LDRC=0;LDNRC=7;RDRC=0;RDNRC=1;LCOV=40.065;RCOV=40.46;LD_AKR_RC=0;LD_AKR_NRC=7;RD_AKR_RC=1;RD_AKR_NRC=0;LC_CLUSTER=169:190;RC_CLUSTER=251:253;LD_CLUSTER=130.0:252.0;RD_CLUSTER=-1:-1;NINDEL=0;CLIP_LEN=32:49:46:49:8:35:35:35:4:53:49:49:49;INS_INV=Not-5prime-inversion;REF_REP=not_in_Alu_copy;GENE_INFO=intron:ENSG00000171735.19_4:CAMTA1;caller=xtea      GT      0/1
chr1     8277046         .       C       <INS:ME:ALU>    .       lc      TSD=null;ASSESS=3;INTERNAL=null,null;SVTYPE=ALU;SVLEN=259;MEINFO=AluJo,21,280,+;DIFF=0.21:g204a,t213a,c215g,c220t,t231c,a232g,g270a;LP=5;RP=8;RA=-0.678;PRIOR=false;SR=2;caller=melt    GT:GL:DP:AD     0/1:-54,-8.43,-105.6:14:5
chr1     8277051         .       .       <INS:ME:ALU>    .       PASS    IMPRECISE;SAMPS=TAAD0007-LCL6989_combined:6;CIPOS=8277045,8277055;SUP=4,2,0,0;POLYA=0;TSD=unknown;CLLEN=267,210;ORIGIN=0,6,0;CLIPPED=-1,-1,-1,-1,-1.00,-1.00;caller=mobster     .       .
chr1     8446627         INS:ME  A       <INS:ME:ALU>    163.561294555664        PASS    MEINFO=chr1:8446627_ALU_Minus,8446627,8446628,-;caller=scramble         .       .

**Comment by lgmgeo** [comment]
Hi @genegogo2019,

My first thought is that your VCF is from Scramble, right?
Unfortunately, this tool does not output GT in the format column and the authors have so far not answered the following request: https://github.com/GeneDx/scramble/issues/20

For each SV of an input VCF file, without GT, AnnotSV considers this SV absent from the sample.

So, to annotate your VCF with AnnotSV, you either need to reformat that VCF and add the GT information, or need to create a bed file (without the GT feature).

Best,
Véronique

**Comment by genegogo2019** [comment]
Véronique
            However, I succeeded to annotate VCF output files from scramble alone.

With best wishes,
段德敏(Demin-Duan)


 Windows 的]件<https://go.microsoft.com/fwlink/?LinkId=550986>魉



寄件者: Geoffroy ***@***.***>
魉rg: 2023年1月2日 下午 10:12
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [lgmgeo/AnnotSV] not a known SV format (Issue #149)


Hi @genegogo2019<https://github.com/genegogo2019>,

My first thought is that your VCF is from Scramble, right?
Unfortunately, this tool does not output GT in the format column and the authors have so far not answered the following request: GeneDx/scramble#20<https://github.com/GeneDx/scramble/issues/20>

For each SV of an input VCF file, without GT, AnnotSV considers this SV absent from the sample.

So, to annotate your VCF with AnnotSV, you either need to reformat that VCF and add the GT information, or need to create a bed file (without the GT feature).

Best,
Véronique

―

**Comment by genegogo2019** [comment]
Dear author:
          I succeeded annotation on Scramble alone, but failed while I merge with other MEI callers output file. The attached file is annotated file for scramble output.


With best wishes,
段德敏


 Windows 的]件<https://go.microsoft.com/fwlink/?LinkId=550986>魉



寄件者: Geoffroy ***@***.***>
魉rg: 2023年1月2日 下午 10:18
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [lgmgeo/AnnotSV] not a known SV format (Issue #149)


Closed #149<https://github.com/lgmgeo/AnnotSV/issues/149> as completed.

―

**Comment by lgmgeo** [comment]
Not sure to understand your need.
AnnotSV is not a tool dedicated to merge VCF.

**Comment by genegogo2019** [comment]
Okay,
       I am not merging the VCF files with AnnotSV.
I merged the VCFs from different callers and filtered and then threw into the AnnotSV. May be I will find a solution. Thanks for your kindly reply.

With best wishes,
段德敏


 Windows 的]件<https://go.microsoft.com/fwlink/?LinkId=550986>魉



寄件者: Geoffroy ***@***.***>
魉rg: 2023年1月3日 上午 12:26
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [lgmgeo/AnnotSV] not a known SV format (Issue #149)


Not sure to understand your need.
AnnotSV is not a tool dedicated to merge VCF.

―

**Comment by lgmgeo** [comment]
To merge SV VCF, I can advise you [truvari ](https://github.com/ACEnglish/truvari) or [jasmine ](https://github.com/mkirsche/Jasmine).

**Comment by genegogo2019** [comment]
Dear author:
        I solved the problem. It was my fault that extra space before the fields. I could annotate successfully. Thanks.
