### ISSUE TITLE
VCF conversion config is not available in the release

### ISSUE THREAD

**Issue by gungorbudak** [lgmgeo/AnnotSV#150]
Hi,

Using the 3.2.1 version, I installed python3.8 and variantconvert requirements but below error occurred because there is [a configs folder in variantconvert repository](https://github.com/SamuelNicaise/variantconvert/tree/master/configs) which is missing in the AnnotSV release.

It works when I put [the JSON](https://github.com/SamuelNicaise/variantconvert/blob/master/configs/config_annotsv3.json) there.

However, because I'm using GRCh38, I needed to change the "GENOME" in the JSON with the GRCh38 since it was hg19 (contigs start with "chr" and contig lengths are different).

I'm guessing there should be two config JSONs one for GRCh37 and one for GHRCh38 because contig lengths are different. AnnotSV can switch between them [in the writing code](https://github.com/lgmgeo/AnnotSV/blob/fd34df9b5b45838e5d2c0ee6e15d4bcc0abd5e3e/share/tcl/AnnotSV/AnnotSV-write.tcl#L1439).

```
...creation of the VCF output file: ./test.vcf
   AnnotSV relies on the variantconvert tool (https://github.com/SamuelNicaise/variantconvert).
   A minimal Python 3.8 installation is required, as well as the natsort, panda and pyfaidx Python modules.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/AnnotSV-3.2.1/share/python3/variantconvert/variantconvert/__main__.py", line 190, in <module>
    main()
  File "/opt/AnnotSV-3.2.1/share/python3/variantconvert/variantconvert/__main__.py", line 186, in main
    main_convert(args)
  File "/opt/AnnotSV-3.2.1/share/python3/variantconvert/variantconvert/__main__.py", line 63, in main_convert
    converter = factory.get_converter(
  File "/opt/AnnotSV-3.2.1/share/python3/variantconvert/variantconvert/converter_factory.py", line 34, in get_converter
    return converter(config)
  File "/opt/AnnotSV-3.2.1/share/python3/variantconvert/variantconvert/converters/abstract_converter.py", line 14, in __init__
    with open(config_filepath, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/AnnotSV-3.2.1/share/python3/variantconvert/configs/config_annotsv3.json'
```

**Comment by lgmgeo** [comment]
Hi @gungorbudak,

Thank you for the report. Indeed, the config directory was not pushed into Github, strange... Really sorry for that.
Moreover, you're right, the code should be optimized for genome build. 
I will make a new version asap.

Best,
Véronique

**Comment by lgmgeo** [comment]
OK, understood.
VariantConvert contains a `.gitignore` file:
![image](https://user-images.githubusercontent.com/49909073/210798433-0067dc57-c4a6-4c83-8163-5c64400fcf5c.png)
which ignore the config/* files:
![image](https://user-images.githubusercontent.com/49909073/210799072-2c753c60-f46d-4955-906b-03251b919c47.png)

**Comment by lgmgeo** [comment]
I just pushed a new version, v3.2.2.
Everything should be OK now. Can you confirm ?

Thank you for your help.

**Comment by gungorbudak** [comment]
Thanks so much @lgmgeo works perfect now. I see that in the JSONs mode says "full&split", I'm guessing it means it can support all three modes (both, full, split) as I didn't get any error with these options used. Have you checked if these options have any impact on VCF conversion?

**Comment by lgmgeo** [comment]
Great, thank you for the feedback!

Indeed, [variantconvert ](https://github.com/SamuelNicaise/variantconvert) is dedicated to work with all the three modes (both, full, split). But I haven't had a full check on it (only a quick test with an exemple).
I invite you [to post your question](https://github.com/SamuelNicaise/variantconvert/issues) directly to the variantconvert developers (they are great and responsive)

Best

**Comment by gungorbudak** [comment]
Thanks much @lgmgeo
