### ISSUE TITLE
two CNV positions in my VCF break AnnotSV

### ISSUE THREAD

**Issue by lindenb** [lgmgeo/AnnotSV#151]
Hi, thank you for AnnotSV.

I want to report that two positions in my VCF seem to break AnnotSV (Web version).
All the other ~800 positions are OK.

It fails even if I just enter the **coordinates** instead of the VCF.

It only fails on hg19 but it works well on hg38.

I cannot report those two positions here for confidentiality reasons but I will be happy to share them by email. 

Best Regards,

PL

**Comment by lgmgeo** [comment]
Bonjour Pierre,

Oui, bien sûr, tu peux me les envoyer par email.
Merci (il y a qq bug qui ressortent avec la dernière version)
veronique.geoffroy@inserm.fr

Best,
Véronique

**Comment by lgmgeo** [comment]
Nouvelle version 3.2.2  postée

**Comment by lgmgeo** [comment]
bug fix validated

**Comment by lindenb** [comment]
> Nouvelle version 3.2.2 postée. Il ne devrait plus y avoir de bug.

merci !
