### ISSUE TITLE
AnnotSV .tsv output SV_chrom values differ from input using GRCh38

### ISSUE THREAD

**Issue by dennishendriksen** [lgmgeo/AnnotSV#152]
First of all thank you creating and maintaining this great tool!

I'm running into the following issue when running AnnotSV on GRCh38 data:

input VCF record:
```
chr9    11566435        .       TTTTTCTATTATACTATTAATATAATAGTTATTAATATAATAACAATATAG     T       13.24   PASS    F       GT:GQ:DP:AF     0/1:13:2:0.5
```

output AnnotSV record in .tsv:
```
AnnotSV_ID      SV_chrom        SV_start        SV_end ...
9_11566435_11566485_DEL_1       9       11566435        11566485 ...
```
`-genomeBuild GRCh38` was used a command-line argument with AnnotSV 3.2.2 (same issue occurs in 3.0.9)

The mismatch in chromosome identifier (input:`chr9`, output:`9`) prevents us annotating the result 'back' on the input in an automated fashion. Since we are annotating individual VEP consequences per VCF record using a plugin using the new -vcf option probably doesn't resolve the issue.

**Comment by lgmgeo** [comment]
Hi,
if I well understood, you would like to keep "chr" in the `SV_chrom` output column, right?
Véronique

**Comment by dennishendriksen** [comment]
I would prefer to use the GRCh38 chromosome identifiers in the output when running with `-genomeBuild GRCh38`. For most chromosomes this implies adding a `chr` prefix. I don't know if this is valid for all chromosome identifiers, for example the mitochondrial chromosome identifier in most GRCh37 references is called `MT` compared to `chrM` (without the T) in GRCh38.

**Comment by lgmgeo** [comment]
OK, here's a simple (and immediate) way to get back to GRCh38 chromosome identifiers in the output:
```
cat test.annotated.tsv | awk '{$1=gensub("^[1-9XYM][0-9]?_","chr&",1,$1); $2=gensub("^[1-9XYM][0-9]?","chr&",1,$2); $0=gensub("[1-9XYM][0-9]?:[0-9]+-[0-9]+","chr&","g",$0); print $0}' > test.annotated.GRCh38.tsv
```
Can you confirm that this command is what you need?

I keep the idea of adding an AnnotSV option to integrate this need directly into the code, but it's not for the near future.

Best,
Véronique

**Comment by dennishendriksen** [comment]
Thank you for your quick reply and the suggested workaround.

I've already added a workaround that I think is similar to yours:
```
mv "!{vcf}.tsv" "!{vcf}.tsv.tmp"
awk -v FS='\t' -v OFS='\t' 'NR>1 {$2 = "chr"$2; print} 1' "!{vcf}.tsv.tmp" > "!{vcf}.tsv"
```

**Comment by lgmgeo** [comment]
Yes, similar for a TSV AnnotSV output. 
Be carefull on the following points:
- You only change the "SV_chrom" column, not the coordinates given in the other ones (e.g. P_loss_coord, P_gain_coord...) 
- You add "chr" for all contigs: for exemple, also for `HLA-A*01:01:01:01` (GRCh38's contig).
