### ISSUE TITLE
Error when using mm10 in AnnotSV v3.2.2 

### ISSUE THREAD

**Issue by toshi0813** [lgmgeo/AnnotSV#153]
I'd like to annotate the SV of the mouse.
It does not work.

Here are the installation commands and the commands I have run.

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
git clone https://github.com/lgmgeo/AnnotSV.git

cd /install_path/AnnotSV
make PREFIX=. install
make PREFIX=. install-mouse-annotation

export ANNOTSV=/path_of_AnnotSV_installation/

$ANNOTSV/bin/AnnotSV \
-SVinputFile //test.vcf \
-annotationsDir /install_path/AnnotSV/share/AnnotSV \
-annotationMode full \
-genomeBuild mm10 \
-includeCI 1 \
-overwrite 1 \
-outputFile ./sample_AnnotSV.tsv

I got the following error message.
I need help.

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
...downloading the configuration data (January 25 2023 - 15:10)
        ...configuration data by default
        ...configuration data from /install_path/AnnotSV/etc/AnnotSV/configfile
        ...configuration data given in arguments
        ...checking all these configuration data

...checking the annotation data sources
           >>> creation of /install_path/AnnotSV/share/AnnotSV/Annotations_Mouse/SVincludedInFt/BenignSV/GRCh37/overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tsv] (January 25 2023 - 15:11)
-- checkOverlappedGenesBenignFiles, GRCh37, RefSeq, Loss --
bedtools intersect -sorted -a  -b  -wa -wb > ./1674627060_overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tmp.bed
Error: Unable to open file . Exiting.
Exit with error
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

Please allow me to add the results of my trial and error.

The same results were obtained with ver 3.2, so I tried ver 3.1, and the above error did not occur anymore. However, a new problem occurred. There is a Gene annotations column in the results, but "Tx", "Tx_start", "Tx_end", "Overlapped_tx_length", "Overlapped_CDS_length", "Overlapped_CDS_percent ", "Frameshift", "Exon_count", "Location", "Location2", "Dist_nearest_SS", "Nearest_SS_type", "Intersect_start" and "Intersect_end" are empty.

Do I need to do anything described in README.AnnotSV_3.1_Mouse.pdf?
The command I ran is as follows.

$ANNOTSV/bin/AnnotSV \
-SVinputFile /test.vcf \
-annotationMode full \
-genomeBuild mm10 \ 
-outputFile . /sample_AnnotSV.tsv

**Comment by lgmgeo** [comment]
Hi @toshi0813,

I can reproduce the bug. I will come back to you asap.

Best,

Véronique

**Comment by lgmgeo** [comment]
Hi,

Sorry for the delay. 
I just pushed a new version v3.2.3 with bugfix.
The bug should be fixed, can you confirm that everything is now working on your side?

Best,
Véronique

**Comment by toshi0813** [comment]
Thank you for fixing the bug.
I believe the issue has been resolved, but the following issue remains unresolved in my environment
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
There is a Gene annotations column in the results, but "Tx", "Tx_start", "Tx_end", "Overlapped_tx_length", "Overlapped_CDS_length", "Overlapped_ CDS_percent ", "Frameshift", "Exon_count", "Location", "Location2", "Dist_nearest_SS", "Nearest_SS_type", "Intersect_start" and "Intersect_ end" are empty.
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

Perhaps this is a problem with my server environment.
Is there anything you can think of that would help me solve this?

Despite the above problems, I was able to do what I wanted to do with the web server interface v3.2.3 !

Before the fix, when I used the web server interface v3.2.2 and used mm10 for genomeBuild, it gave me an error and I could not proceed with the analysis.

**Comment by lgmgeo** [comment]
Really strange, it should be the same on local or with the AnnotSV web server.

In order to have a look at it:
Can you send me the job ID of your try on the web server? 
Or the coordinates of an SV with some empty output values?

**Comment by toshi0813** [comment]
I am sorry for the confusion.
The problem has been resolved.
The cause was that I had executed the command with "-annotationMode full" and only "full" was listed.
I ran the command on my server with the default setting "both" and got exactly the same results as the web server.

Thank you so much for your quick and kind response.

**Comment by lgmgeo** [comment]
Great, good news

**Comment by srbehera** [comment]
I am also getting the same error while annotating an SV vcf (with GRCh38) with v3.3.6
```
	   >>> creation of <PATH>/Annotations_Human/SVincludedInFt/BenignSV/GRCh37/overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tsv] (August 18 2023 - 15:35)
-- checkOverlappedGenesBenignFiles, GRCh37, RefSeq, Loss --
<bedtools_path>/bedtools intersect -sorted -a  -b  -wa -wb > <PATH>/AnnotSV/1692390943_overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tmp.bed
Error: Unable to open file . Exiting.
Exit with error
```
I have used the following command (with ${} values are properly assigned)

```
AnnotSV -bcftools ${bcftools} \
        -bedtools ${bedtools} \
        -annotationsDir ${annotDIr} \
        -outputDir ${annotDIr} \
        -outputFile annotSV_chr1 \
        -SVinputFile ${vcf}
```

**Comment by lgmgeo** [comment]
Hi @srbehera,

If I understood correctly, it works for you on the web server but not in your local installation.

From what I can see, there is an error in your command line: 
`-annotationsDir` and `-outputDir` should not be the same directory.


```
-annotationsDir ${annotDIr} \
```
=> Ok, it's the path of the annotations directory
```
-outputDir ${annotDIr} \
```
=> Incorrect, should be the output path name. 

Please try with the path of a working directory where you have write permissions.

**Comment by lgmgeo** [comment]
> So the annotationsDir should be the one where it is installed, right?

If the annotationsDir is the one by default (`$ANNOTSV/share/AnnotSV/`), please just don't set this option in the command line.
If you move the annotationsDir (e.g. for a Docker user), you need to set the new path.

1 - Actually, only if you want to do a manual installation.
Else, just look at this quick install: https://github.com/lgmgeo/AnnotSV/blob/075d6585b7150e361955b8ac1d9d71ebebf13b10/docs/quickstart.md
with:
```
make PREFIX=. install-human-annotation
```

2 - Exomiser is genome build independant. The previous command is OK for GRCh37/38

3 - Idem. Nothing else to do

**Comment by srbehera** [comment]
Thanks a lot !! Yes, it is working now after I downloaded the annotation files and give the directory name for annotationsDir.

I am now having the issue that already has ben discussed [here](https://github.com/lgmgeo/AnnotSV/issues/15). I can try splitting the input VCF files into smaller ones and run AnnotSV.

**Comment by lgmgeo** [comment]
Thanks for the feedback,
Have fun with AnnotSV
