### ISSUE TITLE
Question about ACMG class 

### ISSUE THREAD

**Issue by omG0-hub** [lgmgeo/AnnotSV#154]
Hello, 

I have a simply question about AnnotSV result,
I obtained the SV annotation result that have a ACMG_class column.
I wonder that what is the mean about "NA" code in ACMG_class column? 
how can i interpret this result?

Thanks,

**Comment by lgmgeo** [comment]
v3.2.3 published, README updated

**Comment by omG0-hub** [comment]
Thanks for the update README file!
