### ISSUE TITLE
Question about VCF version

### ISSUE THREAD

**Issue by toshi0813** [lgmgeo/AnnotSV#155]
Dear @lgmgeo

Thank you very much for your kind response previously.
I have a couple of questions.

When inputting VCF, is there a problem if the vcf version is earlier than 4.3?
The AnnotSV Manual and the web server interface say "VCF file should be compliant with the VCF v4.3."

The test.vcf in the web server interface appears to be the output file from manta.
I believe manta outputs results in version 4.1, how did you get the version 4.3 file?
I would like to know if there is a command or software to convert from 4.1 to 4.3.

Or, to put it simply
What do I have to do to use the output results of manta as an input file for AnnotSV?

**Comment by lgmgeo** [comment]
Hi @toshi0813,

Actually, I specified "VCF file should be compliant with the VCF v4.3." only because I did not test the previous version of VCF.
You can directly use Manta's VCF outputs as an input file for AnnotSV, it should work.
Do not hesitate to come back to me if you encounter any error message.

Best,
Véronique

**Comment by lgmgeo** [comment]
A new VCF version 4.4 is available since January 27, 2023.
I will update/complete the README in a near future on this.

**Comment by toshi0813** [comment]
Thank you for your reply.

I input the manta file directly and did not get any error messages. I overviewed the results and they looked good, so the software seems to have worked correctly.
Is there anything in particular I should check in the output file to make sure the results are OK?

**Comment by lgmgeo** [comment]
No, without error message, the format of the input VCF is sufficient to retrieve data.
Have fun with AnnotSV!
