### ISSUE TITLE
genesAnnotation Error

### ISSUE THREAD

**Issue by dppss90008** [lgmgeo/AnnotSV#159]
Dear author,

I encountered an error, and the program interrupt with following messages.

Here is my command,
/data1/ch.hsieh/AnnotSV_3.2/AnnotSV/bin/AnnotSV -SVinputFile ${wkdir}/SURVIVOR/${sample}_merged.vcf -SVinputInfo 1 -outputFile ${sample}_mergedSV_annotated.tsv -svtBEDcol 4 -outputDir ${wkdir}/Annotated_SV/

Version: AnnotSV 3.2.3 bedtools  v2.30.0

        -svtBEDcol 4
        -tx RefSeq
        ******************************************

-- genesAnnotation --
bedtools intersect -sorted -a /mnt/space4/Annotation/TGSafe/TS230104004/N4549_AA001896/SVcaller/Annotated_SV/20230217-114608_AnnotSV_inputSVfile.formatted.sorted.bed -b /data1/ch.hsieh/AnnotSV_3.1/AnnotSV/share/AnnotSV/Annotations_Human/Genes/GRCh38/genes.RefSeq.sorted.bed -wa -wb > /mnt/space4/Annotation/TGSafe/TS230104004/N4549_AA001896/SVcaller/Annotated_SV/N4549_AA001896_mergedSV_annotated.tsv.tmp.tmp
Error: Invalid record in file /mnt/space4/Annotation/TGSafe/TS230104004/N4549_AA001896/SVcaller/Annotated_SV/20230217-114608_AnnotSV_inputSVfile.formatted.sorted.bed. Record is
M       -1      956     DEL             DEL00041024     C       <DEL>   242     PASS    SUPP=2;SUPP_VEC=010001;SVLEN=-1178;SVTYPE=DEL;SVMETHOD=SURVIVOR1.0.7;CHR2=chrM;END=956;CIPOS=-305,10;CIEND=-957,0;STRANDS=+-    GT:PSV:LN:DR:ST:QV:TY:ID:RAL:AAL:CO     ./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN        ./.:NA:641:0,0:+-:.:DEL:4823:NA:NA:chrM_314-chrM_955    ./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN        ./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN        ./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN        0/0:NA:1178:5585,7:+-:240,242:DEL,DEL:DEL00041024:NA:NA:chrM_304-chrM_956,chrM_-1-chrM_-1
Exit with error

appreciate your help.

**Comment by lgmgeo** [comment]
Hi @dppss90008,

Difficult to understand this bug without your input file to reproduce the bug. 
I think it might be due to the use of CIPOS (because of the negative start location `M -1 956 DEL` ).

To keep the same start and end positions in the AnnotSV results, can you try running AnnotSV with `-includeCI 0`? I guess that should work.
```
-includeCI:                     To expand the "start" and "end" SV positions with the VCF confidence intervals (CIPOS, CIEND) around the breakpoints
                                Values: 1 (default) or 0
```

You can be interested in https://github.com/lgmgeo/AnnotSV/issues/37, https://github.com/lgmgeo/AnnotSV/issues/63, https://github.com/lgmgeo/AnnotSV/issues/73

Best,
Véronique

**Comment by dppss90008** [comment]
Hi Véronique:

It worked, after adding -includeCI 0 !! 
Thank you very much

CH

**Comment by lgmgeo** [comment]
Great! Thank you for the feedback.
