### ISSUE TITLE
Known pathogenic SV

### ISSUE THREAD

**Issue by Nour-EddineS** [lgmgeo/AnnotSV#160]
Dear @lgmgeo,

I run the following command to determine the pathogenicity of my bed file; but in the output file no information on pathogenicity! 

`$ANNOTSV/bin/AnnotSV -SVinputFile Mydata/EX12_SS12_cnv.bed -outputFile ./results.tsv -svtBEDcol 4 -genomeBuild GRCh37`

My bed file : 
[EX12_SS12_cnv.zip](https://github.com/lgmgeo/AnnotSV/files/10823343/EX12_SS12_cnv.zip)

My outputFile : 
[results.zip](https://github.com/lgmgeo/AnnotSV/files/10823379/results.zip)

Thanks in advance for your help.

Best regards,

**Comment by lgmgeo** [comment]
Hi @Nour-EddineS,

Actually, the ranking is present in your results.
You need to look at the `AnnotSV_ranking_score`, `AnnotSV_ranking_criteria` and `ACMG_class`.

For more information on the ranking: https://lbgi.fr/AnnotSV/ranking

For more information on output columns, please refer to the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf):
![image](https://user-images.githubusercontent.com/49909073/221184858-9b1c84fc-53f9-433d-8e9c-1a69a8aa6c42.png)


Best,

Véronique

**Comment by Nour-EddineS** [comment]
@lgmgeo,
I understood well :)
Thank you so much.

Best regards,
