### ISSUE TITLE
Overlooked Benign CNV overlap in ranking

### ISSUE THREAD

**Issue by cathaloruaidh** [lgmgeo/AnnotSV#161]
Hi, 

Firstly, thanks for the tool, it's really useful! 

I'm annotating a set of CNVs and mainly focusing on the ACMG rank provided by AnnotSV (v3.2.2). I'm having an issue with the ranking potentially not factoring in overlapping benign CNVs in its calculation. As an example input, I have the following deletion on GRCh38: 

```
chr4    101345820       101347849       DEL
```

I left all files in the "$ANNOTSV/share/AnnotSV/Annotations_Human/" directory as they were following download. I annotated the deletion with the following command: 

`$ANNOTSV/bin/AnnotSV -genomeBuild GRCh38 -svtBEDcol 4 -overwrite 1 -SVinputFile input.bed -outputDir . -outputFile output.AnnotSV`

The ranking information from the "full" annotation in the output TSV file gives the deletion as Likely Pathogenic:

```
AnnotSV_ranking_score     0.9
AnnotSV_ranking_criteria  1A_(cf_Gene_count,_RE_gene,_+0.00);2C-1_(PPP3CA,_+0.90);3A_(2_genes,_+0.00);5F_(+0.00)
ACMG_class                4
```

However, the input CNV is entirely contained in a common deletion from the DGV: 

```
B_loss_source  esv2657237
B_loss_coord   4:101345388-101348335
B_loss_AFmax   0.1500
```

This benign deletion seems to be ignored, which would have changed the ranking to VUS. I'm not sure if this information is getting lost, or if it's just my implementation of the tool. 

Thanks in advance for your help,
Cathal

**Comment by lgmgeo** [comment]
Dear Cathal,

Thank you for your interest in AnnotSV!

The scoring guidelines used in AnnotSV are available in the [Scoring_Criteria_AnnotSV_latest.xlsx](https://lbgi.fr/AnnotSV/Documentation/Scoring_Criteria_AnnotSV_latest.xlsx) file (see Table1 for loss SV and Table2 for gain SV).
**In each section, only 1 “non-zero value” criterion (from the most pathogenic to the least) is assigned.** “Zero value” criteria are all evaluated (cf the "5. SV RANKING/CLASSIFICATION" section from the [README ](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf)).

In your example, the criterion 2C-1 (PPP3CA,_+0.90) is assigned. So the 2F criterion (-1.00) is not assigned (both are in section 2).

The idea is not to miss a pathogenic SV. In my opinion, it is easier for the bioanalyst to first look at the SV classified as pathogenic and decide if they can explain their patient's clinic (partly thanks to the reported benign annotations, but also thanks to the reported phenotypes).

Hope this makes sense to you,

Best,

Véronique

**Comment by cathaloruaidh** [comment]
Hi Véronique,

Ah, my apologies, I hadn't seen that section of the README, I had thought the scores were cumulative across all sub-categories. 

Just to check: in this instance, since the SV has a pathogenic annotation from Category 2, then Section 4 is also skipped, so the overlapping common deletion should be completely ignored - is that correct?

Thanks again,
Cathal

**Comment by lgmgeo** [comment]
Interesting.
Indeed, the Section 4 (e.g. for Loss) is not evaluated if your CNV overlapped with a pathogenic Loss SV in section 2 (as indicated in the title of the "Section 4" in the Scoring_Criteria_AnnotSV.xlsx

**Comment by cathaloruaidh** [comment]
Hi Véronique,

That's great, thanks for the explanation! 

Cathal
