### ISSUE TITLE
Variants not found after annotation

### ISSUE THREAD

**Issue by priyambial123** [lgmgeo/AnnotSV#162]
Hello

I had a vcf file with 9658 variants. After running annotsv in this file, I had annotated .tsv file with 3798 variants and an unannotated .tsv file with 4857 variants. Both these files add up to 8655 variants and 1003 variants are missing (9658-8655). Why there is no report on these 1003 variants in either annotated or unannotated files

Thank you

**Comment by lgmgeo** [comment]
What version of AnnotSV are you using? Which command line?

**Comment by priyambial123** [comment]
It is annotsv version 3.2.3. I used this command:
`AnnotSV/bin/AnnotSV -SVinputfile "/AnnotSV/bin/sharedvariants.vcf.gz" -genomeBuild GRCh38`

The input vcf file has 9658 variants. After running the annotsv, I got an annotated.tsv file and an unannotaed tsv file as output. I counted the number of variants in both files and got 8655 variants.

**Comment by lgmgeo** [comment]
Any example of missing SV to explain?

**Comment by priyambial123** [comment]
Sorry, I started comparing the files to original vcf and found the number of variants in the input file is not 9658 variants. I will check and will let you know
Thank you

**Comment by lgmgeo** [comment]
If you don't have square-bracketed SV in your VCF input file, you can run this easy command line:
```
gunzip -c sharedvariants.vcf.gz | grep -v "^#" | wc -l
```

**Comment by priyambial123** [comment]
Thank you, I have square bracketed SV and it is 9658 variants, I checked again. After removing duplicates of the variant ID, I have 5792 variants. I could find 3798 variants in the annotated file and in the unannotated file there are 4848 variants. Why there is more number of variants in this unannoated than expected.

In the unannotated tsv file, I have the variant details as:

`1_373857_373857_INS_1: variantLength (35) < SVminSize (50)`

It is difficult to understand which are the variants not annotated in the input vcf dataset.

**Comment by lgmgeo** [comment]
I'm just opening a parenthesis here:
In the future version of AnnotSV (v3.3), the comprehension of the VCF square-bracketed notations will be added. 
Here is an extract of the next README:
![image](https://user-images.githubusercontent.com/49909073/224922122-7b3e6cc0-2d90-417e-8e7f-cd15e0d07d4f.png)


Ok, let's get back to your data.
- You have 5972 variants in the input file.
- Can you run the following command line:
```
# Number of variants in the tsv output file
grep -v "^AnnotSV_ID" sharedvariants.annotated.tsv | grep -v split | wc -l 
```
Normally your result is 3798 from what you wrote, is that correct?
- Can you also run the 2 following command lines and paste the 2 results here?
```
# Number of variants in the VCF input file (with no  duplicate variant ID)
gunzip -c sharedvariants.vcf.gz | grep -v "^#" | cut -f 3 | sort -u | wc -l

# Number of unannotated variants
wc -l sharedvariants.unannotated.tsv
```

> In the unannotated tsv file, I have the variant details as:
> 1_373857_373857_INS_1: variantLength (35) < SVminSize (50)

If you want to annotate all variants (SV but also SNV/indel), you can set the `-SVminSize` option to 1.

> It is difficult to understand which are the variants not annotated in the input vcf dataset. Is there a way to find the variants not annotated in the input vcf.

Normally, unannotated variants should be all reported in the unannotated.tsv output file.
To keep the same coordinates in the AnnotSV_ID output, you can set the `-includeCI` option to 0.

**Comment by priyambial123** [comment]
Thank you for the clear explanation. I could annotate all the variants expect 2 variants by setting it to `-SVminSize`. 

Allele frequency values given in B_gain_AFmax, B_inv_AFmax and B_ B_loss_AFmax columns are calculated from GnomAD, 1000 genomes, Hall et al and DGV studies. Is it right. These four columns only contain the allele frequency values. Is it correct? Is there a setting in the code to find variants with allele frequency less than 0.01

Thank you
