### ISSUE TITLE
Non coding variant annotation-Suggestion

### ISSUE THREAD

**Issue by priyambial123** [lgmgeo/AnnotSV#163]
Hello,

I have a suggestion. Massive parallel reporter assays was performed on 21 regulatory elements. This information is available in this link: https://kircherlab.bihealth.org/satMutMPRA/. This information will be helpful to annotate non-coding variants

Thank you

**Comment by lgmgeo** [comment]
Hi @priyambial123,

Thank you for this interesting suggestion.
I keep this in mind for a futur release with updated annotations.

Best,
Véronique

**Comment by lgmgeo** [comment]
Code was added in the dev branch to integrate MPRA data.
Warning: the names “UC88” and “ZRS” do not correspond to a RefSeq/ENSEMBL gene name. They are not integrated.

This will soon be distributed with the next annotation version.
I will notify you here as soon as the updated annotations are published

**Comment by lgmgeo** [comment]
AnnotSV 3.4 is posted.
