### ISSUE TITLE
Issues creating bioconda recipe

### ISSUE THREAD

**Issue by nvnieuwk** [lgmgeo/AnnotSV#166]
Hi, I'm currently in the process of trying to create a bioconda recipe for AnnotSV, but am running into some issues:

1. When trying to run AnnotSV I get the following error after the recipe has been build: `"ANNOTSV" environment variable not specified. Please defined it before running AnnotSV. Exit with error`. This is a problem because bioconda doesn't support creating custom environment variables as far as I (and the people I asked) know. Is there some way I can work around this?
2. Due to the size of the annotation files I can't include these into the recipe itself. Is it possible to get the annotation files in another way? (e.g. by running some kind of command and passing them to AnnotSV with a flag?)

Bioconda recipe PR: https://github.com/bioconda/bioconda-recipes/pull/40158

Thanks in advance!
-Nicolas

**Comment by lgmgeo** [comment]
Hi Nicolas,

1. I don't really know bioconda, I'll find out and get back to you as soon as possible. If no solution, you will have to cheat with the AnnotSV code (we can see that together)

2. You can use the `-annotationsDir` option (Path of the annotations directory)

Best,
Véronique

**Comment by nvnieuwk** [comment]
Thank you for the quick response!

1. Thank you! I'll be happy to help where I can 
2. Okay! Is there some place I can find the annotations? I think it would be helpful to add these locations to the recipe for future users to know 

-Nicolas

**Comment by lgmgeo** [comment]
>  Is there some place I can find the annotations? I think it would be helpful to add these locations to the recipe for future users to know

Not sure to understand... you want the url where you can download the annotations?

**Comment by matthdsm** [comment]
Hi @lgmgeo 

 - We'd need you to remove the env variable requirement for us to be able to add it to conda and install it in a way we don't need to set the install dir.
 - We need a way to install the software and get a help message of sorts without the requirement of downloading the reference data
 - Lastly, we need a download url or a manual to roll our own for the reference data.

Thanks!
Matthias

**Comment by lgmgeo** [comment]
I will definitely not be able to help with bioconda development. 
So I will do my best with the development of AnnotSV.

**Comment by nvnieuwk** [comment]
Thank you! I'll take the bioconda development part on me if you manage to fix the issues @matthdsm posted earlier

**Comment by lgmgeo** [comment]
> remove the env variable requirement 

Ok, I can have a try

> We need a way to install the software and get a help message of sorts without the requirement of downloading the reference data

With the following commands, no need to download any data:
cd /path/to/install/AnnotSV
make PREFIX=. install

You need an help/install message translating the `make PREFIX=. install-human-annotation`, with instruction to download and move the data at the good place?


> Lastly, we need a download url or a manual to roll our own for the reference data.

The ones I can provide in the help/install message above?

**Comment by nvnieuwk** [comment]
Thank you! We should also make sure that `variantconvert` works in this environment, but that could maybe be solved by making it accessible as an independent package and having AnnotSV call it via the path instead of through a set folder.

**Comment by lgmgeo** [comment]
OK, I just pushed new commits on the "patch_AnnotSV" branch:
>> No more need of $ANNOTSV
>> New "Install" file distributed, with url for annotations download

Can you have a look at it? 
Let me know if this meets your needs.

**Comment by nvnieuwk** [comment]
Yes that would be perfect! Maybe also make it available in the environment as a simple command to execute? (If that's possible of course :) )

**Comment by lgmgeo** [comment]
Bash command?

**Comment by nvnieuwk** [comment]
Yes that would be perfect :)

**Comment by lgmgeo** [comment]
With this default interpreter:
#!/bin/bash

**Comment by nvnieuwk** [comment]
I think that should be fine

**Comment by lgmgeo** [comment]
done on the `patch_AnnotSV` branch

**Comment by nvnieuwk** [comment]
Thank you! I'll give it a go tomorrow

**Comment by nvnieuwk** [comment]
I got it to build and run perfectly in the normal mode, but when trying to build a VCF file I get the following error:

```
AnnotSV 3.3.2

Copyright (C) 2017-2023 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.6

Application name used:
/usr/local


...downloading the configuration data (April 07 2023 - 09:50)
	...configuration data by default
	...configuration data from /usr/local/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

...parsing of candidateSnvIndelFiles for "disease_103" (April 07 2023 - 09:50)
	...parse all positions from test2_haplotc.vcf.gz (April 07 2023 - 09:50)

couldn't change working directory to "/usr/local/share/python3/variantconvert": no such file or directory
    while executing
"cd $variantconvertDIR"
    (procedure "checkVariantconvertConfigfile" line 45)
    invoked from within
"checkVariantconvertConfigfile"
    (file "/usr/local/bin/AnnotSV" line 157)
```

Building was done with this docker image:
```docker
FROM mambaorg/micromamba:1.4-focal

ENV VERSION=3.3.3

# Install mamba dependencies
RUN micromamba install -y --name base -c conda-forge -c bioconda -c defaults \
    git \
    make \
    wget \
    coreutils \
    tk=8.6.12 \
    bedtools=2.30 \
    bcftools=1.16 \
    openjdk=8 \
    unzip \
    python=3.8 \
    natsort=7.1.1 \
    pandas=1.5.3 \
    pyfaidx=0.7.2.1 \
    && micromamba clean --all --yes

USER root

ARG MAMBA_DOCKERFILE_ACTIVATE=1
RUN git clone --branch patch_AnnotSV https://github.com/lgmgeo/AnnotSV.git && \
    cd AnnotSV && \
    make install 

```

**Comment by lgmgeo** [comment]
I'm quite surprised by:
```
Application name used:
/usr/local
```
This should end with "/AnnotSV"

Where did you install AnnotSV?

**Comment by lgmgeo** [comment]
What is the result of:
``` 
ls -l /usr/local/AnnotSV
```

Can you give me your AnnotSV command line?

**Comment by nvnieuwk** [comment]
I used the default location in the docker container (which is `/usr/local`).
To install AnnotSV into conda I need this to work in the way I showed in the docker container. It seems to work perfectly for AnnotSV itself to run, but it's unable to find variantconvert.

The AnnotSV source code is located in a temporary folder (`/tmp`) and not in `/usr/local`

**Comment by nvnieuwk** [comment]
The executable is located at `/usr/local/bin/AnnotSV`

**Comment by lgmgeo** [comment]
May I advise you to change `make install` with `make PREFIX=. install` ("." or another path, whatever)

**Comment by nvnieuwk** [comment]
That's the main problem here. If I do that it will install AnnotSV in a non-conventional folder (like `/tmp` in this case). This will cause the conda build to fail because it needs to be able to install in a specific bin folder. 

A workaround could maybe be to install variantconvert separately and call it from the environment instead of from a set path in the source code? (That would be the least work to adjust I think)

**Comment by lgmgeo** [comment]
I have a bad understanding, sorry

> I used the default location in the docker container (which is /usr/local).

OK

> The AnnotSV source code is located in a temporary folder (/tmp) and not in /usr/local

This is the part I don't understand... Why is this code in /tmp? It should be located in /usr/local/AnnotSV

**Comment by lgmgeo** [comment]
> A workaround could maybe be to install variantconvert separately and call it from the environment instead of from a set path in the source code? (That would be the least work to adjust I think)

Absolutely, yes. No problem.
But I'm frustrated that I don't understand what's going on.

**Comment by nvnieuwk** [comment]
All downloaded files in the container go to `/tmp` where I run the `make install` command which installs AnnotSV and moves the executable to an environmentally accessible location (like `/usr/local` in this case). This makes it so that you can use the tool by simply using `AnnotSV <flags>` instead of having to specify the location of the installation itself. I can't create the bioconda recipe if this isn't possible. The main problem is that this location is variable (especially in a conda environment), so there is no way to hardcode this.

(I'm sorry if some things are unclear, my knowledge isn't that big on this stuff, but I'm learning as we go :))

**Comment by nvnieuwk** [comment]
> > A workaround could maybe be to install variantconvert separately and call it from the environment instead of from a set path in the source code? (That would be the least work to adjust I think)
> 
> Absolutely, yes. No problem. But I'm frustrated that I don't understand what's going on.

We could maybe discuss this with the `variantconvert` developer to publish his tool on `pip` and `conda` this way you can easily install it and set is as a dependency of `AnnotSV` :)

**Comment by lgmgeo** [comment]
Thanks for the explanations.

> We could maybe discuss this with the variantconvert developer to publish his tool on pip and bioconda 

Yes, you can ask at [https://github.com/SamuelNicaise/variantconvert](https://github.com/SamuelNicaise/variantconvert)

> this way you can easily install it and set is as a dependency of AnnotSV :)

I'm going to add a new option "-variantconvertDir", same that "-annotationsDir"

**Comment by nvnieuwk** [comment]
Allright, but that won't really be useful for `bioconda` (but can be helpful for people manually installing the tool). I'll open an issue at `variantconvert` and come back to you once that one has been made available :) 

Thanks for all your patience and helpfulness!

**Comment by lgmgeo** [comment]
I think I have something to improve in my Makefile...
I may be able to get variantconvert to work in bioconda.

Can you just give me the results of these commands:
```
find  /tmp/AnnotSV/ -name "variantconvert"
find /usr/local/  -name "AnnotSV"
find /usr/local/  -name "share"
find /usr/local/  -name "variantconvert"
```

**Comment by nvnieuwk** [comment]
This is the result of those commands:

```
(base) root@05b8f90e1e51:/tmp# find /tmp/AnnotSV/ -name "variantconvert"
/tmp/AnnotSV/share/python3/variantconvert
/tmp/AnnotSV/share/python3/variantconvert/variantconvert
(base) root@05b8f90e1e51:/tmp# find /usr/local/ -name "AnnotSV"
/usr/local/share/tcl8.6/AnnotSV
/usr/local/share/doc/AnnotSV
/usr/local/share/bash/AnnotSV
/usr/local/etc/AnnotSV
/usr/local/bin/AnnotSV
(base) root@05b8f90e1e51:/tmp# find /usr/local/ -name "share"
/usr/local/share
(base) root@05b8f90e1e51:/tmp# find /usr/local/ -name "variantconvert"
```

**Comment by lgmgeo** [comment]
Can you have a new try from scratch? (new install)

**Comment by nvnieuwk** [comment]
It seems to find the directory this time! It just can't open the pipinstall.flag file. Is there another way you can see if the package is installed with pip? 

These are the logs:
```
AnnotSV 3.3.3

Copyright (C) 2017-2023 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.6

Application name used:
/usr/local


...downloading the configuration data (April 07 2023 - 13:49)
	...configuration data by default
	...configuration data from /usr/local/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

...parsing of candidateSnvIndelFiles for "disease_103" (April 07 2023 - 13:49)
	...parse all positions from test2_haplotc.vcf.gz (April 07 2023 - 13:49)

couldn't open "/usr/local/share/python3/variantconvert//pipinstall.flag": permission denied
    while executing
"open $fichier a"
    (procedure "WriteTextInFile" line 2)
    invoked from within
"WriteTextInFile "$Message" $g_AnnotSV(variantconvertDir)/pipinstall.flag"
    (procedure "checkVariantconvertConfigfile" line 45)
    invoked from within
"checkVariantconvertConfigfile"
    (file "/usr/local/bin/AnnotSV" line 157)
```

**Comment by nvnieuwk** [comment]
I basically need to install it as the root user, but am trying to run it as a none-root user

**Comment by lgmgeo** [comment]
My fault, this file should not be present in the git repository. I will add it in the .gitignore file
Sorry

**Comment by nvnieuwk** [comment]
Fingers crossed that's the last thing we have to do :)

**Comment by lgmgeo** [comment]
This flag is created during the first use of AnnotSV, so in your case with a none-root user 
=> permission denied in the AnnotSV install directory (root permission needed)

I need to add this step in the Makefile, the flag will be created with a root user

**Comment by nvnieuwk** [comment]
allright, thanks! Let me know if you want me to try again :)

**Comment by nvnieuwk** [comment]
It also doesn't look like `INSTALL_annotations.sh` and `INSTALL_code.sh` are available in the environment. Could you maybe also add these to the `/usr/local/bin`?

**Comment by lgmgeo** [comment]
I can't get variantconvert to work at the moment, when install is with the root user and use is with a non-root user.
I'll get back to you as soon as possible (not today)

**Comment by lgmgeo** [comment]
OK, everything looks good to me on the patch_annotsv branch 
(AnnotSV install with the root user; AnnotSV run with a non-root user; both in the same environment)

**Comment by nvnieuwk** [comment]
Thank you! I'll give it another try later today :)

**Comment by nvnieuwk** [comment]
I'm not seeing any new commits on that branch since April 7th, or do you mean that the current code works fine for you?

**Comment by lgmgeo** [comment]
Whoops. I forgot to push the commit to github.
It's done now

**Comment by nvnieuwk** [comment]
Awesome! It seems to work in the docker container I created. This should also work now to create a bioconda environment in theory. I'll give that one a go once you released the version containing these fixes. Thanks so much for all the help :)

Just one more thing: Can you make the annotation installation script available in the installation bin folder? That way we can execute `INSTALL_annotations <directory_to_store_annotations>` to download them real quick :)

**Comment by lgmgeo** [comment]
v3.3.4 pushed to master
Thanks again for the bioconda recipe!
(can you email me or give me your email address?)

**Comment by nvnieuwk** [comment]
Thanks I'll give it a go now, I'll keep you posted :) 
I can send you an e-mail, what's your address?

**Comment by lgmgeo** [comment]
fingers crossed!
veronique.geoffroy [at] inserm.fr

**Comment by nvnieuwk** [comment]
AnnotSV has been added to [bioconda](https://anaconda.org/bioconda/annotsv)

A docker image is available [here](https://quay.io/repository/biocontainers/annotsv) and a singularity image is available [here](https://depot.galaxyproject.org/singularity/annotsv%3A3.3.4--py311hdfd78af_0).

Thanks so much for all the help! It will now be even easier to install this tool 🥳
