### ISSUE TITLE
Annotations of benign allele frequency from DDD 

### ISSUE THREAD

**Issue by priyambial123** [lgmgeo/AnnotSV#169]
Hello,

I need some help in annotating the variants in a particular order. Here is my case, I want to exclude the variants which have been annotated as benign in GnomAD, Ira Hall, 1000g, DGV . But, retain the variants which have reported as benign in DDD as these variants allele frequency are reported in developmental disorders which could turn out to be rare in my study samples. From AnnotSV, DDD annotation appears along with other databases and reports allele frequency >=0.01 and sometimes there are also annotations only from DDD. So, is it possible to get annotations from all databases except DDD and after excluding benign variants, can I again submit for annotation from DDD

Thank you

**Comment by lgmgeo** [comment]
Hi @priyambial123,

How do you proceed for the filtering? Is AnnotSV output file integrated in a bioinformatic pipeline?
Or do you filter it manually in a spreadsheet program?

Best,

Véronique

**Comment by priyambial123** [comment]
Hello Véronique

I plan to exclude benign variants by exporting the excel file into R as dataframe and exclude the rows with values allele frequency >=0.01

But, can I annotate the variants from GnomAD, 1000g, DGV except DDD. After filtering in R, then can I annotate in DDD

**Comment by lgmgeo** [comment]
> get annotations from all databases except DDD

- 1st option:
You can filter on the `B_loss_source` or `B_gain_source` features (depending on your SV type, respectively del or dup).
Indeed, the “B_*_source” output values begin with “DDD”. So you can parse the different sources (";" separated) with a script.

- 2nd option: 
You can remove all DDD annotations in:
$ANNOTSV/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh37/benign_Gain_SV_GRCh37.sorted.bed
$ANNOTSV/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh37/benign_Loss_SV_GRCh37.sorted.bed
$ANNOTSV/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh38/benign_Gain_SV_GRCh38.sorted.bed
$ANNOTSV/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh38/benign_Loss_SV_GRCh38.sorted.bed
In parallele, you can add your own DDD annotations. Please look at the "d)	Custom annotations: External BED annotation files (optional)" section in the [README ](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf)
