### ISSUE TITLE
Missing headers in the annotated vcf files

### ISSUE THREAD

**Issue by priyambial123** [lgmgeo/AnnotSV#172]
Hello

I  have my vcf file annotated in AnnotSV as tsv and vcf files. Using bcftools, I tried to extract columns which have been annotated with DDD database as follows:

`bcftools view -i 'INFO/B_gain_source="DDD"' /20230411_AnnotSV/shared_hetero_dp_S3.annotatedheader.vcf" > annotated_ddd_na.vcf`

Some of the header which were in the original vcf file are missing in the annotated vcf file

I got the error as missing headers:
```

[W::bcf_hrec_check] Invalid tag name: "'SampleID'"
[W::bcf_hrec_check] Invalid tag name: "Compound_htz(sample)"
[W::bcf_hrec_check] Invalid tag name: "Count_hom(sample)"
[W::bcf_hrec_check] Invalid tag name: "Count_htz(sample)"
[W::bcf_hrec_check] Invalid tag name: "Count_htz/allHom(sample)"
[W::bcf_hrec_check] Invalid tag name: "Count_htz/total(cohort)"
[W::bcf_hrec_check] Invalid tag name: "Count_total(cohort)"
[W::vcf_parse_format] FORMAT 'AD' at 1:727286 is not defined in the header, assuming Type=String
[W::vcf_parse_format] FORMAT 'DP' at 1:727286 is not defined in the header, assuming Type=String
[W::vcf_parse_filter] FILTER 'NearReferenceGap' is not defined in the header
```

Is it possible to include these headers in the annotated vcf file 

I also query on the annotation part. For example, the SV coordinate is 178432254-178436144 and the B_gain_source coordinate: 178431420-178441455

This annotated B_gain_source coordinate is not near the breakpoints or within the SV coordinates. It lies outside the SV coordinates and there is no overlap. How this B_gain_source coordinate is annotated for this SV coordinate. 

Thank you

Priya

**Comment by lgmgeo** [comment]
Hi Priya,

> Some of the header which were in the original vcf file are missing in the annotated vcf file

The VCF output file is created by the variantconvert tool from the TSV output file.
If I understand correctly, the missing headers are present in the TSV and not in the VCF, right?
If so, may I ask you to post your bug report to https://github.com/SamuelNicaise/variantconvert/issues ?
(perhaps can you also report the TSV header in this post)

> This annotated B_gain_source coordinate is not near the breakpoints or within the SV coordinates. It lies outside the SV coordinates and there is no overlap.

SV coordinates___________: 178 432 254 - 178 436 144 
B_gain_source coordinate: 178 431 420 - 178 441 455

AnnotSV searches for benign genomic regions completely overlapping the SV to annotate, which is the case here.
According to the ACMG technical standards (Riggs et al., 2020), a SV completely contained within an established
benign CNV region would be classified as benign (if sharing the same SV type).

Please, look at the "Known benign genes or genomic regions annotation" section from the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf).

**Comment by priyambial123** [comment]
Sorry, for the ignorant question about the SV coordinates. I will look into the README file.
