### ISSUE TITLE
Null value in the Samples_ID column AND VCF output does not work.

### ISSUE THREAD

**Issue by weichisyu** [lgmgeo/AnnotSV#174]
Hi,
(AnnotSV version 3.2.3)
I cannot obtain annotated VCF output for cases where the input VCF file contains CNVs in DUP type.
Additionally, in the TSV output from these VCF files, the Samples_ID column values are empty for DUP type variants.
**The difference between DEL and DUP is the format in GT, the vcf use './.' to represent the GT in DUP variants. Maybe it is the reason to cause those issues.**
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/119550682/233252533-3690fbdc-9373-4dbb-b2b6-0368133c003d.png">

I thought it is weird to represent the GT in DUP variants with './.'
But after checking the [document](https://samtools.github.io/hts-specs/VCFv4.3.pdf) on page 17,  seems it is the correct representation.

Thanks.

**Comment by lgmgeo** [comment]
Hi @weichisyu,

You provided the correct explanation.

AnnotSV reports in the “Samples_ID” output column the list of the samples ID for which the SV was called (based on the genotype (GT) information). With GT = "./.", we don’t know the status of the SV. Therefore, AnnotSV does not report the sample name in the `Samples_ID`column.

You may be interested in the following FAQ of the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf):
![image](https://user-images.githubusercontent.com/49909073/233962611-b7213a2f-2293-4f13-a57d-c34815cce4e7.png)
 
Best,
Véronique
