### ISSUE TITLE
WARNING: No Exomiser annotations available.

### ISSUE THREAD

**Issue by Yousuk-Song** [lgmgeo/AnnotSV#175]
![스크린샷 2023-04-20 오후 3 06 00](https://user-images.githubusercontent.com/71381603/233272727-48611dce-53a2-47dd-b396-dc39d1273ea9.png)

![스크린샷 2023-04-20 오후 3 07 01](https://user-images.githubusercontent.com/71381603/233272907-95399734-9e99-4605-ac26-a461c5f1f4d5.png)

I precisely followed README, and I certainly downloaded Exomiser data in right path, but I recieved this error message.

**Comment by lgmgeo** [comment]
Hi @Yousuk-Song,

Sorry for the inconvenience.
It looks like the following file is missing:
![image](https://user-images.githubusercontent.com/49909073/233928707-d5085169-ae38-4105-b917-79b558c0dd96.png)

Can you give me your install commands? 
(just to try to reproduce the bug)
Is it something like:
```
cd /path/to/install/
git clone https://github.com/lgmgeo/AnnotSV.git
cd /path/to/install/AnnotSV
make PREFIX=. install
make PREFIX=. install-human-annotation
```
Or did you set a specific PREFIX?
Last question, are you using AnnotSV with the same user used for installation?

Best,
Véronique

**Comment by Yousuk-Song** [comment]
Hi lgmgeo, yes I used exactly the same install commands.

Q1) Can you give me your install commands?

my commands: 

cd /home/juyoung/tmp_song7602/HNSC/Tools
git clone https://github.com/lgmgeo/AnnotSV.git
cd AnnotSV
make PREFIX=. install
make PREFIX=. install-human-annotation

Q2) Or did you set a specific PREFIX?
I just set '.' for PREFIX, following the tutorials, 

Q3) Last question, are you using AnnotSV with the same user used for installation?
yes, I used my colleague's server id for installation of AnnotSV, and also used the same id for running it.

Thank you,
You-suk

**Comment by lgmgeo** [comment]
I'm annoyed because I can't reproduce the bug with AnnotSV 3.3.5.
Can you do another install from scratch and give me the output display?
