### ISSUE TITLE
AnnotSV_ranking_criteria discrepancy

### ISSUE THREAD

**Issue by przemekl** [lgmgeo/AnnotSV#178]
I have two samples with identical variant - 1_1450546_1512545_DEL_1
Ranking criteria for the first sample is  '1A (cf Gene_count, RE_gene, +0.00);2A (cf P_loss_source, +1.00);3A (3 genes, +0.00);40 (cf B_loss_source and po_B_loss_allG_source, -1.00);5F (+0.00)'
For the second one - '1A (cf Gene_count, RE_gene, +0.00);2A (cf P_loss_source, +1.00);3A (3 genes, +0.00);5F (+0.00)'
How is that possible?
(AnnotSV version 3.2)
[27595.txt](https://github.com/lgmgeo/AnnotSV/files/11479348/27595.txt)
[27594.txt](https://github.com/lgmgeo/AnnotSV/files/11479349/27594.txt)

**Comment by przemekl** [comment]
Only a minimal set of options:
export ANNOTSV=/AnnotSV-3.2
$ANNOTSV/bin/AnnotSV \
-SVinputFile $1 \
-genomeBuild GRCh38 \
-outputDir ./AnnotSV_3.2_output

Two input vcf's (renamed) attached.
[27594.vcf.txt](https://github.com/lgmgeo/AnnotSV/files/11479815/27594.vcf.txt)
[27595.vcf.txt](https://github.com/lgmgeo/AnnotSV/files/11479816/27595.vcf.txt)

I will check the new version.

**Comment by lgmgeo** [comment]
OK, I just tested with v3.3.4 and there is no more bug. You confirm ?
Can you upgrade to the latest version?

Really sorry for the inconvenience,
Véronique

**Comment by przemekl** [comment]
Yes, I confirm, for version 3.3.5 the results are consistent.

Thank you very much for your quick response
