### ISSUE TITLE
Incorrect line in the end of file *.annotsv.tsv

### ISSUE THREAD

**Issue by PKazakova** [lgmgeo/AnnotSV#18]
Hello, @lgmgeo!
We have run AnnotSV after [new commit](https://github.com/lgmgeo/AnnotSV/commit/b6fc622c7b769e3ddcb942ff8ea9a3294db9d21a) and have seen the unnecessary line at the end of all output files `*.annotsv.tsv`

![Screenshot_3](https://user-images.githubusercontent.com/54620640/85373744-624b7900-b53c-11ea-8fab-7dfa163520cc.png)
Can you help to solve this problem?

**Comment by lgmgeo** [comment]
Hi PKazakova,

I just pushed a bug fix. Sorry for any inconvenience that may have been caused,

Véronique

**Comment by lgmgeo** [comment]
And thank you for the report !

**Comment by PKazakova** [comment]
Thanks a lot for fix!
