### ISSUE TITLE
CNVs' ID modified in output file

### ISSUE THREAD

**Issue by alfortega** [lgmgeo/AnnotSV#181]
Hi!

First off, many thanks to everyone involved in the AnnotSV project. I do appreciate your dedication to producing a this high-quality tool, and your efforts in maintaining and improving it.

I am writing to inform you about an odd behaviour or potential bug I have encountered while using AnnotSV. There seems to be an issue with how the software handles CNV IDs imported from the DRAGEN Bio-IT platform when provided in the input BED file.

Specifically, when the input BED file includes CNVs' IDs from DRAGEN, the IDs in the AnnotSV output file appear to be modified. Let me provide an example for clarity. Say that in the input BED file, there is a CNV with the ID "DRAGEN:LOSS:chr1:25258202-25331683" corresponding to the deletion in the region "chr1:25258202-25331683". However, in the AnnotSV output file, the ID for the same CNV appears as "DRAGEN:LOSS:chr1:25258203-25331683". As you can see, the start position of the CNV has been modified by adding one base.

This modification of the start position occurs for all IDs included in the input file (that is, all that AnnotSV also outputts). In contrast, the corresponding column for SV_start in the output file appears to be correct. This inconsistent behaviour may lead to confusion or errors in downstream analysis that rely on accurate CNV identification and tracking.

I wanted to bring this issue to your attention so that you know it and can investigate further. It would be greatly appreciated if you could look into this matter and provide any insights or potential solutions. If there are any additional details or files I can provide to help you troubleshoot this bug, please don't hesitate to let me know, and I'll be more than happy to offer them.

Thanks again!
Alfredo Ortega, PhD
University of Helsinki

**Comment by lgmgeo** [comment]
Interesting, thanks for the report of this confusion.

I can explain:
- in a BED file, the first base on the chromosome is numbered 0 (zero indexed).
- in a VCF file, the first base on the chromosome is numbered 1 (one-indexed).

AnnotSV produces a tab-separated values file (tsv) and optionally a VCF file. Both output files are 1-based, with inclusive-end.

I understand that changing the ID is confusing, but having different formats in the annotations is too. So I made the choice to put all the annotations in a single format (one-indexed).

Let me know your feeling about that,
Best,
Véronique
