### ISSUE TITLE
Error with test Data

### ISSUE THREAD

**Issue by kiranpatil222** [lgmgeo/AnnotSV#186]
Hi I have followed all Instructions given for Installation and Human data but i  am getting bellow error

`Application name used:
/data/shared/clinical/ExomeAnalysis/clinical/Scratch/Resources/AnnotSV

...downloading the configuration data (June 15 2023 - 21:33)
        ...configuration data by default
        ...configuration data from /data/shared/clinical/ExomeAnalysis/clinical/Scratch/Resources/AnnotSV/etc/AnnotSV/configfile
        ...configuration data given in arguments
        ...checking all these configuration data

############################################################################
Bad value for the bedtools option (bedtools)
couldn't execute "bedtools": no such file or directory
Exit with error.`

**Comment by kiranpatil222** [comment]
Thanks a Lot it did work, had same issue with BCFTOOLS too, 
there is nowhere in the Installation guide mentioned bedtools and bcftools are required and SET ENV / export

**Comment by kiranpatil222** [comment]
Thanks, but fortunately most of the users do not look in to the PDF doc, rather they see [Install](https://github.com/lgmgeo/AnnotSV/blob/master/docs/quickstart.md) which do have any info, we follow what's on Git home page README guide

**Comment by lgmgeo** [comment]
I will therefore add to look at the README for a detailed installation (in case of problems)
