### ISSUE TITLE
Query on the allele frequency

### ISSUE THREAD

**Issue by priyambial123** [lgmgeo/AnnotSV#188]
Hello,

Benign allele frequency from GnomAD and other databases gives allele frequency  starting from 0.01 and column with blank values. Does this mean these databases don't have allele frequency less than 0.01?.

Thank you

**Comment by lgmgeo** [comment]
Hi @priyambial123,

Actually, common variants can be considered as benign, not the rare variants.

AnnotSV let you the possibility to change the threshold (AF > 0.05 (i.e. 5%), AF > 0.01 (i.e. 1%)…) any time. But not with a too 
low frequency. That's why rare variants are not reported in GnomAD and other databases for benign analyses.
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/1a976d67-1afa-4e36-a79e-940b9af2d3f3)

Best

**Comment by priyambial123** [comment]
Thank you. So, in AnnotSV we have information for allele frequency only for benign analyses?. Allele frequency data for rest of the structural variants are not included? In GnomADSV, there are three data sources, for non-neuro, control and SV sites, which one is included in AnnotSV

**Comment by priyambial123** [comment]
Hi Véronique,

Is it possible to include the information for rare structural variants (allele frequency less than 0.01) from GnomAD SV and other databases. There are also ultra-rare structural variants with allele frequency 0.0001. Can you advice on this, on how to find information on structural variants with very low allele frequency

Thank you

**Comment by lgmgeo** [comment]
> In GnomADSV, there are three data sources, for non-neuro, control and SV sites, which one is included in AnnotSV

**Data sources:** 
Please, look at the [README ](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf), section "gnomAD benign SV annotations":
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/de283252-b6a7-4732-b1c1-fdcde5270652)

**Comment by lgmgeo** [comment]
>in AnnotSV we have information for allele frequency only for benign analyses?

Absolutely, yes
Please, look at the [README ](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf), section "Annotation columns available in the output file"

**Comment by lgmgeo** [comment]
> Is it possible to include the information for rare structural variants (allele frequency less than 0.01) from GnomAD SV and other databases. There are also ultra-rare structural variants with allele frequency 0.0001.

Users can add their own private annotations to the one already provided by AnnotSV.
Please, look at the [README ](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf), section "d) Custom annotations: External BED annotation files (optional)"

**Comment by priyambial123** [comment]
Thank you. I have another query related to the allele frequency in this benign analysis.

What is the percentage of overlap for a structural variant to fall in the B_loss_coord? 

Please let me know if i understood this:

For example, there is deletion in chromosome 12 at start position: 12922185 and end position is: 12922462. In the B_loss_source, B_loss_coord and B_loss_AF there is no value **(from AnnotSV analysis)**. 

I downloaded and used the nstd166 data (gnomAD_SV data) and found a deletion at start position: 12922195 and at end position at 12922462 and with allele frequency of 0.407035. 

Is there a reason why this SV allele frequency is not annotated in the above AnnotSV analysis?

**Comment by lgmgeo** [comment]
Your SV to annotate (12:12922185-12922462) is not  completely overlapped with the SV from nstd166 (12:12922195-12922462). So the SV from nstd166 is not reported in the B_loss_coord. 

Indeed, no way to classify your SV as benign with the  SV from nstd166. You may imagine that `12:12922185:12922195` is a region that could become pathogenic if deleted.


cf README:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/41696bd1-be99-4ada-a91a-621961e2936b)
