### ISSUE TITLE
-txFile option does not work

### ISSUE THREAD

**Issue by genomika-2020** [lgmgeo/AnnotSV#19]
Could you please indicate how  the user transcript file (-given after -txFile option) should be formatted?   
I tried space delimited file and it does not work for me.   
I use Ensembl based sorted.refGene.bed and Ensembl transcripts ids.  
kt

**Comment by lgmgeo** [comment]
Hi,

The `-txFile` option give the path of a file containing a list of preferred genes transcripts to be used in priority during the annotation. 
The corresponding annotations are stored in the `NM` output column (RefSeq identifiers).
It is formatted as follow: the preferred genes transcripts names should be tab or space separated.

For example, you should have something like : `NM_001127325 NM_001310326 NM_001618` (space separated).

Best regards,

Véronique

**Comment by genomika-2020** [comment]
Hi,

Thank you for quick answer. It seems that my txFile is properly formatted.   
I have changed the `refGene.txt.gz` (actually, the `sorted.refGene.bed`) file for Ensembl based - to have `ENST...` transcript names in the annotated file. 
```
wget "ftp://ftp.ensembl.org/pub/current_gtf/homo_sapiens/Homo_sapiens.GRCh38.100.gtf.gz"
wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/gtfToGenePred
chmod +x gtfToGenePred 
zcat Homo_sapiens.GRCh38.100.gtf.gz > Homo_sapiens.GRCh38.100.gtf
 ./gtfToGenePred -genePredExt -geneNameAsName2 Homo_sapiens.GRCh38.100.gtf refGene.txt 
 for i in 1 10 11 12 13 14 15 16 17 18 19 2 20 21 22 3 4 5 6 7 8 9 M MT X Y; do \
awk -v chr=$i '$2 ==chr {print $2"\t"$4"\t"$5"\t"$3"\t"$12"\t"$1"\t"$6"\t"$7"\t"$9"\t"$10}' refGene.txt \
 | sed 's/^MT/M/' | sort -k1,1 -k2,2n -k3,3n >> sorted.refGene.bed; done
```
Everything except this option seems to work fine, but maybe I did something wrong. Could you have a look?
Best regards,
Kasia

**Comment by lgmgeo** [comment]
I will have a look asap.
I will come back to you.

**Comment by lgmgeo** [comment]
Hi,

On my side, your sorted.refGene.bed file works perfectly with the `-txFile` option.

Here what I did:
- I run your commands and created the sorted.refGene.bed file (for GRCh38)
- I copy this file (be careful to the inversion between your file name and the one needed in the installation) in the AnnotSV installation: 
`cp sorted.refGene.bed $ANNOTSV/share/AnnotSV/Annotations_Human/RefGene/GRCh38/refGene.sorted.bed`

Then, I checked all that with a small example:
"test.bed" file:
`1       1613810   1687739    DEL` 
"test.txt" file:
`ENST00000341832`

**Test without the `-txFile` option:**
`$ANNOTSV/bin/AnnotSV -SVinputFile test.bed -outputFile "./test.annotated.tsv" -svtBEDcol 4 -genomeBuild GRCh38`
`gr "CDK11B" "./test.annotated.tsv" | gr split`
=>ENST00000407249

**Test with the `-txFile` option:**
`$ANNOTSV/bin/AnnotSV -SVinputFile test.bed -outputFile "./test_tx.annotated.tsv" -svtBEDcol 4 -txFile test.txt -genomeBuild GRCh38`
`gr "CDK11B" "./test_tx.annotated.tsv" | gr split`
=> ENST00000341832

Can you achieve the same example?

Best,
Véronique

**Comment by genomika-2020** [comment]
Hi,
Yes, I got the desired results with the test example!
Also, when I gave  the previously used "big"  transcript file after the -txFile option.

I use wdl script to run AnnotSV, so probably I wrote something wrong there.

Thank you! 
Best,
Kasia

**Comment by lgmgeo** [comment]
Great!
In a futur version, I will add a new option to choose transcripts from NCBI or ENSEMBL. Thanks for the idea.
Have fun with AnnotSV ;o)
