### ISSUE TITLE
inversions lost

### ISSUE THREAD

**Issue by SplitInf** [lgmgeo/AnnotSV#194]
Hi Véronique

Thank you for making the tool available! 

I have a general question, I noticed that in some cases inversions "MantaBND" from manta would get filtered out after running annotsv even though it has the PASS flag and sufficient depth. 

Is it because of the square bracketed ALT?
e.g. TCCTATCCTCCAGTTT]chr13:24129634]

How would you suggest one to go about troubleshooting this?

**Comment by lgmgeo** [comment]
Hi @SplitInf,

May you please send me:
- the AnnotSV command line you run 
- the AnnotSV version
- a VCF with a single SV input line? (VCF file is not accepting here, please change the extension to txt `vcfFile.vcf.txt`)

It will be easier to understand.

Best,
Véronique

**Comment by lgmgeo** [comment]
Any news ?
