### ISSUE TITLE
gnomAD SV INS effect on ranking score / ACMG class

### ISSUE THREAD

**Issue by dennishendriksen** [lgmgeo/AnnotSV#196]
Good day @lgmgeo,

I'm trying to understand the AnnotSV output for [this gnomAD SV insertion](https://gnomad.broadinstitute.org/variant/INS_2_10274?dataset=gnomad_sv_r2_1). Based on the allele count, number of homozygotes and allele frequency and keeping into account population and sex I would expect this SV to be classified as `LB`. The actual output for ACMG_class is `NA` with no values for AnnotSV_ranking_score/AnnotSV_ranking_criteria.

How does AnnotSV arrive at the `NA` classification? Looking at the GAIN scoring criteria my understanding is that this is part of section 4O `Overlap with common population variation`, but the annotation columns used are empty in the output.

Running AnnotSV v3.3.6 with:
- input [INS_2_10274.vcf.gz](https://github.com/lgmgeo/AnnotSV/files/12800136/INS_2_10274.vcf.gz)
- genomeBuild `GRCh37`
- annotationMode `full`

Results in output [INS_2_10274.tsv.gz](https://github.com/lgmgeo/AnnotSV/files/12800284/INS_2_10274.tsv.gz)

Thank you for creating and maintaining this valuable tool!

Greetings,
@dennishendriksen

**Comment by lgmgeo** [comment]
Hi @dennishendriksen,

Thank you for your interest in AnnotSV.
Actually, AnnotSV ranking is only available for gains (DUP) and losses (DEL), following the ACMG/ClinGen guidelines. 
The INS are not yet ranked.

Thanks for your feedback. I will add details in the README on this subject. 

Best,
Véronique

**Comment by dennishendriksen** [comment]
Thank you for the clarification!
