### ISSUE TITLE
'etc/AnnotSV/configfile' disable annotation function does not Work

### ISSUE THREAD

**Issue by Overinterested** [lgmgeo/AnnotSV#197]
Hi Véronique

Thank you for making one of the best SV annotation tool!
I have a question. I try to add "#" before some annotation in 'etc/AnnotSV/configfile' to ignore some columns in result annotation file(like following example), but it does not work and still output such column.
#B_gain_AFmax
#B_loss_source
#B_loss_coord

Is it a bug?

**Comment by Overinterested** [comment]
Sorry to reopen this issue. I try the latest version of AnnotSV, and it seems to still annotate the type but just not to output? 
For example, I only want to annotate gene, and other database will be ignored. (However I know this seems a rather strict and unreasonable requirement)
[configfile.txt](https://github.com/lgmgeo/AnnotSV/files/13012684/configfile.txt)

**Comment by lgmgeo** [comment]
Hi @Overinterested,

In order to disable default annotations provided by AnnotSV, some column names can be commented with a hash character ("#") by the user.
However, those marked with an * (as #B_gain_AFmax, #B_loss_source, #B_loss_coord) in the distributed configfile are necessary for the ranking and cannot be removed.

Hope this is clearer,
Best,
Véronique

**Comment by lgmgeo** [comment]
FYI:
`cut` is a command-line tool commonly used to extract a portion of text from a file and print the result to a standard output. 
You can use it to keep only the output column of interest from an AnnotSV tsv output file.

**Comment by lgmgeo** [comment]
I contacted the author, I know he is actively working on a new version. 
It should give you an answer quickly.

**Comment by Overinterested** [comment]
> FYI: `cut` is a command-line tool commonly used to extract a portion of text from a file and print the result to a standard output. You can use it to keep only the output column of interest (gene) from an AnnotSV tsv output file.

Thanks for your quick reply, and I may know it
