### ISSUE TITLE
SVinputFile too big

### ISSUE THREAD

**Issue by jingydz** [lgmgeo/AnnotSV#198]
I submitted the vcf file in http://lbgi.fr/AnnotSV/.
But, I get this error. "Job with id "wJOjos6Sem" has failed. SVinputFile too big"

**Comment by lgmgeo** [comment]
Hi @jingydz,

Due to storage constraints, we only allow the submission of VCF input files with SV of a maximum size of 10MB.
Please, remove large SV from your VCF input file before submitting them online. Else, please use a local AnnotSV installation.

Best,

Véronique

**Comment by jingydz** [comment]
thank you. I changed the vcf file into bed file.
It's only 2.2M, and it succeed.
(the raw vcf file size is 1.1G)

**Comment by lgmgeo** [comment]
Great, thanks for your feedback!

**Comment by lgmgeo** [comment]
Warning added on the RunJob page:

![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/bd61af35-e0c4-4f66-8010-456aa6dcdfd6)

**Comment by lgmgeo** [comment]
The README will be updated in the next version.
