### ISSUE TITLE
domain error: argument not in valid range

### ISSUE THREAD

**Issue by Qijie0615** [lgmgeo/AnnotSV#199]
domain error: argument not in valid range
    while executing
"expr {($po_end-$po_start)*100.0/($endP-$startP)}"
    (procedure "poPathogenicSVannotation" line 64)
    invoked from within
"poPathogenicSVannotation $SVchrom $SVleft $SVright"
    (procedure "OrganizeAnnotation" line 767)
    invoked from within
"OrganizeAnnotation"
    (file "/data/yangqj/software/AnnotSV-3.2.1/bin/AnnotSV" line 282)
I'm using version 3.2.1, and I still have the same error report.
Thanks very much for your help

**Comment by Qijie0615** [comment]
I tried v3.3.1 and v3.3.6 at the same time, and it failed with an error.

**Comment by lgmgeo** [comment]
mmmm... quite difficult to help you without more information.
I need to reproduce the bug.

Can you please share your AnnotSV input file and command line?
(You can isolate the SV from your input file that causes the bug and only send me this as an example)

**Comment by Qijie0615** [comment]
thanks for your reply.
The command line is as follows：
$ANNOTSV/bin/AnnotSV -SVinputFile "/mbak/yangqj/SV202309/annotsv/AD/rare34/a.vcf" -annotationMode both -SVminSize 0 -bcftools $bcftools -bedtools $bedtools -outputFile /mbak/yangqj/SV202309/annotsv/AD/rare34/Rare.CNV034.a.tsv -genomeBuild GRCh38 -annotationsDir /data/yangqj/software/AnnotSV-3.3.1/share/AnnotSV/


I’ve attached the inputfile.






Rainbow
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lgmgeo/AnnotSV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月26日(星期四) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lgmgeo/AnnotSV] domain error: argument not in valid range (Issue #199)





 
mmmm... quite difficult to help you without more information.
 I need to reproduce the bug.
 
Can you please share your AnnotSV input file and command line?
 (You can isolate the SV from your input file that causes the bug and only send me this as an example)

**Comment by lgmgeo** [comment]
Sorry, I can't see any attached input file...
Can you try attaching it again after changing the extension from ".vcf" to ".vcf.txt"?

**Comment by lgmgeo** [comment]
Quite strange... it does not work.

Can you email me your .vcf.txt file?
(veronique.geoffroy@inserm.fr)

**Comment by Qijie0615** [comment]
ok




Rainbow
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lgmgeo/AnnotSV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月26日(星期四) 晚上10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lgmgeo/AnnotSV] domain error: argument not in valid range (Issue #199)





 
Quite strange... it does not work.
 
Can you email me your .vcf.txt file?
 ***@***.***)

**Comment by lgmgeo** [comment]
Can you try version v3.3.7? 
The bug should be fixed.

**Comment by Qijie0615** [comment]
I am sorry for the late reply. Thank you so much !! it ran to completion without error.

**Comment by lgmgeo** [comment]
Thanks for the feedback!
