### ISSUE TITLE
Version AnnotSV 2.4

### ISSUE THREAD

**Issue by Jordi-V** [lgmgeo/AnnotSV#20]
Dear all,

in the changeLog.txt appear a new version of AnnotSV 2.4, is avaliable if we git clone the repository as describe in the Readme file? I mention this beacuse is confused which version is the lastest one... some files are named as 2.3.2 and for example the changeLog.txt appear this new version from July month...

Thanks for your help

Jordi

**Comment by lgmgeo** [comment]
Sorry, my fault, it's confusing. I did a mistake while pushing the changeLog.txt.
AnnotSV 2.4 is going to be available soon.
But just to let you know, the version available on github is working.
 
Véronique

**Comment by lgmgeo** [comment]
I will correct the version number this week-end

**Comment by Jordi-V** [comment]
Thanks!

**Comment by lgmgeo** [comment]
AnnotSV 2.3.3 is posted.
AnnotSV 2.4 will be available soon.
