### ISSUE TITLE
query on the results

### ISSUE THREAD

**Issue by ttzhao123** [lgmgeo/AnnotSV#200]
hello,  I have recently encountered some issues while using the AnnotSV, and I would like to inquire about them. 
**Qestion 1:**
Why does the position of some SVs change after being annotated by AnnotSV?
for example:
vcf:
chr16   29227393        MantaDUP:TANDEM:3465:0:1:3:0:0  A       <DUP:TANDEM>    42      PASS    END=88193183;SVTYPE=DUP;SVLEN=58965790;IMPRECISE;CIPOS=-665,665;CIEND=-438,438      GT:FT:GQ:PL:PR  0/1:PASS:42:92,0,260:18,8       0/0:HomRef:39:11,0,258:17,3     0/0:HomRef:77:0,27,243:14,1

AnnotSV.tsv
16_29226728_88193621_DUP_1      16      29226728        88193621        58965790        DUP     fyx     MantaDUP:TANDEM:3465:0:1:3:0:0      A       <DUP:TANDEM>    42      PASS    END=88193183;SVTYPE=DUP;SVLEN=58965790;IMPRECISE;CIPOS=-665,665;CIEND=-438,438  GT:FT:GQ:PL:PR      0/1:PASS:42:92,0,260:18,8       0/0:HomRef:39:11,0,258:17,3     0/0:HomRef:77:0,27,243:14,1     full    q24.2-p11.1 
**Question 2:**
Why is there only DUP and DEL in the result AnnotSV.tsv file? Is there a problem with my VCF file format or something else?
for example:
chr1    29055666        MantaBND:2:3253:3254:0:2:0:0    G       G[chr2:238500741[       686     PASS    SVTYPE=BND;MATEID=MantaBND:2:3253:3254:0:2:0:1;CIPOS=0,1;HOMLEN=1;HOMSEQ=G;BND_DEPTH=120;MATE_BND_DEPTH=122 GT:FT:GQ:PL:PR:SR       0/1:PASS:421:471,0,665:27,2:26,14   0/1:PASS:162:212,0,845:42,2:31,7        0/1:PASS:103:153,0,662:32,0:17,7
chr1    29100313        MantaBND:2:10463:10473:0:0:0:0  C       C]chr16:23517543]       198     NoPairSupport   SVTYPE=BND;MATEID=MantaBND:2:10463:10473:0:0:0:1;CIPOS=0,16;HOMLEN=16;HOMSEQ=AAAAAAATTAGCTGGG;BND_DEPTH=117;MATE_BND_DEPTH=196      GT:FT:GQ:PL:PR:SR           0/1:MinGQ:6:54,0,999:56,0:43,8  0/1:PASS:133:183,0,552:25,0:23,7        0/1:PASS:59:109,0,570:24,0:24,7
thank you

**Comment by lgmgeo** [comment]
Hi @ttzhao123,

**Question 1:**
AnnotSV expands the "start" and "end" SV positions with the VCF confidence intervals (CIPOS, CIEND) around the breakpoints.
(In your example: `CIPOS=-665,665;CIEND=-438,438`)
If you want to keep the input coordinates, please set the -includeCI to 0.
```
-includeCI:                     To expand the "start" and "end" SV positions with the VCF confidence intervals (CIPOS, CIEND) around the breakpoints
                                Values: 1 (default) or 0
```

**Question 2:**
Please, look at the report of unannotated variants (“.unannotated.tsv” file) for specific explanation.
cf README:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/e13c79cc-db89-4c1e-857d-c1142078e2fd)

Best,
Véronique

**Comment by lgmgeo** [comment]
In your case, you have square bracketed notations. e.g.: `G[chr2:238500741[`

FYI, see the "Output file path(s) and name(s)" section from the README:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/70aa3e4d-695c-43aa-84b7-12ca25985423)

**Comment by lgmgeo** [comment]
Note for square-bracketed ALT notation:

The comprehension of the square-bracketed notations relies on the [homogenization rules ](https://github.com/EUCANCan/variant-extractor#homogenization-rules) from the [variantextractor tool](https://github.com/EUCANCan/variant-extractor) (provided by Rodrigo Martin).
- For duplication, inversion, deletion and insertion, AnnotSV returns one full annotation per SV (one full
annotation per breakend pair). For this reason, considering paired breakends, the ALT feature with the
lowest position is returned.

- Else (translocation, complexe SV…), both breakends are annotated.

**Comment by ttzhao123** [comment]
Thank you very much for your answer, I completely understand the first question now. But for the question 2, I wanted to ask about none of translocation, complexe SV... and even inversion, insertion annotatation results didn't show up in the output. could you give more explanation or examples about this?

**Comment by lgmgeo** [comment]
Sorry I close this issue by error

**Comment by lgmgeo** [comment]
I'm not sure I understand you well

Your translocation example from question 2: 
``` 
chr1 29055666 MantaBND:2:3253:3254:0:2:0:0 G G[chr2:238500741[ 686 PASS SVTYPE=BND;MATEID=MantaBND:2:3253:3254:0:2:0:1;CIPOS=0,1;HOMLEN=1;HOMSEQ=G;BND_DEPTH=120;MATE_BND_DEPTH=122 GT:FT:GQ:PL:PR:SR 0/1:PASS:421:471,0,665:27,2:26,14 0/1:PASS:162:212,0,845:42,2:31,7 0/1:PASS:103:153,0,662:32,0:17,7
```
I run AnnotSV with this SV input file (test.vcf):
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/cdbf714d-6ff3-41f6-8777-c3ec301d5f20)

And this translocation is annotatated (test.annotated.vcf):
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/66e74dae-8dd9-4673-972d-3b65f5875fe1)


What is your problem?

**Comment by lgmgeo** [comment]
Any news?

**Comment by ttzhao123** [comment]
No more questions for now, thank you
