### ISSUE TITLE
gnomad V4

### ISSUE THREAD

**Issue by gevro** [lgmgeo/AnnotSV#201]
Hi, gnomad v4 SV annotations were just released. Will this be added as a new default annotation?
Thanks

**Comment by lgmgeo** [comment]
Hi @gevro,
Yes for sure. It will be updated in the new annotation version (December or January).
Best,
Véronique

**Comment by jchenpku** [comment]
I'm about to ask the same question and it's great to hear the good news. Thanks!

**Comment by lgmgeo** [comment]
Sorry, I didn't find time to finalize the annotation updates at the end of this busy year.
I have blocked the last 2 weeks of the end of January, it will be done before this deadline.

**Comment by lgmgeo** [comment]
Code was added in the dev branch to integrate the benign SV annotation of "gnomad v4" (GRCh38).
This will soon be distributed with the next annotation release.
I will notify you here as soon as the updated annotations are published

**Comment by lgmgeo** [comment]
FYI: 
In gnomAD r4, “Controls and biobanks” correspond only to samples collected specifically as controls for disease studies or samples belonging to biobanks (e.g. BioMe, Genizon) or general population studies (e.g., 1000 Genomes, HGDP, PAGE). 
=> Therefore, in AnnotSV, “AF”, “AN” and “N_HOMALT” values are extracted from this collection.

**Comment by lgmgeo** [comment]
AnnotSV 3.4 is posted.
