### ISSUE TITLE
PacBio pipeline structural variant annotations

### ISSUE THREAD

**Issue by gevro** [lgmgeo/AnnotSV#202]
Hi,
PacBio recently released a comprehensive variant calling pipeline, including for structural variants: 

They provide new structural variant annotation resources, including for long-read. Are you able to also add these to annotSV as standard annotations? These details were provided by the PacBio bioinformatics team.

All available at Zenodo (https://zenodo.org/records/8415406) with READMEs

1. DECODE SV:
    REFERENCE   Beyter, et al. Nat. Genetics, 2021, doi: 10.1038/s41588-021-00865-4
    URL        https://github.com/DecodeGenetics/LRS_SV_sets/blob/master/ont_sv_high_confidence_SVs.sorted.vcf.gz?raw=true
 
2. EEE_SV
    REFERENCE   Audano 2019. doi:10.1016/j.cell.2018.12.019.
    URL        http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/hgsv_sv_discovery/working/20181025_EEE_SV-Pop_1/VariantCalls_EEE_SV-Pop_1/EEE_SV-Pop_1.ALL.sites.20181204.vcf.gz
 
3. HPRC: 103 HPRC (year 1 and 2) and GIAB (HG001, HG003, HG004, HG006, HG007) samples:
  URL gs://pacbio-wdl/dataset/GRCh38/sv_pop_vcfs/hprc.GRCh38.pbsv.vcf.gz

Thanks!

**Comment by lgmgeo** [comment]
Thank you for this interesting suggestion!
I will do my best for the next annotation version (January).

**Comment by lgmgeo** [comment]
Can you tell me more about what new annotation columns you would like?

**Comment by gevro** [comment]
Hi, I looked at the vcfs and made a summary of my suggestions - but feel free to disagree since you're the expert!

**HPRC (gs://pacbio-wdl/dataset/GRCh38/sv_pop_vcfs/hprc.GRCh38.pbsv.vcf.gz)**

Basic SV info:
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the structural variant described in this record">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SVANN,Number=.,Type=String,Description="Repeat annotation of structural variant">
##ALT=<ID=INV,Description="Inversion">
##ALT=<ID=DUP,Description="Duplication">

POP freq info:
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=AC_Hom,Number=A,Type=Integer,Description="Allele counts in homozygous genotypes">
##INFO=<ID=AC_Het,Number=A,Type=Integer,Description="Allele counts in heterozygous genotypes">
##INFO=<ID=AC_Hemi,Number=A,Type=Integer,Description="Allele counts in hemizygous genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele frequency">

Which SVs to include: Either annotate only FILTER=PASS variants, or annotate all of them and further annotate the VCF FILTER column, which contains a list of PASS or one or more of these filters:
##FILTER=<ID=NearContigEnd,Description="Variant is near (< 1000 bp) from the end of a contig">
##FILTER=<ID=InsufficientStrandEvidence,Description="Variant has insufficient number of reads per strand (< 0).">
##FILTER=<ID=Decoy,Description="Variant involves a decoy sequence">
##FILTER=<ID=NearReferenceGap,Description="Variant is near (< 1000 bp) from a gap (run of >= 50 Ns) in the reference assembly">

Lower priority:
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="Confidence interval around POS for imprecise variants">
##INFO=<ID=MATEID,Number=.,Type=String,Description="ID of mate breakends">
##INFO=<ID=MATEDIST,Number=1,Type=Integer,Description="Distance to the mate breakend for mates on the same contig">
##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Imprecise structural variation">
##INFO=<ID=NotFullySpanned,Number=0,Type=Flag,Description="Duplication variant does not have any fully spanning reads">
##INFO=<ID=MAF,Number=1,Type=Float,Description="Frequency of the second most common allele">
##INFO=<ID=HWE,Number=A,Type=Float,Description="HWE test (PMID:15789306); 1=good, 0=bad">
##INFO=<ID=ExcHet,Number=A,Type=Float,Description="Test excess heterozygosity; 1=good, 0=bad">


**EEE_SV** (http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/hgsv_sv_discovery/working/20181025_EEE_SV-Pop_1/VariantCalls_EEE_SV-Pop_1/EEE_SV-Pop_1.ALL.sites.20181204.vcf.gz)

Basic SV info:
##ALT=<ID=INS,Description="Insertion of novel sequence relative to the reference">
##ALT=<ID=DEL,Description="Deletion relative to the reference">
##ALT=<ID=INV,Description="Inversion of reference sequence">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Difference in length between the REF and ALT alleles">
##INFO=<ID=END,Number=1,Type=Integer,Description="Reference end position of the variant">
##INFO=<ID=REPEAT_TYPE,Number=1,Type=String,Description="Repeat annotation for a structural variant">

Pop freq info:
##INFO=<ID=MERGE_AC,Number=1,Type=Integer,Description="Number fo samples containing a variant represented by this record">
##INFO=<ID=MERGE_AF,Number=1,Type=Integer,Description="Frequency of variant in discovery samples">
##INFO=<ID=CONTIG_SUPPORT,Number=1,Type=Integer,Description="Number of contigs supporting this variant">
##INFO=<ID=CONTIG_DEPTH,Number=1,Type=Integer,Description="Number of contigs at the variant locus">

Lower priority:
##FORMAT=<ID=CS,Number=1,Type=Integer,Description="Number of local assembly contigs supporting this variant">
##FORMAT=<ID=CD,Number=1,Type=Integer,Description="Number of local assembly contigs at this location">
##FORMAT=<ID=RO,Number=1,Type=Float,Description="Reciprocal overlap (RO) between representative SV and the best SV in this sample by RO">


**ONT SV** (https://github.com/DecodeGenetics/LRS_SV_sets/blob/master/ont_sv_high_confidence_SVs.sorted.vcf.gz?raw=true)

Basic SV info
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the structural variant">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##ALT

Pop freq info:
I found pop freq info in the suppl data of the paper (https://www.nature.com/articles/s41588-021-00865-4):

Download here: https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-021-00865-4/MediaObjects/41588_2021_865_MOESM5_ESM.zip -> contains 'freq' column

Critical note: the order of the variants is chr1, chr10, chr11 in the csv in the above zip file, whereas it is chr1, chr2, etc in the VCF file. So it looks like joining the freq column here to the vcf should be performed by matching the 'Name' column in csv = ID column in VCF.

Lower priority:
##INFO=<ID=TRRBEGIN,Number=1,Type=Integer,Description="Begin position of the Tandem Repeat Region the structural variant is in">
##INFO=<ID=TRREND,Number=1,Type=Integer,Description="End position of the Tandem Repeat Region the structural variant is in">

**Comment by priyambial123** [comment]
To add, also the gnomad structural variants version 4 has been released this month 
https://gnomad.broadinstitute.org/news/2023-11-v4-structural-variants

**Comment by gevro** [comment]
Hi, I'm curious if this will be part of an upcoming release? Thanks!

**Comment by lgmgeo** [comment]
yes, for sure

**Comment by gevro** [comment]
Hi, Just checking if these annotations will also be part of the next release?

**Comment by lgmgeo** [comment]
I'm in process to update AnnotSV annotations. It's quite long. 
I plan to review the PacBio data next week.
I will keep you posted here very soon

**Comment by lgmgeo** [comment]
Ok, now I'm working on the PACBIO data.

HPRC and EEE sources look good.

But I have some misunderstandings about the ONT VCF files.
I am not going to integrate this source.

As an example, let's look at this DEL:
```
chr1    714294  chr1:714294:DN  AACAGTAATTGCTATATTGCTTATTTCTGAGTAGAAGAATATGAGACATTTCCCTAATCATTATGTGTAATTACAATTACATAGAAGAATATGAGACATTTC  ATAGCAATTGCTATATTGCTTATTTAGAGAAAATATGAGACATTT   0       .       END=714395;SV
TYPE=DEL;SVLEN=-54;TRRBEGIN=.;TRREND=.
```
For me, it's a complex SV (INS/DEL), not a simple DEL. It is therefore quite dangerous to integrate this SV into AnnotSV as `chr1:714294-714395 DEL` (freq = 0.99936, => benign DEL)

**Comment by gevro** [comment]
Hi!
Regarding (1): I thought annotSV annotates everything, including the AF of the SV in the reference dataset, and then the user can set an AF threshold when filtering. Wouldn't that be better than only annotating SVs above a hard-coded AF?

Regarding (2): I agree, something must be a bit wrong with that annotation, even though it is used widely. So I think it is best to leave it out.

Thanks!

**Comment by lgmgeo** [comment]
Regarding (1):
- Distributed benign SV annotation file:
 General criteria: AnnotSV includes all SV with AF > 0.1% only if ≥ 500 individuals tested (so we can be sure of the AF).
(this is not the case for the HPRC and the EEE. It therefore seems quite difficult to me to assess whether an SV is benign or not)
- While running AnnotSV:
By default, -benignAF is set to 1%
But the user can change this setting in USAGE/OPTIONS (from 0.1% to 10%).
Why not to use a hard-coded AF threshold?
For example, with a rare disease, 1% or even 0.1% is relevant.
But with some more common disease, 5% is better

**Comment by lgmgeo** [comment]
AnnotSV annotates all SV:

According to the ACMG technical standards, a SV completely contained within an established benign CNV region would be classified as benign (if sharing the same SV type).
=> AnnotSV searches for benign SV completely overlapping the SV to annotate.

**Comment by gevro** [comment]
Ok understood - thanks for explaining. In that case I think your criteria you proposed for HPRC and EEE make sense.

**Comment by lgmgeo** [comment]
I'm quite confused with the EEE dataset.
After long reflection and discussion with colleagues, it does not seem wise to integrate benign SV from a cohort of only 15 individuals. This is not robust enough for frequencies.
I will therefore not integrate this EEE dataset into the next release.
I will only integrate the HPRC dataset.

**Comment by priyambial123** [comment]
Yes, it was bit difficult to understand. So, first they did long read sequencing in 15 individulas and identified approx 99000 structural variants. These variants were verified with short range sequencing of 440 individuals and the allele frequency from these individuals were also reported. So, the structural variants which are shown to have common allele frequency (from 440 genomes data)  were originally identified by long-range sequencing. 
 ```
REFERENCE   Audano 2019. doi:10.1016/j.cell.2018.12.019.
 URL         http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/hgsv_sv_discovery/working/20181025_EEE_SV-Pop_1/VariantCalls_EEE_SV-Pop_1/EEE_SV-Pop_1.ALL.sites.20181204.vcf.gz
```

**Comment by lgmgeo** [comment]
I indeed looked at the "EEE_SV-Pop_1.ALL.sites.20181204.vcf.gz" file, in particular the AF data:
``` 
gunzip -c EEE_SV-Pop_1.ALL.sites.20181204.vcf.gz | grep -v "^#" | cut -f 8 | tr ";" "\n" | grep MERGE_AF | sort -u
MERGE_AF=0.07
MERGE_AF=0.13
MERGE_AF=0.20
MERGE_AF=0.27
MERGE_AF=0.33
MERGE_AF=0.40
MERGE_AF=0.47
MERGE_AF=0.53
MERGE_AF=0.60
MERGE_AF=0.67
MERGE_AF=0.73
MERGE_AF=0.80
MERGE_AF=0.87
MERGE_AF=0.93
MERGE_AF=1.00
```
As you can see, the AF is calculated with only the 15 individuals. That's why I can not integrate EEE dataset in AnnotSV.

**Comment by priyambial123** [comment]
Here is the link which is working, checked it
https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/hgsv_sv_discovery/working/20181025_EEE_SV-Pop_1/

 

    On Monday, 5 February, 2024 at 10:34:04 am GMT+1, Priya Arasu ***@***.***> wrote:  
 
 I am sorry sending the file without checking. This file is from the same group, with data from 440 individualshttp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/hgsv_sv_discovery/working/20181025_EEE_SV-Pop_1/VariantCalls_EEE_SV-Pop_1/EEE_SV-Pop_1.ALL.genotypes.20181204.vcf.gz



 

    On Monday, 5 February, 2024 at 09:42:52 am GMT+1, Geoffroy Véronique ***@***.***> wrote:  
 
 


I indeed looked at the "EEE_SV-Pop_1.ALL.sites.20181204.vcf.gz" file, in particular the AF data:
gunzip -c EEE_SV-Pop_1.ALL.sites.20181204.vcf.gz | grep -v "^#" | cut -f 8 | tr ";" "\n" | grep MERGE_AF | sort -u
MERGE_AF=0.07
MERGE_AF=0.13
MERGE_AF=0.20
MERGE_AF=0.27
MERGE_AF=0.33
MERGE_AF=0.40
MERGE_AF=0.47
MERGE_AF=0.53
MERGE_AF=0.60
MERGE_AF=0.67
MERGE_AF=0.73
MERGE_AF=0.80
MERGE_AF=0.87
MERGE_AF=0.93
MERGE_AF=1.00

As you can see, the AF is calculated with only the 15 individuals. That's why I can not integrate EEE dataset in AnnotSV.

**Comment by priyambial123** [comment]
Here is the link which is working, checked it (440 genomes)

https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/hgsv_sv_discovery/working/20181025_EEE_SV-Pop_1/

**Comment by lgmgeo** [comment]
This one?
https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/hgsv_sv_discovery/working/20181025_EEE_SV-Pop_1/Genotypes_EEE_SV-Pop_1/EEE_SV-Pop_1.ALL.genotypes.20181204.vcf.gz

**Comment by gevro** [comment]
Hi, I agree I think it makes more sense to use the EEE vcf where they genotyped the SVs they first found in 15 long read individuals in 440 other individuals, since the AF estimates will be a lot more robust.

**Comment by gevro** [comment]
Ok, I defer to whatever your best opinion is.

**Comment by lgmgeo** [comment]
Anyway, this discussion is really interesting. Thank you for sharing. 
This EEE dataset will undoubtedly grow in the near future, this will be more interesting then.

**Comment by priyambial123** [comment]
Thank you. Will you be including allele frequency information from GnomAD recent release 
https://gnomad.broadinstitute.org/news/2023-11-v4-structural-variants

**Comment by lgmgeo** [comment]
> Thank you. Will you be including allele frequency information from GnomAD recent release https://gnomad.broadinstitute.org/news/2023-11-v4-structural-variants

yes, cf https://github.com/lgmgeo/AnnotSV/issues/201

**Comment by lgmgeo** [comment]
AnnotSV 3.4 is posted.
