### ISSUE TITLE
Is it possible to add annotations for the breakpoints?

### ISSUE THREAD

**Issue by xiucz** [lgmgeo/AnnotSV#203]
Hi, 
When I was working on DNA fusion genes(EML4--ALK), I realized an issue with AnnotSV. It seems that AnnotSV cannot provide annotations for the genes and transcripts at the breakpoints; it can only annotate the genes covered by the fusion event. Here's an example of an inversion :
AnnotSV version: v3.3.6
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	LT	LN
chr2	29446989	18_1	N	N]chr2:42483159]	32279.63	.	SVTYPE=BND;STRANDS=++:1435;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;MATEID=18_2;EVENT=18;SU=1435;PE=653;SR=782	GT:SU:PE:SR:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	0/1:1435:653:782:200:32279.63:-3259,-31,-1146:3553:2120:1433:2119:1432:1476:781:0:643:651:0.4	0/0:0:0:0:200:0.00:-0,-246,-816:817:817:0:816:0:573:0:0:243:0:0
chr2	42483159	18_2	N	N]chr2:29446989]	32279.63	.	SVTYPE=BND;STRANDS=++:1435;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;MATEID=18_1;EVENT=18;SECONDARY;SU=1435;PE=653;SR=782	GT:SU:PE:SR:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	0/1:1435:653:782:200:32279.63:-3259,-31,-1146:3553:2120:1433:2119:1432:1476:781:0:643:651:0.4	0/0:0:0:0:200:0.00:-0,-246,-816:817:817:0:816:0:573:0:0:243:0:0
```
Gene_name column in both mode,  maybe I hope the last gene in order is EML4, not YPEL5?
```
ALK;ARHGEF33;ATL2;BIRC6;BIRC6-AS2;C2orf91;CAPN13;CAPN14;CDC42EP3;CDKL4;CEBPZ;CEBPZOS;CRIM1;CRIM1-DT;CYP1B1;CYP1B1-AS1;DHX57;DPY30;EHD3;EIF2AK2;EML4;EML4-AS1;FAM98A;FEZ2;GALM;GALNT14;GEMIN6;GPATCH11;HEATR5B;HNRNPLL;LBH;LCLAT1;LINC00211;LINC00486;LINC01317;LINC01318;LINC01320;LINC01883;LINC01913;LINC01914;LINC01936;LINC01946;LINC02613;LOC105374389;LOC375196;LTBP1;MAP4K3;MAP4K3-DT;MEMO1;MIR4430;MIR4765;MIR548AD;MIR558;MORN2;MYADML;NDUFAF7;NLRC4;PKDCC;PRKD3;QPCT;RASGRP3;RASGRP3-AS1;RMDN2;RMDN2-AS1;SLC30A6;SLC8A1;SLC8A1-AS1;SNORA10B;SOS1;SPAST;SRD5A2;SRSF7;STRN;SULT6B1;THUMPD2;TMEM178A;TTC27;VIT;XDH;YIPF4;YPEL5
```
Best,
xiucz

**Comment by lgmgeo** [comment]
> And more, I'm curious about the concept of sorting in alphabetical order. Previously, I believed that sorting was done based on coordinates.

Actually, the `Gene_name` feature is only used to report all overlapped genes, without any redundancy. No breakpoint information.
Because in my opinion, all the overlapped genes can be implied in a default of function (due to promoters, TAD... reorganisation).

Finally, to assess the functional impact of a gene, the user must examine the split lines (phenotype matched genes...).

cf README:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/04ed5bb1-4e09-4dcc-afce-894c9970df96)

**Comment by lgmgeo** [comment]
> Is it possible to add a parameter that allows gene names to be sorted in coordinate order in both the full mode and split mode? Alternatively, could coordinate sorting be the default mode? This would provide a clearer sense of direction in the results to enhance breakpoints' annotations.

Ok:
- Coordinate sorting could become the default order for the full lines (but not in a near future, sorry, I'm running out of time). 
- When a SV spans over several genes, the split lines are sorted from most to least pathogenic. I prefer to keep this pathogenic sorting.

**Comment by lgmgeo** [comment]
Code has been added in the dev branch regarding your request.
Gene names are now sorted by genomic coordinates and no longer sorted alphabetically ("Gene_name" feature).
This will soon be distributed with the next release (I will notify you here)

**Comment by lgmgeo** [comment]
AnnotSV 3.4 is posted.
Let me know if everything works well on your side.
