### ISSUE TITLE
Exomiser 2309 already released - update is planned?

### ISSUE THREAD

**Issue by Stikus** [lgmgeo/AnnotSV#204]
Hello, thx again for great tool.

There are 3 releases of Exomiser [data](https://data.monarchinitiative.org/exomiser/data) since your last from here https://www.lbgi.fr/~geoffroy/Annotations/ - 2209, 2302 and 2309.

Should we expect an update any time soon?

**Comment by Stikus** [comment]
And one more question - 3.3.7 data is missing:
![image](https://github.com/lgmgeo/AnnotSV/assets/41360525/e127e535-6c79-4317-92fb-73d6f3e18d79)

https://github.com/lgmgeo/AnnotSV/blob/master/changeLog.txt - doesn't contain 3.3.7 info.

What release should we use - 3.3.6 or 3.3.7?

**Comment by mneveu-mx** [comment]
Hello,
Can you explain us how you generate 2309_hg19.tar.gz file ?
It is not the same sizes than the files we found on : https://data.monarchinitiative.org/exomiser/data/
Can we generate us the 2309_hg19.tar.gz file and send to you ?

**Comment by lgmgeo** [comment]
Hi @mneveu-mx,

Everything is detailed in the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf):
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/1f54c2c0-5e69-4da4-bfc1-3c1806d96f07)

Actually I can't update annotation sources one by one. It would take too long. I update all sources at once.

**Comment by lgmgeo** [comment]
> Why there is no 2309_hg38.tar.gz file on https://www.lbgi.fr/~geoffroy/Annotations/ ?

cf https://github.com/lgmgeo/AnnotSV/issues/12
The Exomiser analyses are independent of the genome build. The Exomiser module only uses the name of the genes (and not the position of the genes).

**Comment by lgmgeo** [comment]
AnnotSV 3.4 is posted, Exomiser has been updated to version 2309.
