### ISSUE TITLE
About CNV calling result from WES method

### ISSUE THREAD

**Issue by GaianX39** [lgmgeo/AnnotSV#206]
Hi there

I want to know whether there are differences on input CNV calling result comes from WES or WGS method, thank you!

Best
Gaian

**Comment by lgmgeo** [comment]
Hi,

AnnotSV is dedicated to annotation and ranking of CNV. No matter if it comes from WES or WGS data.

Of course, the calling of your CNVs will be more or less precise at the BND level depending on the calling methods (read depth, split reads, etc.) and the data type (WGS, WES, SNP array) but this is done before using AnnotSV.

Best,

Véronique
