### ISSUE TITLE
Error running AnnotSV in conda environment: can't read "hpoVersion": no such variable

### ISSUE THREAD

**Issue by handoko12u** [lgmgeo/AnnotSV#207]
fail to run AnnotSV in conda environment with error:

(annotsv) sysadmin@sysadmin:~/Downloads/R_practice$ AnnotSV -SVinputFile s1_sv.vcf
AnnotSV 3.3.6

Copyright (C) 2017-2023 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.6

Application name used:
/home/sysadmin/mambaforge/envs/annotsv

...downloading the configuration data (January 11 2024 - 10:08)
	...configuration data by default
	...configuration data from /home/sysadmin/mambaforge/envs/annotsv/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

...VCF to BED (January 11 2024 - 10:08)

...checking the annotation data sources (January 11 2024 - 10:08)
can't read "hpoVersion": no such variable
    while executing
"file exist $g_AnnotSV(annotationsDir)/Annotations_Exomiser/$hpoVersion/application.properties"
    (procedure "checkExomiserInstallation" line 18)
    invoked from within
"checkExomiserInstallation"
    (file "/home/sysadmin/mambaforge/envs/annotsv/bin/AnnotSV" line 180)

Initially I though exomiser has not been installed, then I also install: conda install bioconda::exomiser-rest-prioritiser, but still fail.

please advice, what's wrong?

**Comment by lgmgeo** [comment]
Hi @handoko12u,

Thank you for this bug report.
I just added a fix (v3.3.9).
Can you confirm that everything is back to normal?

Best,

Véronique

**Comment by handoko12u** [comment]
Hello @lgmgeo 
Here is the result:

(annotsv) sysadmin@sysadmin:~/Downloads/R_practice$ AnnotSV -SVinputFile s1_sv.vcf -genomeBuild GRCh38
AnnotSV 3.3.9

Copyright (C) 2017-2024 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.6

Application name used:
/home/sysadmin/mambaforge/envs/annotsv


...downloading the configuration data (January 16 2024 - 13:00)
	...configuration data by default
	...configuration data from /home/sysadmin/mambaforge/envs/annotsv/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

...VCF to BED (January 16 2024 - 13:00)


...checking the annotation data sources (January 16 2024 - 13:00)

WARNING: No Exomiser annotations available in /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Exomiser/

	   >>> creation of /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh37/overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tsv] (January 16 2024 - 13:00)
-- checkOverlappedGenesBenignFiles, GRCh37, RefSeq, Loss --
bedtools intersect -sorted -a  -b  -wa -wb > 20240116_AnnotSV/1705384826_overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tmp.bed
Error: Unable to open file . Exiting.
Exit with error

Still doesn't work.

**Comment by lgmgeo** [comment]
Sorry I can't reproduce the bug. 
Quite difficult to help you.

Does the following file exist in your installation:
/home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh37/overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tsv

**Comment by lgmgeo** [comment]
Here is the command you used to run AnnotSV:
> (annotsv) sysadmin@sysadmin:~/Downloads/R_practice$ AnnotSV -SVinputFile s1_sv.vcf -genomeBuild GRCh38

Can you run AnnotSV by using the "bin" path?
Something like:
```/home/sysadmin/mambaforge/envs/annotsv/bin/AnnotSV -SVinputFile s1_sv.vcf -genomeBuild GRCh38```

**Comment by handoko12u** [comment]
Hello @lgmgeo 

This is my current directory: /home/sysadmin/Downloads/R_practice

I have also run using bin path:

(annotsv) sysadmin@sysadmin:~/Downloads/R_practice$ /home/sysadmin/mambaforge/envs/annotsv/bin/AnnotSV -SVinputFile s1_sv.vcf -genomeBuild GRCh38
AnnotSV 3.3.9

Copyright (C) 2017-2024 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.6

Application name used:
/home/sysadmin/mambaforge/envs/annotsv


...downloading the configuration data (January 18 2024 - 08:14)
	...configuration data by default
	...configuration data from /home/sysadmin/mambaforge/envs/annotsv/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

...VCF to BED (January 18 2024 - 08:14)


...checking the annotation data sources (January 18 2024 - 08:14)

WARNING: No Exomiser annotations available in /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Exomiser/

	   >>> creation of /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh37/overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tsv] (January 18 2024 - 08:14)
-- checkOverlappedGenesBenignFiles, GRCh37, RefSeq, Loss --
bedtools intersect -sorted -a  -b  -wa -wb > 20240118_AnnotSV/1705540478_overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tmp.bed
Error: Unable to open file . Exiting.
Exit with error
(annotsv) sysadmin@sysadmin:~/Downloads/R_practice$ pwd
/home/sysadmin/Downloads/R_practice

I checked there is no overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tsv created. Is it supposed to be created automatically?

**Comment by handoko12u** [comment]
This is my ls result:

(annotsv) sysadmin@sysadmin:~/Downloads/R_practice$ ls /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/*/*
/home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Gene-based/NCBIgeneID:
geneSymbol_NCBIgeneID.txt  results.txt

/home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Genes/GRCh38:
genes.RefSeq.sorted.bed

**Comment by lgmgeo** [comment]
The bug can be visualize in your output with this command:
```
bedtools intersect -sorted -a -b -wa -wb
```
This should be:
```
bedtools intersect -sorted -a /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Genes/GRCh37/genes.RefSeq.sorted.bed -b /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh37/benign_Loss_SV_GRCh37.sorted.bed -wa -wb
```

Can you please:
- download and uncompress the attached file
[AnnotSV-benignsv.tcl.gz](https://github.com/lgmgeo/AnnotSV/files/13974347/AnnotSV-benignsv.tcl.gz)
- save then replace this file in your install:
`/home/sysadmin/mambaforge/envs/annotsv/share/tcl/AnnotSV/AnnotSV-benignsv.tcl`
- run AnnotSV
- give me the output

**Comment by handoko12u** [comment]
Hello @lgmgeo 

This is my first time running AnnotSV

I have done as your instruction. This is the result:
(annotsv) sysadmin@sysadmin:~/Downloads/R_practice$ /home/sysadmin/mambaforge/envs/annotsv/bin/AnnotSV -SVinputFile s1_sv.vcf -genomeBuild GRCh38
AnnotSV 3.3.9

Copyright (C) 2017-2024 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.6

Application name used:
/home/sysadmin/mambaforge/envs/annotsv


...downloading the configuration data (January 19 2024 - 14:19)
	...configuration data by default
	...configuration data from /home/sysadmin/mambaforge/envs/annotsv/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

...VCF to BED (January 19 2024 - 14:19)


...checking the annotation data sources (January 19 2024 - 14:19)

WARNING: No Exomiser annotations available in /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Exomiser/

--- g_AnnotSV(annotationsDir) : /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV
    g_AnnotSV(organism)       : Human
    genomeBuild               : GRCh37
    benignDir                 : /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh37
    genesDir                  : /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Genes/GRCh37
    --- tx : RefSeq

        GenesfileFormatted :
           >> $genesDir/genes.${tx}.sorted.bed 
           >> /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Genes/GRCh37/genes.RefSeq.sorted.bed
           >>  ($GenesfileFormatted)
ls: cannot access '/home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Genes/GRCh37/genes.RefSeq.sorted.bed': No such file or directory
    while executing
"exec ls /home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Genes/GRCh37/genes.RefSeq.sorted.bed"
    ("eval" body line 1)
    invoked from within
"eval exec ls $genesDir/genes.${tx}.sorted.bed"
    (procedure "checkOverlappedGenesBenignFiles" line 23)
    invoked from within
"checkOverlappedGenesBenignFiles"
    (file "/home/sysadmin/mambaforge/envs/annotsv/bin/AnnotSV" line 188)

![image](https://github.com/lgmgeo/AnnotSV/assets/153805498/e2f47fbe-4b06-4d75-be0f-a3037307961f)

**Comment by lgmgeo** [comment]
I don't know why, but your annotation directory is not correct.
This following file is distributed with AnnotSV and should exist:
/home/sysadmin/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Genes/GRCh37/genes.RefSeq.sorted.bed
(even if you run AnnotSV with `-genomeBuild GRCh38`)

This does not seem to be the case.

Can you try another AnnotSV install from scratch:

To install AnnotSV, please follow these instructions:
https://github.com/lgmgeo/AnnotSV/blob/master/docs/quickstart.md
The following step is mandatory: 
```
make PREFIX=. install-human-annotation
```

**Comment by lgmgeo** [comment]
Any news?

**Comment by handoko12u** [comment]
Hello @lgmgeo 

I have removed the whole thing and install again.

![image](https://github.com/lgmgeo/AnnotSV/assets/153805498/f1acb000-016c-4be0-97c3-d8ad596cd1a1)
stil does not work. The annotations files are supposed to be downloaded automatically (when we install AnnotSV), is that right? why it doesn't seem to be the case for me.

Thanks

**Comment by lgmgeo** [comment]
The annotations files are supposed to be downloaded automatically when running:
```
make PREFIX=. install-human-annotation
```

Can you give me the output of this command?

**Comment by handoko12u** [comment]
Here is the result:

(annotsv) sysadmin@sysadmin:~/Downloads/R_practice/sv_vcf$ make PREFIX=. install-human-annotation
make: *** No rule to make target 'install-human-annotation'.  Stop.

**Comment by lgmgeo** [comment]
OK, at least we know why you don't have annotation files... The install is not done correctly...

Please run the following instructions:
```
cd ~/Downloads/R_practice/sv_vcf
git clone https://github.com/lgmgeo/AnnotSV.git
cd ~/Downloads/R_practice/sv_vcf/AnnotSV
make PREFIX=. install
make PREFIX=. install-human-annotation
```
And paste me the outputs of each step if it does not work (but it should work).

**Comment by handoko12u** [comment]
Installation looks successful:
![image](https://github.com/lgmgeo/AnnotSV/assets/153805498/f83281c9-f278-48f7-92a4-b2559a111b10)

But when I run again:
![image](https://github.com/lgmgeo/AnnotSV/assets/153805498/f311ad5f-54b8-404e-9fc9-578bd6de0774)

the annotation downloaded is this:
![image](https://github.com/lgmgeo/AnnotSV/assets/153805498/76575e7c-1428-4278-8040-da642bc908c3)

please advice, some adjustment is needed, but I don't know how!
Thanks

**Comment by lgmgeo** [comment]
I'm a little lost, I've never had feedback like this and I can't reproduce the bug...


- Can you try not to run AnnotSV from the AnnotSV bin directory? Or to redirect the output elsewhere than in the AnnotSV install (`-outputFile /home/sysadmin/Downloads/R_practice/sv_vcf/s1_phased.annotated.tsv`).

(This is something that is not done, the installation must remain clean)

But this will not explain your bug.


- Your output is quite strange:

The AnnotSV path install is:
/home/sysadmin/Downloads/R_practice/sv_vcf/AnnotSV

But then, AnnotSV search for annotation in:
/home/sysadmin/mambaforge/envs/annotsv/

That's not normal.

What is the result when printing the ANNOTSV env variable?
```
echo $ANNOTSV
```

**Comment by handoko12u** [comment]
this is the result:
![image](https://github.com/lgmgeo/AnnotSV/assets/153805498/2f9678e3-8726-4900-8707-95c444adc67a)

**Comment by lgmgeo** [comment]
The ANNOTSV environment variable must be set:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/483f18b2-c3cb-4227-b3cb-30b4e79812dc)

**Comment by handoko12u** [comment]
Have done it correctly? but it is still the same
![image](https://github.com/lgmgeo/AnnotSV/assets/153805498/39fc9562-03e5-4d91-bd9d-ee1578f1e130)
![image](https://github.com/lgmgeo/AnnotSV/assets/153805498/a3276940-8a59-475e-b034-3712c08d5341)

**Comment by lgmgeo** [comment]
Can you add the `export ANNOTSV=/home/sysadmin/Downloads/R_practice/sv_vcf/AnnotSV` command in your ~/.bashrc file?
Then : 
```
cd /home/sysadmin/Downloads/R_practice/sv_vcf/
echo $SHELL
source ~/.bashrc
echo $ANNOTSV
$ANNOTSV/bin/AnnotSV -SVinputFile /home/sysadmin/Downloads/R_practice/sv_vcf/s1_phased.vcf -outputFile /home/sysadmin/Downloads/R_practice/sv_vcf/s1_phased.annotated.tsv
```

**Comment by handoko12u** [comment]
Thank you very much @lgmgeo . It works now.

**Comment by lgmgeo** [comment]
Great! 
Have fun with AnnotSV!
