### ISSUE TITLE
Bed 0 based incompatible with dragen cnv output

### ISSUE THREAD

**Issue by LiviaMoura** [lgmgeo/AnnotSV#208]
Hello, 

At v3.3, AnnotSV implemented a fix related to the VCF input base. 
```
- Add bugfix concerning genomic start coordinates:
          TSV and VCF output files are now both 1-based, with inclusive-end (whatever the input file format)
```
However, the Illumina Dragen CNV output, despite the documentation saying it is 1-based (https://support-docs.illumina.com/SW/DRAGEN_v310/Content/SW/DRAGEN/CNVVCFFile.htm), is a 0-based VCF.
In the process of AnnotSV creating a bed, it ends up transforming positions `0` into `-1`, like the variant example below:

`chrM 0 DRAGEN:GAIN:chrM:1-7000 N <DUP> 12 cnvQual SVLEN=7000;SVTYPE=CNV;END=7000;REFLEN=7000`

This causes bedtools to not recognize the bed, and AnnotSV crashes with an error. The bed line is below:

`M       -1      16569   DUP     SAMPLE_NAME  DRAGEN:GAIN:chrM:1-7000        N       <DUP>    ETC`

Is there the possibility of adding a parameter to indicate whether the input is 0-based or 1-based? This would avoid problems with this type of input

**Comment by lgmgeo** [comment]
Hi,

Thank you for your report and explanations.
Definitely, AnnotSV will not handle file format errors given as input. 
I already can't handle all the developments I would like to code in AnnotSV. I'm chasing time

The best would be to ask a fix to  the Illumina Dragen CNV developpers.

Sorry for not being of more help,

Véronique

**Comment by LiviaMoura** [comment]
Thank you Véronique

**Comment by LiviaMoura** [comment]
Thank you Véronique, We`ll try talking with Illumina.

**Comment by LiviaMoura** [comment]
Véronique, I had to reopen this issue, just to inform that AnnotSV is changing the ID from the original VCF.
Ex:
`original VCF`
```
chr2    50053260        DRAGEN:GAIN:chr2:50053261-50091504 
```

`AnnotSV change`
```
2_50053260_50091504_DUP_1       2       50053260        50091504        38244   DUP    SAMPLE_NAME  DRAGEN:GAIN:chr2:50053262-50091504
```

Note that the ID was increased  by AnnotSV, losing track from the original VCF. I think this is might be a bug

**Comment by lgmgeo** [comment]
cf https://github.com/lgmgeo/AnnotSV/issues/181

**Comment by LiviaMoura** [comment]
ok.. I see.. 
I personally think that the VCF ID shouldn't be modified by any means, but I understand why you did that. I'll treat the data after AnnotSV. 
Thank you again.
