### ISSUE TITLE
Cytoband issue

### ISSUE THREAD

**Issue by BoudSTER** [lgmgeo/AnnotSV#210]
Hi,

First of all, thank you so much for developing this fantastic algorithm. :)

I believe I've encountered an issue related to Cytoband annotations.

Specifically, while analyzing CNVs for a sample with a gain on
chr19:243927-36911072 (refer to the attached plot), the TSV annotation (in
attachment) from AnnotSV provided the following result for the first 16 columns:
q13.12-p11. However, according to my plot, the gain appears to start at the
beginning of chr19, which seems inconsistent with AnnotSV's annotation.

To verify, I checked the genomic position on UCSC Genome Browser (refer to the
attached picture), and the findings were consistent with my graph and not with
the AnnotSV output.

The most surprising thing is that in the TSV p11 never appears as a split! 

Could you please help clarify this discrepancy?

Thank you in advance for your assistance.

Best regards, 

BoudSTER
[19.txt](https://github.com/lgmgeo/AnnotSV/files/14182727/19.txt)
![Screenshot 2024-02-06 at 15 51 50](https://github.com/lgmgeo/AnnotSV/assets/60364831/cd4d9b04-f095-4b0f-a2be-1d1c81a05b0a)
![Screenshot 2024-02-06 at 15 54 27](https://github.com/lgmgeo/AnnotSV/assets/60364831/25fec039-617a-4b90-a649-dafde8a99d10)
AnnotSV:3.3.6

**Comment by BoudSTER** [comment]
[19.txt](https://github.com/lgmgeo/AnnotSV/files/14182719/19.txt)

**Comment by lgmgeo** [comment]
Hi @BoudSTER ,

Thank you very much for your report. Indeed, I had a stupid glitch in the AnnotSV code.
I fixed this in the development branch.
This will soon be distributed with the next annotation release.
I will notify you here as soon as the release is published.

Best,

Véronique

**Comment by BoudSTER** [comment]
Hi Véronique,

Thank you a lot for your reply :) !
It was kind of you to let me know about the new version.

Have a nice day,

BoudSTER

**Comment by lgmgeo** [comment]
AnnotSV 3.4 is posted.
Let me know if everything works well on your side.

**Comment by BoudSTER** [comment]
Hi Véronique,

Sorry for the delay ! 
It's look perfect ! 
AnnotSV old  q13.12-p11
AnnotSV 3.4 p13.3-q13.12 (UCSC check OK)

A big thank you ! =)

BoudSTER
