### ISSUE TITLE
tclversion issue

### ISSUE THREAD

**Issue by gevro** [lgmgeo/AnnotSV#211]
Hi,
AnnotSV stopped working. It was installed into tcl8.5, but for some reason when I run it now, it is looking for a 'tcl' directory instead of 'tcl8.5'.

Somehow the tclVersion is getting set to tcl instead of tcl8.5 when annotSV runs. But I did not change anything in the installation.

set tclVersion [info tclversion]
set g_AnnotSV(tclDir)     "$g_AnnotSV(installDir)/share/tcl${tclVersion}/AnnotSV"
puts "Tcl/Tk version: $tclVersion"
set tclVersion [split $tclVersion "."]
if {[lindex $tclVersion 0] < 8 || ([lindex $tclVersion 0] eq 8 && [lindex $tclVersion 1] < 5)} {

Is there an environment variable that maybe changed on my computing cluster that could affect this?
Thanks

**Comment by gevro** [comment]
I think perhaps my computing cluster changed the tclsh version. If so, is it ok to simply rename 
AnnotSV/share/tcl8.5 to AnnotSV/share/tcl ? Or would that break the installation?

**Comment by lgmgeo** [comment]
Hi, you found the good explanation.

For example on my server:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/5e12edc8-4607-4398-a379-41f278012cc3)
=> AnnotSV accepts `tcl` or `tcl8.6`

**Comment by lgmgeo** [comment]
> I think perhaps my computing cluster changed the tclsh version. If so, is it ok to simply rename
AnnotSV/share/tcl8.5 to AnnotSV/share/tcl ?

Absolutely, it's the best thing to do
