### ISSUE TITLE
How to use the bioconda version of AnnotSV

### ISSUE THREAD

**Issue by fanavarro** [lgmgeo/AnnotSV#214]
Hi, I am trying to use the bioconda version of AnnotSV but I cannot make it work. I have a yaml file to install the environment as follows:

```
name: annotsv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - annotsv=3.3.9
```

I installed the environment with:

`mamba env create -f environment.yml`

Then, I tried to run the application with a vcf test file as input with:

`AnnotSV -SVinputFile test.vcf`

And I got the following output:

```
AnnotSV 3.3.9

Copyright (C) 2017-2024 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.6

Application name used:
/home/fabad/mambaforge/envs/annotsv


...downloading the configuration data (February 28 2024 - 12:27)
	...configuration data by default
	...configuration data from /home/fabad/mambaforge/envs/annotsv/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

...VCF to BED (February 28 2024 - 12:27)
	...WARNING: 11 sample IDs with missing alleles in the GT field (./. or .|.) have been reported in the "Samples_ID" output field

...checking the annotation data sources (February 28 2024 - 12:27)
############################################################################
"/home/fabad/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Genes/GRCh38/refGene.txt.gz" file doesn't exist
Please check your install - Exit with error.
############################################################################
```
I think the missing file is generated by using `make PREFIX=. install-human-annotation` during the standard installation of the tool. I am wondering how to do this in the conda installation. The folder `/home/fabad/mambaforge/envs/annotsv/share/AnnotSV/`, which is the folder where the application looks for the files, does not exist. I tried to create the complete folder path to include the refGene.txt.gz file manually, but then I have another error:

```
AnnotSV 3.3.9

Copyright (C) 2017-2024 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.6

Application name used:
/home/fabad/mambaforge/envs/annotsv


...downloading the configuration data (February 28 2024 - 12:34)
	...configuration data by default
	...configuration data from /home/fabad/mambaforge/envs/annotsv/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

...VCF to BED (February 28 2024 - 12:34)
	...WARNING: 11 sample IDs with missing alleles in the GT field (./. or .|.) have been reported in the "Samples_ID" output field

...checking the annotation data sources (February 28 2024 - 12:34)
	...creation of /home/fabad/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Genes/GRCh38/genes.RefSeq.sorted.bed (February 28 2024 - 12:34)
	   (done only once during the first annotation)

WARNING: No Exomiser annotations available.
.../home/fabad/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/Gene-based/NCBIgeneID/results.txt doesn't exist

WARNING: No Exomiser annotations available in /home/fabad/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Exomiser/

	   >>> creation of /home/fabad/mambaforge/envs/annotsv/share/AnnotSV/Annotations_Human/SVincludedInFt/BenignSV/GRCh37/overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tsv] (February 28 2024 - 12:34)
-- checkOverlappedGenesBenignFiles, GRCh37, RefSeq, Loss --
bedtools intersect -sorted -a  -b  -wa -wb > 20240228_AnnotSV/1709120074_overlappedGenes_RefSeq_in_benign_Loss_SV_GRCh37.tmp.bed
Error: Unable to open file . Exiting.
Exit with error
```

So I think the conda version of the tool is not ready to use after installing the environment. What are the steps to follow after the creation of the environment?

Kind regards,
Francisco Abad.

**Comment by lgmgeo** [comment]
Perhaps can you try to use the "-annotationsDir" option?

Else, @nvnieuwk, may you be able to help this user?

**Comment by nvnieuwk** [comment]
Using AnnotSV in bioconda requires a little bit of setup:
1. Run the following command: `INSTALL_annotations.sh`. this creates a directory called `AnnotSV_annotations` in the current working directory. This directory contains all annotations needed to run AnnotSV (this could not be included in the recipe due to the size of this folder)
2. Run Annotsv using the following command: `AnnotSV -annotationsDir AnnotSV_annotations ...` (where `...` stands for your other parameters)

**Comment by fanavarro** [comment]
Thanks for your answers, I miss the INSTALL_annotations.sh script; now its working. Thanks!
