### ISSUE TITLE
AnnotSV structural variant chromosome start/stop position does not match VCF file position

### ISSUE THREAD

**Issue by mxiong2** [lgmgeo/AnnotSV#217]
Hello,

Is there an explanation why AnnotSV is annotating the start and end position of SV slightly off. I checked the position of the annotated SV against the position in my VCF file but saw that the SV were off. I am annotating the data with the annotation split mode. 

Thanks.

**Comment by lgmgeo** [comment]
Hi,

By default, the `includeCI` option is set to "1":
```
-includeCI: To expand the "start" and "end" SV positions with the VCF confidence intervals (CIPOS, CIEND) around the breakpoints
            Values: 1 (default) or 0
```

To keep the start and end positions, please set the `includeCI` option to "0".

Best,
Véronique

**Comment by lgmgeo** [comment]
Any news?
