### ISSUE TITLE
PhenoGenius issue

### ISSUE THREAD

**Issue by lgmgeo** [lgmgeo/AnnotSV#218]
Issue reported by @abrusell
cf https://github.com/lgmgeo/AnnotSV/issues/216
___
I've correctly installed PhenoGenius in the $AnnotSV_3.4/share/python3/phenogenius directory, but I get this error:

```
...running PhenoGenius for 4524 gene names (March 01 2024 - 15:37)

child process exited abnormally
```

**Comment by lgmgeo** [comment]
1- Can you share your `$ANNOTSV/share/python3/phenogenius/PhenoGenius.install.log` file?

2- Can you share your `$ANNOTSV/share/python3/phenogenius/poetry_install.log` file?

2- Is this the same user installing and running AnnotSV?
If not, can you try changing the permissions in the PhenoGenius installation?
chmod -R 777 $ANNOTSV/share/python3/phenogenius/

3- Another question, have you run AnnotSV with bioconda?
Same feelings regarding permissions in the "conda_env_share" you are using

**Comment by abrusell** [comment]
1- Even though phenogenius seems to have been installed whithout errors, I haven't got a PhenoGenius.install.log... I don't know why!
2- I have 2 poetry_install.log: one in the $ANNOTSV/share/python3/phenogenius/ directory :
  `Updating dependencies
   Resolving dependencies...
   Writing lock file
   No dependencies to install or update
   Installing the current project: PhenoGenius_app (0.1.0)`

and one in $ANNOTSV/share/ directory:
  `Poetry could not find a pyproject.toml file in $ANNOTSV/share/python3 or its parents`
This one seems to have encountered some problems... 

3- YES
4- YES
5- NO, I've installed it from source

Thank you

**Comment by lgmgeo** [comment]
Can you run the following commands and show me each result:
```
bash
cd $ANNOTSV/share/python3/phenogenius/PhenoGenius
poetry --version 
python --version
python3 --version
poetry install
poetry run python3 phenogenius_cli.py --help
poetry run python3 phenogenius_cli.py --hpo_list HP:0000107,HP:0000108,HP:0001407,HP:0005562 --result_file PKD1.tsv
```

**Comment by abrusell** [comment]
$ cd $ANNOTSV/share/python3/phenogenius/PhenoGenius
$ poetry --version
`Poetry (version 1.2.2)`
$ python --version
`Python 3.9.15`
$ python3 --version
`Python 3.9.15`
$ poetry install
```
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: PhenoGenius_app (0.1.0)
```
 $ poetry run python3 phenogenius_cli.py --help
```
Usage: phenogenius_cli.py [OPTIONS]

Options:
  --version           Show the version and exit.
  --result_file TEXT  Output file name, default = match.tsv
  --hpo_list TEXT     (Mandatory) List of HPO terms to match, separated with
                      commas
  --gene_list TEXT    (Optional) List of genes in NCBI ID format to match,
                      separated with commas
  --help              Show this message and exit.
```
$ poetry run python3 phenogenius_cli.py --hpo_list HP:0000107,HP:0000108,HP:0001407,HP:0005562 --result_file PKD1.tsv
```
Traceback (most recent call last):
  File "phenogenius_cli.py", line 245, in <module>
    evaluate_matching()
  File "/g100/home/userexternal/abrusell/.cache/pypoetry/virtualenvs/phenogenius-app-3ZtR_Fj0-py3.8/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/g100/home/userexternal/abrusell/.cache/pypoetry/virtualenvs/phenogenius-app-3ZtR_Fj0-py3.8/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/g100/home/userexternal/abrusell/.cache/pypoetry/virtualenvs/phenogenius-app-3ZtR_Fj0-py3.8/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g100/home/userexternal/abrusell/.cache/pypoetry/virtualenvs/phenogenius-app-3ZtR_Fj0-py3.8/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "phenogenius_cli.py", line 141, in evaluate_matching
    ncbi, symbol = symbol_to_id_to_dict()
  File "phenogenius_cli.py", line 38, in symbol_to_id_to_dict
    ncbi_df = pd.read_csv("data/resources/Homo_sapiens.gene_info.gz", sep="\t")
  File "/g100/home/userexternal/abrusell/.cache/pypoetry/virtualenvs/phenogenius-app-3ZtR_Fj0-py3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/g100/home/userexternal/abrusell/.cache/pypoetry/virtualenvs/phenogenius-app-3ZtR_Fj0-py3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/g100/home/userexternal/abrusell/.cache/pypoetry/virtualenvs/phenogenius-app-3ZtR_Fj0-py3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/g100/home/userexternal/abrusell/.cache/pypoetry/virtualenvs/phenogenius-app-3ZtR_Fj0-py3.8/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/g100/home/userexternal/abrusell/.cache/pypoetry/virtualenvs/phenogenius-app-3ZtR_Fj0-py3.8/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 550, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 639, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2021, in pandas._libs.parsers.raise_parser_error
  File "/g100_work/PROJECTS/spack/v0.17/prod/0.17.1/install/0.17/linux-centos8-cascadelake/intel-2021.4.0/python-3.8.12-tvg3jcaazvbwlpwrdeiyin4rjulbae26/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/g100_work/PROJECTS/spack/v0.17/prod/0.17.1/install/0.17/linux-centos8-cascadelake/intel-2021.4.0/python-3.8.12-tvg3jcaazvbwlpwrdeiyin4rjulbae26/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/g100_work/PROJECTS/spack/v0.17/prod/0.17.1/install/0.17/linux-centos8-cascadelake/intel-2021.4.0/python-3.8.12-tvg3jcaazvbwlpwrdeiyin4rjulbae26/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')
```

**Comment by lgmgeo** [comment]
Can you try the same command with python == 3.8?

Else, @kyauy, can you help us please?

**Comment by abrusell** [comment]
Same output with python-3.8.12

**Comment by lgmgeo** [comment]
Ok, waiting for help from the PhenoGenius developper (@kyauy)

**Comment by kyauy** [comment]
Hi @abrusell and @lgmgeo !

It seems that this file is corrupted in your clone repository ("data/resources/Homo_sapiens.gene_info.gz" -> gzip.BadGzipFile: Not a gzipped file (b've')). 

Errors may have happen during the download, can you reinstall ? (https://github.com/kyauy/PhenoGenius.git) or replace the corresponding file (https://github.com/kyauy/PhenoGenius/blob/main/data/resources/Homo_sapiens.gene_info.gz) ?

**Comment by abrusell** [comment]
Finally got it working!
I had to manually re-download every file in PhenoGenius/data/resources

Thank you @kyauy and @lgmgeo !
Best

**Comment by lgmgeo** [comment]
Do you have git-lfs installed?
```
which git-lfs
```
Because the resource files in the PhenoGenius GitHub are hosted via [git-lfs]( https://github.com/git-lfs/git-lfs)

**Comment by abrusell** [comment]
No,
I didn't have it...

Thank you
Alessandro

**Comment by lgmgeo** [comment]
Thanks for the feed-back, I will update the README.

Have fun with PhenoGenius and AnnotSV!

**Comment by jammywwh** [comment]
> Hi @abrusell and @lgmgeo !
> 
> It seems that this file is corrupted in your clone repository ("data/resources/Homo_sapiens.gene_info.gz" -> gzip.BadGzipFile: Not a gzipped file (b've')).
> 
> Errors may have happen during the download, can you reinstall ? (https://github.com/kyauy/PhenoGenius.git) or replace the corresponding file (https://github.com/kyauy/PhenoGenius/blob/main/data/resources/Homo_sapiens.gene_info.gz) ?

Hi @kyauy,
I got same issue. I use "git clone https://github.com/kyauy/PhenoGenius.git", but files are empty in data/ directory.
Only "wget https://github.com/kyauy/PhenoGenius/blob/main/data/resources/Homo_sapiens.gene_info.gz" is work.
How can i get all correct files once.
Thanks, looking forward to your reply!

**Comment by lgmgeo** [comment]
Do you have git-lfs installed?

**Comment by jammywwh** [comment]
> Do you have git-lfs installed?

I installed it with conda and confirmed that git-lfs (3.5.1) was installed successfully.

**Comment by kyauy** [comment]
> > Do you have git-lfs installed?
> 
> 
> 
> I installed it with conda and confirmed that git-lfs (3.5.1) was installed successfully.

Hi!

Not sure that git-lfs installed by conda makes it.

https://github.com/conda/conda-build/issues/1462

Could you try to install it directly ?

Thanks,
Kevin

**Comment by jammywwh** [comment]
> > > Do you have git-lfs installed?
> > 
> > 
> > I installed it with conda and confirmed that git-lfs (3.5.1) was installed successfully.
> 
> Hi!
> 
> Not sure that git-lfs installed by conda makes it.
> 
> [conda/conda-build#1462](https://github.com/conda/conda-build/issues/1462)
> 
> Could you try to install it directly ?
> 
> Thanks, Kevin

According https://github.com/git-lfs/git-lfs/wiki/Installation described "On all operating systems, once git-lfs is downloaded, git lfs install must be run. ", I execute
```
git lfs install
git clone https://github.com/kyauy/PhenoGenius.git
```
It works!
Thank you.

**Comment by jammywwh** [comment]
Hi, @kyauy @lgmgeo 
I got a new issue, when I execute
`$ANNOTSV/bin/AnnotSV -SVinputFile ./input/PKD1.bed -outputFile "./output/PKD1.annotated.tsv" -svtbedcol 4 -genomeBuild GRCh38 -hpo "HP:0000107,HP:0000108,HP:0001407,HP:0005562"`
It will re-download PhenoGenius, PhenoGenius.install.log, and poetry_install.log under the current path, then output

> WARNING: No PhenoGenius installation available for the phenotype-driven analysis.
> cf $ANNOTSV/share/python3/phenogenius/*.log

PhenoGenius.install.log

> Cloning into 'PhenoGenius'...
> Note: switching to 'fd7e63c7192c968a054cf0c0f0e7f6421326e7ce'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> Filtering content: 100% (22/22), 160.66 MiB | 2.96 MiB/s, done.

poetry_install.log

> Updating dependencies
> Resolving dependencies...
> 
> No dependencies to install or update
> 
> Writing lock file
> 
> Installing the current project: PhenoGenius_app (0.1.0)


What's this about, what am I doing wrong?
Thanks, looking forward to your reply!

**Comment by lgmgeo** [comment]
Hi,

When HPO terms are given as input, AnnotSV checks if the PhenoGenius installation is correct.
=> To do this, AnnotSV executes the file $ANNOTSV/share/bash/AnnotSV/checkPhenoGeniusInstall.sh
=> The results are in $ANNOTSV/share/python3/phenogenius/*.log

The result of `git clone https://github.com/kyauy/PhenoGenius --branch v1.0.0` is strange:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/07e00a7d-f12c-4634-9d8c-0fb21b794a3b)
=> The problem seems to be with your `git clone` command.

Ok, can you run the following commands:
```
echo $ANNOTSV
cd $ANNOTSV/share/python3/phenogenius
chmod -R 777 PhenoGenius* poetry_install.log
rm -r  PhenoGenius* poetry_install.log
$ANNOTSV/share/bash/AnnotSV/checkPhenoGeniusInstall.sh
```

**Comment by jammywwh** [comment]
Hi, @lgmgeo 
Thanks for your reply, I re-executed as you said, but this log file still shows the same message as before.
```
git clone https://github.com/lgmgeo/AnnotSV.git
cd ${ANNOTSV}
make PREFIX=. install
make PREFIX=. install-human-annotation
git lfs install
mkdir -p ${ANNOTSV}/share/python3/phenogenius ; cd ${ANNOTSV}/share/python3/phenogenius
${ANNOTSV}/share/bash/AnnotSV/checkPhenoGeniusInstall.sh
```

the ${ANNOTSV}/share/python3/phenogenius/PhenoGenius.install.log shows:

> Cloning into 'PhenoGenius'...
> Note: switching to 'fd7e63c7192c968a054cf0c0f0e7f6421326e7ce'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false

as before.

**Comment by jammywwh** [comment]
I'm sorry, I went ahead and tested it and it's working now. Thanks.
`$ANNOTSV/bin/AnnotSV -SVinputFile ./input/PKD1.bed -outputFile "./output/PKD1.annotated.tsv" -svtbedcol 4 -genomeBuild GRCh38 -hpo "HP:0000107,HP:0000108,HP:0001407,HP:0005562"`

> Hi, @lgmgeo Thanks for your reply, I re-executed as you said, but this log file still shows the same message as before.
> 
> ```
> git clone https://github.com/lgmgeo/AnnotSV.git
> cd ${ANNOTSV}
> make PREFIX=. install
> make PREFIX=. install-human-annotation
> git lfs install
> mkdir -p ${ANNOTSV}/share/python3/phenogenius ; cd ${ANNOTSV}/share/python3/phenogenius
> ${ANNOTSV}/share/bash/AnnotSV/checkPhenoGeniusInstall.sh
> ```
> 
> the ${ANNOTSV}/share/python3/phenogenius/PhenoGenius.install.log shows:
> 
> > Cloning into 'PhenoGenius'...
> > Note: switching to 'fd7e63c7192c968a054cf0c0f0e7f6421326e7ce'.
> > You are in 'detached HEAD' state. You can look around, make experimental
> > changes and commit them, and you can discard any commits you make in this
> > state without impacting any branches by switching back to a branch.
> > If you want to create a new branch to retain commits you create, you may
> > do so (now or later) by using -c with the switch command. Example:
> > git switch -c 
> > Or undo this operation with:
> > git switch -
> > Turn off this advice by setting config variable advice.detachedHead to false

**Comment by lgmgeo** [comment]
Great!

**Comment by lgmgeo** [comment]
**- Requirement before AnnotSV v3.4.5:** 
PhenoGenius is downloaded from https://github.com/kyauy/PhenoGenius. 
=> git-lfs is required to download PhenoGenius resources.

**- From AnnotSV v3.4.6 onward:** 
PhenoGenius is downloaded from https://github.com/kyauy/PhenoGeniusCli. 
=> No need to have git-lfs installed anymore.
