### ISSUE TITLE
Same region not annotated in split annotation mode

### ISSUE THREAD

**Issue by priyambial123** [lgmgeo/AnnotSV#219]
Hello,

I am working with AnnotSV version 3.3.4. When I used the 'full' annotation mode, I could find annotation for the below region:

```
/AnnotSV/bin/AnnotSV -SVinputfile "/AnnotSV/bin/shared_hetero_dp_S3.vcf" -genomeBuild GRCh38 -benignAF 0.001 -annotationMode full -SVminSize 1 -vcf 1 -overwrite

17_15886243_15890470_DEL_1 | 17 | 15886243 | 15890470 | -4227 | DEL | pbsv.DEL.384 | 
```

When I used the same vcf file and used the 'split' annotation mode, I could not find annotation for the above region

`/AnnotSV/bin/AnnotSV -SVinputfile "/AnnotSV/bin/shared_hetero_dp_S3.vcf" -genomeBuild GRCh38 -benignAF 0.001 -annotationMode split -SVminSize 1 -vcf 1 -overwrite
`

Thank you

**Comment by lgmgeo** [comment]
For a better understanding of full and split lines, cf [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf):
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/b462bb86-55e1-41bb-b2c2-09683c3dfe9d)

In other words:
- To generate all “split” and "full" lines: `-annotationMode both`
- To keep only the full annotation lines: `-annotationMode full`
- To keep only the split annotation lines: `-annotationMode split`

In your case,"17_15886243_15890470_DEL" does not overlap any gene: 
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/616dba0f-8eec-4ba3-b285-1e20bd90d3d0)

=> So you don't have any split lines reported.

**Comment by priyambial123** [comment]
Thank you
