### ISSUE TITLE
gnomAD GRCh38 BED files have an empty line on top

### ISSUE THREAD

**Issue by boboppie** [lgmgeo/AnnotSV#22]
Dear AnnotSV developers,

Thank you for such a nice tool. 

We had experienced an issue which caused bedtools error:

> ...annotation in progress (August 17 2020 - 13:27)
-- gnomADannotation --
bedtools intersect -sorted -a ./test.cnv.formatted.sorted.bed.users.sorted.bed -b /home/annotsv/installed/share/AnnotSV/Annotations_Human/SVincludedInFt/gnomAD/GRCh38/20200716_liftoverGRCh38_gnomAD_DUP_SV.sorted.bed -wa -wb > ./test.cnv.formatted.sorted.intersect.gnomAD-DUP
Error: Type checker found wrong number of fields while tokenizing data line.
Exit with error

It appears to be an empty line in gnomAD GRCh38 BED files, deleting the first line will make it work again.
No issue with GRCh37.

Will you double check the files on your side please?

Best wishes,
Fengyuan

**Comment by lgmgeo** [comment]
Hi Fengyuan,

Sorry for the delay, I was on vacation.
Thank you so much for your help, everything should be back in order now.

Best,
Véronique
