### ISSUE TITLE
change Gene annotations into Gencode version

### ISSUE THREAD

**Issue by IcyYeyangchen** [lgmgeo/AnnotSV#220]
Hello,thanks for wonderful tools!
I have a question , I want to change the gene annotations version into GenCODE version , but i failed to change the file in the directory : $ANNOTSV/share/AnnotSV/Annotations_Human/Genes/GRCh38, could it possible? any helps?
Thanks for advance

**Comment by lgmgeo** [comment]
As I understand it, you don't want to use annotations from RefSeq or ENSEMBL, but rather those from GenCODE. Correct?

**Comment by IcyYeyangchen** [comment]
Yes ,that was what I meant, sorry for late reply.
Because I have the specific version GENCODE annotation of the same sample RNA-seq data , I wanna make SV annotation consistent with that.
I tried the script gtftogenepred to convert the GENCODE annotation gtf file and changed the file name in this directory :
$ANNOTSV/share/AnnotSV/Annotations_Human/Genes/GRCh38
I also modified the file format  , even I changed file's name into the "genes.RefSeq.sorted.bed"
all of  aboved try failed, so any suggesstion?

**Comment by lgmgeo** [comment]
Hi,

Sorry, currently AnnotSV only supports annotations from RefSeq or ENSEMBL.

What is exaclty your need?
Do you want to use (for gene annotation) the following GENCODE file? (Release 45, GRCh38.p14)
https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_45/gencode.v45.annotation.gtf.gz

If yes, you can try the following:
```
bash
cd $ANNOTSV/share/AnnotSV/Annotations_Human/Genes/GRCh38/
rm genes.ENSEMBL.sorted.bed
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_45/gencode.v45.annotation.gtf.gz
gunzip gencode.v45.annotation.gtf.gz
wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/gtfToGenePred
chmod +x gtfToGenePred
./gtfToGenePred -genePredExt -geneNameAsName2 -includeVersion gencode.v45.annotation.gtf refGene.txt
sed -i "s/chr//" refGene.txt

for i in 1 10 11 12 13 14 15 16 17 18 19 2 20 21 22 3 4 5 6 7 8 9 M MT X Y
    do awk -v chr=$i '$2 ==chr {print $2"\t"$4"\t"$5"\t"$3"\t"$12"\t"$1"\t"$6"\t"$7"\t"$9"\t"$10}' refGene.txt | sed 's/^MT/M/' | sort -k1,1 -k2,2n -k3,3n >> refGene.sorted.tmp.tmp.bed
done
grep -v "none" refGene.sorted.tmp.tmp.bed > refGene.sorted.tmp.bed

rm gtfToGenePred refGene.txt gencode.v45.annotation.gtf refGene.sorted.tmp.tmp.bed
```
Then run AnnotSV.

**Comment by IcyYeyangchen** [comment]
Thanks for your apply 
It works after running your script ,and setting `---tx ENSEMBL`
