### ISSUE TITLE
Genehancer files not being recognized

### ISSUE THREAD

**Issue by alexanderchang1** [lgmgeo/AnnotSV#221]
Hi,

For some reason even when I follow the ReadMe, I'm not getting my GeneHancer Files recognized, the GeneHancer team sent me the .txt files directly without a .zip but I renamed the files to match the names in the README.

WARNING: No GeneHancer annotations available.
(Please, see in the README file how to add these annotations. Users need to contact the GeneCards team.)

[achang4@bridges2-login012 RegulatoryElements]$ tree
.
|-- GRCh37
|   |-- ABC_ENSEMBL_GRCh37.sorted.bed
|   |-- ABC_RefSeq_GRCh37.sorted.bed
|   |-- EA_ENSEMBL_GRCh37.sorted.bed
|   |-- EA_RefSeq_GRCh37.sorted.bed
|   |-- MPRA_ENSEMBL_GRCh37.sorted.bed
|   |-- MPRA_RefSeq_GRCh37.sorted.bed
|   |-- miRTargetLink_ENSEMBL_GRCh37.sorted.bed
|   |-- miRTargetLink_RefSeq_GRCh37.sorted.bed
|   |-- promoter_500bp_ENSEMBL_GRCh37.sorted.bed
|   -- promoter_500bp_RefSeq_GRCh37.sorted.bed
|-- GRCh38
|   |-- EA_ENSEMBL_GRCh38.sorted.bed
|   |-- EA_RefSeq_GRCh38.sorted.bed
|   |-- MPRA_ENSEMBL_GRCh38.sorted.bed
|   |-- MPRA_RefSeq_GRCh38.sorted.bed
|   |-- miRTargetLink_ENSEMBL_GRCh38.sorted.bed
|   |-- miRTargetLink_RefSeq_GRCh38.sorted.bed
|   |-- promoter_500bp_ENSEMBL_GRCh38.sorted.bed
|   -- promoter_500bp_RefSeq_GRCh38.sorted.bed
|-- GeneHancer-5.19-for-annotsv
|   |-- GeneHancer_elements.txt
|   |-- GeneHancer_gene_association_scores.txt
|   |-- GeneHancer_hg19.txt
|   |-- GeneHancer_tissues.txt
|   -- ReadMe.txt
|-- GeneHancer_elements.txt
|-- GeneHancer_gene_association_scores.txt
|-- GeneHancer_hg19.txt
|-- GeneHancer_tissues.txt
-- ReadMe.txt

**Comment by lgmgeo** [comment]
You should see in `$ANNOTSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/`:
GeneHancer_elements.txt  
GeneHancer_gene_associations_scores.txt  
GeneHancer_hg19.txt  

Surprisingly, AnnotSV does not see at least 1 of these files.

Can you show me the result of:
```
ls -l $ANNOTSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GeneHancer*
```

Else, what is your command line? 
Do you use the -annotationsDir option?
Do you use a conda environment?

**Comment by alexanderchang1** [comment]
Hi,

I do not use a specific conda environment but I do load the module on my cluster to avoid issues, please see below for my full command. I wasn't using the annotationsDir option, would you mind showing me an example use case? I assumed the export function took care of that. 

Code: 
`module load anaconda3/2022.10

module load bcftools/1.10.2

module load bedtools/2.30.0

export ANNOTSV=/ocean/projects/aurora/achang4/annotSV/AnnotSV



# Define the base directory
BASE_DIR="/ocean/projects/aurora/achang4/sarek/Part2_FASTQ2SAREK/results/variant_calling/manta"

# Navigate to the base directory
cd "$BASE_DIR"

# Loop through subdirectories that contain '_vs_' in their names
for SUBDIR in *; do
    if [[ -d "$SUBDIR" ]] && [[ "$SUBDIR" == *"_vs_"* ]]; then
        # Define the VCF file name based on the subdirectory name
        VCF_FILE="${SUBDIR}/${SUBDIR}.manta.somatic_sv.vcf.gz"

        # Check if the VCF file exists
        if [[ -f "$VCF_FILE" ]]; then
            # Define the SVinputfile variable
            SVinputfile="$VCF_FILE"

            # Run the AnnotSV command
            $ANNOTSV/bin/AnnotSV -SVinputFile "$SVinputfile" -outputFile "/ocean/projects/aurora/achang4/sarek/Part3_AnnotSV/${SVinputfile}.annotated.tsv" -svtBEDcol 4
        else
            echo "File $VCF_FILE not found."
        fi
    fi
done`

Output of ls -l $ANNOTSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GeneHancer*

`[achang4@bridges2-login011 ~]$ ls -l $ANNOTSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GeneHancer*
-rw-r--r-- 1 achang4 aurora  26496045 Mar 15 20:43 /ocean/projects/aurora/achang4/annotSV/AnnotSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GeneHancer_elements.txt
-rw-r--r-- 1 achang4 aurora 109360712 Mar 15 20:43 /ocean/projects/aurora/achang4/annotSV/AnnotSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GeneHancer_gene_associat
ion_scores.txt
-rw-r--r-- 1 achang4 aurora  15004540 Mar 15 21:15 /ocean/projects/aurora/achang4/annotSV/AnnotSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GeneHancer_hg19.txt
-rw-r--r-- 1 achang4 aurora 219631020 Mar 15 20:43 /ocean/projects/aurora/achang4/annotSV/AnnotSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GeneHancer_tissues.txt
/ocean/projects/aurora/achang4/annotSV/AnnotSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GeneHancer-5.19-for-annotsv:
total 361828
-rw-r--r-- 1 achang4 aurora  26496045 Mar 15 20:43 GeneHancer_elements.txt
-rw-r--r-- 1 achang4 aurora 109360712 Mar 15 20:43 GeneHancer_gene_association_scores.txt
-rw-r--r-- 1 achang4 aurora  15004540 Mar 15 20:43 GeneHancer_hg19.txt
-rw-r--r-- 1 achang4 aurora 219631020 Mar 15 20:43 GeneHancer_tissues.txt
-rw-r--r-- 1 achang4 aurora      1305 Mar 15 20:43 ReadMe.txt`

**Comment by lgmgeo** [comment]
Ok, the 3 files (GeneHancer_elements.txt, GeneHancer_gene_associations_scores.txt and GeneHancer_hg19.txt) are well located.
Very strange that AnnotSV can't see them.

Can you try:
```
$ANNOTSV/bin/AnnotSV -SVinputFile "$SVinputfile" -outputFile "/ocean/projects/aurora/achang4/sarek/Part3_AnnotSV/${SVinputfile}.annotated.tsv" -svtBEDcol 4 -annotationsDir /ocean/projects/aurora/achang4/annotSV/AnnotSV/share/AnnotSV
```

Else, can you try to change permissions before to run AnnotSV:
`
chmod 755 $ANNOTSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GeneHancer*
`

**Comment by alexanderchang1** [comment]
Hi, I implemented both of those and it's still not working

Corrected code
```
module load anaconda3/2022.10

module load bcftools/1.10.2

module load bedtools/2.30.0

export ANNOTSV=/ocean/projects/aurora/achang4/annotSV/AnnotSV

chmod 755 $ANNOTSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/RegulatoryElements/GeneHancer*


# Define the base directory
BASE_DIR="/ocean/projects/aurora/achang4/sarek/Part2_FASTQ2SAREK/results/variant_calling/manta"

# Navigate to the base directory
cd "$BASE_DIR"

# Loop through subdirectories that contain '_vs_' in their names
for SUBDIR in *; do
    if [[ -d "$SUBDIR" ]] && [[ "$SUBDIR" == *"_vs_"* ]]; then
        # Define the VCF file name based on the subdirectory name
        VCF_FILE="${SUBDIR}/${SUBDIR}.manta.somatic_sv.vcf.gz"

        # Check if the VCF file exists
        if [[ -f "$VCF_FILE" ]]; then
            # Define the SVinputfile variable
            SVinputfile="$VCF_FILE"

            # Run the AnnotSV command
            $ANNOTSV/bin/AnnotSV -SVinputFile "$SVinputfile" -outputFile "/ocean/projects/aurora/achang4/sarek/Part3_AnnotSV/${SVinputfile}.annotated.tsv" -svtBEDcol 4 -annotationsDir /ocean/projects/aurora/achang4/annotSV/AnnotSV/share/AnnotSV
        else
            echo "File $VCF_FILE not found."
        fi
    fi
done
```

Head of output


```
AnnotSV 3.4

Copyright (C) 2017-2024 GEOFFROY Veronique

Please feel free to create a Github issue for any suggestions or bug reports (https://github.com/lgmgeo/AnnotSV/issues)

Tcl/Tk version: 8.6

Application name used:
/ocean/projects/aurora/achang4/annotSV/AnnotSV


...downloading the configuration data (March 19 2024 - 10:50)
	...configuration data by default
	...configuration data from /ocean/projects/aurora/achang4/annotSV/AnnotSV/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

...VCF to BED (March 19 2024 - 10:50)


...checking the annotation data sources (March 19 2024 - 10:50)

WARNING: No GeneHancer annotations available.
(Please, see in the README file how to add these annotations. Users need to contact the GeneCards team.)

```

**Comment by lgmgeo** [comment]
Ok, quite difficult to debug from here... Let's have a try.

1 - Save the 'AnnotSV-regulatoryelements.tcl' file from your install
```
mv $ANNOTSV/share/tcl/AnnotSV/AnnotSV-regulatoryelements.tcl $ANNOTSV/share/tcl/AnnotSV/AnnotSV-regulatoryelements.tcl.sauv
```
2 - Replace with the uncompress [AnnotSV-regulatoryelements.tcl.gz](https://github.com/lgmgeo/AnnotSV/files/14652836/AnnotSV-regulatoryelements.tcl.gz)
```
gunzip AnnotSV-regulatoryelements.tcl.gz
mv AnnotSV-regulatoryelements.tcl $ANNOTSV/share/tcl/AnnotSV/
```
3 - Run AnnotSV and send me the output.

**Comment by alexanderchang1** [comment]
I had to modify all commands to be tcl8.6 instead like this, just FYI, I don't know that matters. 

```
mv AnnotSV-regulatoryelements.tcl $ANNOTSV/share/tcl8.6/AnnotSV/
```

Here's the output files, I believe the problem was a typo in the annotation file I got from GeneHancer being labelled as annotation instead of annotationS. These errors disappeared once I fixed that. Should I revert back to the previous .tcl file and try again? 

[annotate_sv_23053643_error.txt](https://github.com/lgmgeo/AnnotSV/files/14673071/annotate_sv_23053643_error.txt)
[annotate_sv_23053643_out.txt](https://github.com/lgmgeo/AnnotSV/files/14673075/annotate_sv_23053643_out.txt)

**Comment by lgmgeo** [comment]
What a stupid glitch...
Neither of us saw that there was an "s" missing from the name of this file (and yet I had compared the file names).

Ok, revert back to the previous .tcl file and try again. This should work.

**Comment by lgmgeo** [comment]
For next time, the best thing to do would be to request the updated v5.19 ZIP file for AnnotSV directly from GeneHancer.

**Comment by alexanderchang1** [comment]
Hi, just an FYI, GeneHancer sent me the files like this which caused me to have to rename things, the typo is inbuilt to the link they send. 

GeneHancer_AnnotSV_gene_association_scores_v5.19.txt
