### ISSUE TITLE
Annotations - website 

### ISSUE THREAD

**Issue by priyambial123** [lgmgeo/AnnotSV#222]
Hello Véronique,

I annotated using annotsv version 3.3.4.

```
Annotation:
chrX startsite:31,452,231-31,452,564 is annotated to DMD gene in intron 16
```
![Capture](https://github.com/lgmgeo/AnnotSV/assets/11889537/4ee97217-701f-4378-96a8-acb5965379e7)

The same region, recently i checked in annotsv website, it shows in DMD gene in intron5
![image](https://github.com/lgmgeo/AnnotSV/assets/11889537/2c345b80-ccf7-4217-8d9c-264e72f1061c)

Was something changed in the recent version?

Thank you

Priya

**Comment by lgmgeo** [comment]
The version of the AnnotSV website is 3.4 => Human annotation have been updated.

I can not reproduced your result on the website. Can you give me all the parameters you use?
SV coordinates : "2:31452231-31452564 INS"
Else?

**Comment by lgmgeo** [comment]
AnnotSV 3.4 annotates your INS with NM_004014.3.

https://genome-euro.ucsc.edu/cgi-bin/hgc?hgsid=326977599_2TJgd5TmLU4vT5AZDyRFXyFdXKpy&db=hg38&c=chrX&l=31452231&r=31452564&o=31119221&t=31508296&g=ncbiRefSeqCurated&i=NM_004014.3

![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/f6266202-24a0-4c9d-bf3e-d50f7b4a82c9)

**Comment by priyambial123** [comment]
Thank you for letting me know. Can you also let me know the database that was used for the human annotation to intron or exon region

Thank you

Priya

**Comment by lgmgeo** [comment]
cf [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf)
=> RefSeq or ENSEMBL (user defined)
