### ISSUE TITLE
Error with example command

### ISSUE THREAD

**Issue by arkatebi** [lgmgeo/AnnotSV#224]
When execute the command in share/doc/AnnotSV/Example/commands.README file, I get the following error message: 
...downloading the configuration data (April 01 2024 - 13:36)
	...configuration data by default
	...configuration data from /Users/a.katebi/research.zlab/AnnotSV/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

############################################################################
Bad value for the bedtools option (bedtools)
couldn't execute "bedtools": no such file or directory
Exit with error.
############################################################################

**Comment by lgmgeo** [comment]
cf [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf):
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/6dd9f915-f280-457b-9fcc-648db1bd275c)
