### ISSUE TITLE
mm39 can't use

### ISSUE THREAD

**Issue by uso2015** [lgmgeo/AnnotSV#225]
Hi,

       I use mm39(GRCm39) genome to analyse SV and CNV，but AnnotSV can't annotate the result，I need help.

**Comment by lgmgeo** [comment]
Hi,

Currently, annotation can be performed using either the mm9 or mm10 build version of the mouse genome.

I'll try to add mm39 by the end of the month (not sure I'll find the time), I'll keep you posted here.

Véronique

**Comment by uso2015** [comment]
> The mm39 code and README are available on the `patch_AnnotSV ` development branch: https://github.com/lgmgeo/AnnotSV/tree/patch_AnnotSV
> 
> Mouse annotations will be available for download in the next release. I will keep you posted here.

**Comment by uso2015** [comment]
> [AnnotSV 3.4.1](https://github.com/lgmgeo/AnnotSV) is posted with updated Mouse annotation (add of GRCm39/mm39 annotations). Can you confirm that everything is working fine?
"AnnotSV-3.4.1/share/AnnotSV/Annotations_Mouse/BreakpointsAnnotations/Repeat/mm39/20240409_Repeat.sorted.bed" is incomplete, other ok.

**Comment by lgmgeo** [comment]
Ooops!
This was fixed with AnnotSV 3.4.2
