### ISSUE TITLE
Annotation in progress part costs too long time

### ISSUE THREAD

**Issue by boyanboyue** [lgmgeo/AnnotSV#226]
HI,I meet a very confusing problem.
I installed AnnotSV3.4 by conda to a docker image and started  it in a container.
I downloaded the human database by your command.The software did well in the container that download the databse one,but as I copied the database and start a new container,Annotation in progress part costs too long time.
Can you tell me why this condition happened and what can I do if I want to avoid this condition when I want to use the software in a docker image?
I am looking forward to your reply.

**Comment by lgmgeo** [comment]
@nvnieuwk, do you have any advice?

**Comment by nvnieuwk** [comment]
Can you share your Dockerfile and command used @boyanboyue? Along with any specifications of the system your are trying to run this on (operating system, docker version...)

**Comment by boyanboyue** [comment]
The Dockerfile I used is based on mamba base docker images with python=3.9 version.
Then I use this command "docker run -it -v /{xxx}/:/data {mamba.images} /bin/bash" to start a container.
In the container,I use "mamba install bioconda::annotsv=3.4 -y" to install annotsv.
After that I used "cd /xxx/conda/pkg/annotsv-3.4-py312hdfd78af_1/" into the directory with Makefile.
Then I used "make PREFIX=. install-human-annotation" to install human databse.
After that I used "cp -r share/AnnotSV /{xxx}/AnnotSV" to copy the database to a place that I can easily used next time.
Now,if I use "AnnotSV -annotationsDir ${share/AnnotSV} -genomeBuild ${GENOME} -SVinputFile ${BASENAME} -bedtools bedtools -outputFile ${SM} -outputDir ./ -overlap 80" to annotate a vcf file,it will be ok.
But if I start a new container and install the annotsv by the same way and don't install the database instead of attaching the database which I have copied to my computer to a container,and I used the same file and command to annotate,it will cost so long time in Annotation in progress part.

The information of opration system is below:
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Docker version is "Docker version 24.0.6, build ed223bc".

I think that this problem probably because of my actions.
Is there any index or cache maybe be made and not in the "share/AnnotSV" in the database installing time?

**Comment by nvnieuwk** [comment]
Hi thank you for the thorough explanation. First of all can I suggest to add all those commands to you Dockerfile and create a container image like that? That way you won't have to rerun all those commands every time you want to use the tool. Alternatively, you can use `quay.io/biocontainers/annotsv:3.4--py312hdfd78af_1` as your docker image. This image contains all the tooling already installed. You only need to supply the annotations directory to it with a volume (`docker run -v <path_to_annotations>:/annotations quay.io/biocontainers/annotsv:3.4--py312hdfd78af_1 AnnotSV -annotationsDir /annotations ...`)

**Comment by lgmgeo** [comment]
@boyanboyue, any news?

**Comment by boyanboyue** [comment]
I‘m sorry to reply after so long time.
I find something wrong in our machine and the situation I mentioned before is possible because of this reason.
I' busy dealing with machine things.
So sorry for my forgetting to reply.
Thanks a lot for your concern！
