### ISSUE TITLE
BND negative length

### ISSUE THREAD

**Issue by 5im1z** [lgmgeo/AnnotSV#228]
Hi,

Thanks for this amazing resource!

I'm running AnnotSV 3.4 with `-annotationMode full -includeCI 0 -SVminSize 1`. I was hoping to annotate VCF outputs from Manta, but saw that some variants, breakpoint insertions in particular, are not annotated, for example:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT sample
chr12	45281622	MantaBND:95393:0:1:0:0:0:1	A	[chr12:45339452[AAGA	.	PASS	SVTYPE=BND;MATEID=MantaBND:95393:0:1:0:0:0:0;SVINSLEN=3;SVINSSEQ=AAG;BND_DEPTH=60;MATE_BND_DEPTH=63	PR:SR	46,20:62,10
```

This is what it says in the unannotated output file:

`12_45281622_45281622_INS_A_[12:45339452[AAGA: variantLength (-1) < SVminSize (1) (line 15491)`

I'm wondering why AnnotSV thinks the length of this variant is -1. Is my VCF formatted in a way that's not compatible? Is there a way around this so this variant can be annotated?

Any pointers would be appreciated. Thank you!
Simone

**Comment by lgmgeo** [comment]
Hi Simone,

Can you give me the corresponding mate line? ID=MantaBND:95393:0:1:0:0:0:0

Véronique

**Comment by lgmgeo** [comment]
Your insertion seems badly formatted.
I explain:
In AnnotSV, the comprehension of the square-bracketed notations relies on the homogenization rules from the variantextractor tool (provided by Rodrigo Martin). 
By running [variant-extractor](https://github.com/EUCANCan/variant-extractor#homogenization-rules), I get this information:
```
id,start_chrom,start,end_chrom,end,ref,alt,length,brackets,type_inferred
,12,45281622,12,45339452,A,[chr12:45339452[AAGA,57830,[N,INV
```
variant-extractor homogenized and returned your variant as an Inversion.

**Comment by 5im1z** [comment]
Hi Véronique,

Thanks for getting back to me so quickly.

I can now see why this is classified as an inversion (with small insertions at breakpoints), but it's still not clear to me why it has a variantLength of -1. Here's the mate line:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT sample
chr12	45339452	MantaBND:95393:0:1:0:0:0:0	T	[chr12:45281622[CTTT	.	PASS	SVTYPE=BND;MATEID=MantaBND:95393:0:1:0:0:0:1;SVINSLEN=3;SVINSSEQ=CTT;BND_DEPTH=63;MATE_BND_DEPTH=60	PR:SR	46,20:62,10
```

What would be the correct way to format a pair like this?

Thank you!
Simone

**Comment by lgmgeo** [comment]
> it's still not clear to me why it has a variantLength of -1.

Actually, in the AnnotSV code, this bad format is not taken into account. 
The variantLength is therefore incorrect because AnnotSV does not detect this breakpoint as such and mixes between insertion and inversion.

Your example:
```
chr12	45281622	MantaBND:95393:0:1:0:0:0:1	A	[chr12:45339452[AAGA	.	PASS	SVTYPE=BND;MATEID=MantaBND:95393:0:1:0:0:0:0;SVINSLEN=3;SVINSSEQ=AAG;BND_DEPTH=60;MATE_BND_DEPTH=63	PR:SR	46,20:62,10
chr12	45339452	MantaBND:95393:0:1:0:0:0:0	T	[chr12:45281622[CTTT	.	PASS	SVTYPE=BND;MATEID=MantaBND:95393:0:1:0:0:0:1;SVINSLEN=3;SVINSSEQ=CTT;BND_DEPTH=63;MATE_BND_DEPTH=60	PR:SR	46,20:62,10
```
If I well understand, your example is not only an insertion (AAGA or CTTT) but also a deletion (chr12:45281622-45339452).
So I don't know how to correctly represent this complex SV. 

I will add a fix in AnnotSV and look at the SVTYPE first. If set to BND, only the 2 breakpoints will be annotated.
