### ISSUE TITLE
Web server runjob not responding when input custom vcf file

### ISSUE THREAD

**Issue by Mirror-fish** [lgmgeo/AnnotSV#229]
Hi,
I'm recently testing the annotation on manta output file, I uploaded my custom file about 2.5Mb in size. But the server just had no response after I clicked the button 'Submit'.

I wonder if it's my problem, can you please check if other users had the same problem?

By the way, I tried the 'SV input file example' and it started running with no problem, but later I received a message saying 'SVinputFile too big'. I even downloaded the example file and re-submitted it, but it still responded 'SVinputFile too big'.
The job id of these two jobs are jqwALE7Cka and eE4XnSTzoi.

Thanks for reading! Any advices would be appreciated!
Jingyu

**Comment by Mirror-fish** [comment]
I tried again today, and everything is ok now. But when I tried to submit a larger file (30Mb in size), the server just had no response again after I clicked the button 'Submit'. The error I get from the explorer is ERR_CONNECTION_ABORTED.

I wonder if it's because of bad internet connection, the upload speed is too slow and the server just shut down the upload process? About 30 seconds after I clicked 'Submit', the connection was aborted.

**Comment by lgmgeo** [comment]
I just checked with our administrator, everything seems normal on our end.
I ran the example just now without a problem.
I haven't been contacted by other users either.
Sorry

**Comment by lgmgeo** [comment]
Can you install AnnotSV locally? That would be the best thing to do.

**Comment by Mirror-fish** [comment]
@lgmgeo Thank you, I guess it's because of the internet I'm using. I'll try again later in other places.
