### ISSUE TITLE
The meaning of number behind CLN (Clinvar) in Known pathogenic genes or genomic regions annotation

### ISSUE THREAD

**Issue by namxle** [lgmgeo/AnnotSV#230]
Hello,

I have a question about the number following the `CLN` (ClinVar source) included in the `po_P_*_source` column. For example, `CLN:566916`.

Is this a ClinVar Variation ID, which I can search by entering this URL: https://www.ncbi.nlm.nih.gov/clinvar/variation/566916/?

If so, I don't understand why in the `AnnotSv_ID`: `7_5958499_6018327_DUP_1`, my `P_loss_source` can contain `CLN:566916`, which belongs to chromosome 5.

Thank you very much!

**Comment by lgmgeo** [comment]
Hi @namxle,

- **Context:**
Pathogenic SVs are selected in ClinVar as follows (cf [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf)):
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/a082ab0a-4a94-4e7c-902c-9f85711efbaf)

- **ClinVar source file (VCF)**
In the GRCh38 VCF source file, here is your `CLN:566916` example:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/41deeb42-e755-4458-9953-c6dfb0a38a91)
=> The ID reported in AnnotSV (`CLN:566916`) corresponds to the ALLELEID present in the ClinVar VCF.

- **AnnotSV install**
FYI, you can find the pathogenic SVs in the following file: 
$ANNOTSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/PathogenicSV/GRCh38/pathogenic_Loss_SV_GRCh38.sorted.bed
Your example corresponds to the following line:
```
7  5977077 5977677 Hereditary_nonpolyposis_colorectal_neoplasms            CLN:566916      7:5977077-5977677
```

- **WARNING**: 
> Is this a ClinVar Variation ID, which I can search by entering this URL: https://www.ncbi.nlm.nih.gov/clinvar/variation/566916/?

No.
Please go to https://www.ncbi.nlm.nih.gov/clinvar and search for 566916[AlleleID]

![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/695ea9ea-e409-4794-be10-e8ceff4c185a)
=> https://www.ncbi.nlm.nih.gov/clinvar/variation/579556/?oq=566916[AlleleID]&m=NM_000535.7(PMS2):c.2357_2445%20510del

Best,
Véronique

**Comment by lgmgeo** [comment]
The next README will be updated

**Comment by namxle** [comment]
@lgmgeo Thank you a lot for your explanation!
