### ISSUE TITLE
MAF in gnomAD 

### ISSUE THREAD

**Issue by somayehbakhtiari** [lgmgeo/AnnotSV#235]
Hi,
I have used AnnotSV v3.4 to annotate copy number variants identified through the GATK-gCNV pipeline. I need to filter these variants based on their frequency in gnomAD, but can find such information in the annotated file. 
Your help would be much appreciated!

**Comment by lgmgeo** [comment]
Hi Somaye,

Thank you for your interest in AnnotSV.

According to the ACMG technical standards (Riggs et al., 2020), a SV completely contained within an established benign CNV region would be classified as benign (if sharing the same SV type).
=> In this aim, AnnotSV searches for benign genomic regions completely overlapping the SV to annotate.
Benign regions are selected from different sources:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/159a14ed-f14e-4b1a-8743-b9ac0cf3a3cd)

For example, the method to extract benign SV from gnomAD:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/323e42d4-befe-4cd9-b7fd-a32742cd4bb6)


So, to filter out benign DUP, you can use: 
`B_gain_AFmax`: Maximum allele frequency of the reported benign gain genomic regions (if available) 

And to filter out benign DEL:
`B_loss_AFmax`: Maximum allele frequency of the reported benign loss genomic regions (if available)

Another way is to specifically analyse the CNV with `ACMG_class` = 5 or 4. 

Best,

Véronique
