### ISSUE TITLE
Question about reverse strand genes

### ISSUE THREAD

**Issue by bwubb** [lgmgeo/AnnotSV#238]
Hello, I am trying to understand if there is a way for AnnotSV to annotate reverse strand genes in the proper exon numbering.

I have a sample with a duplication in BRCA1 spanning exon 12. The bed input line appears as:

`17      43076446        43090796        14351bp;loh;gain;A4;B0  400     +`

This will be annotated in AnnotSV as: 
`BRCA1   ENST00000644379  43045085        43091851        14350   365     18      yes     15      **intron2-intron5** CDS`

I cant be the first to point out the error in reverse strand exon/intron coordinates; is there some argument I need to add? Documentation does not appear to indicate anything. Thank you.

-bwubb

**Comment by lgmgeo** [comment]
GRCh38 try:

AnnotSV_ID : 17_43076447_43090796__1 17     
Genes : BRCA1                          
Tx : ENST00000644379 
Tx_version : 2 
Location : intron11-intron14
=> Looks goot to me (spanning exon 12)

**Comment by bwubb** [comment]
Thank you for the help. Im hoping its just user error.

I am currently using AnnotSV version 3.1.1.

My command would be:

AnnotSV -SVinputFile {input} -annotationMode split -genomeBuild GRCh38 -tx ENSEMBL -outputFile {output}

And it would be the Location column

**Comment by bwubb** [comment]
Oh no, Ill be disappointed in myself if its just a version update. Let me check.

**Comment by bwubb** [comment]
Thank you very much. Sorry for the trouble!
