### ISSUE TITLE
Map BEDPE-based structrure variation (SV) to human genes (BED or GTF)? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [lgmgeo/AnnotSV#24]
Hi Geoffroy, 

Does the latest AnnotSV support to map BEDPE-based structrure variation (SV) to human genes (BED or GTF)? 

Thanks. 

Shicheng

**Comment by lgmgeo** [comment]
Hi Shicheng-Guo,

Sorry, BEDPE is not yet supported by AnnotSV. 

Best,

Véronique
