### ISSUE TITLE
 left gene

### ISSUE THREAD

**Issue by bioinfomatio** [lgmgeo/AnnotSV#242]
Hi 
Why is the gene closest to it on the left side not ZNF384, but RP11-1038A11.1？The location is: 12:6800414

![image](https://github.com/lgmgeo/AnnotSV/assets/160692531/a3b1c7f7-99ab-4ec0-aa6d-eb24a25ebe59)
![image](https://github.com/lgmgeo/AnnotSV/assets/160692531/5dcf6f61-cd11-4b20-88a0-7cadba949885)

![image](https://github.com/lgmgeo/AnnotSV/assets/160692531/e17f362e-103d-4349-be1b-822c8a8cf381)

**Comment by lgmgeo** [comment]
**Please detail your request when reporting a bug (command line, etc.)**

I run:
```
$ANNOTSV/bin/AnnotSV -SVinputFile ./test.bed -outputFile ./test.annotated.tsv -svtbedcol 4 -tx ENSEMBL -genomeBuild GRCh37
```
with:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/9b49d84b-523c-4f8e-b23e-e79edb685d1a)

But I can't reproduced the bug, everything seems correct on my side:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/dedcdb9b-7a03-49d1-9d9a-a076227bc880)

Please, give me your command line and attach the VCF input file with your "12:6800414" translocation.

**Comment by bioinfomatio** [comment]
chr12	6800414	MantaBND:17297:0:1:0:0:0:0	C	C]chr22:41540267]	.	PASS	SVTYPE=BND;MATEID=MantaBND:17297:0:1:0:0:0:1;BND_DEPTH=122;MATE_BND_DEPTH=145	PR:SR	89,20:135,16

**Comment by bioinfomatio** [comment]
chr12	6800414	MantaBND:17297:0:1:0:0:0:0	C	C]chr22:41540267]	.	PASS	SVTYPE=BND;MATEID=MantaBND:17297:0:1:0:0:0:1;BND_DEPTH=122;MATE_BND_DEPTH=145	PR:SR	89,20:135,16
chr22	41540267	MantaBND:17297:0:1:0:0:0:1	A	A]chr12:6800414]	.	PASS	SVTYPE=BND;MATEID=MantaBND:17297:0:1:0:0:0:0;BND_DEPTH=145;MATE_BND_DEPTH=122	PR:SR	89,20:135,16

**Comment by bioinfomatio** [comment]
![image](https://github.com/lgmgeo/AnnotSV/assets/160692531/5b3bfee7-b411-4bbb-a205-00b2bab03b63)
The result is RP11-1038A11.1, the correct result should be ZNF384

**Comment by lgmgeo** [comment]
Can you join the VCF input file in a new comment (in place of copy/paste)?
This will save me from having to tab the VCF file myself and create a header.

**Comment by bioinfomatio** [comment]
##fileformat=VCFv4.1
##fileDate=20240625
##source=GenerateSVCandidates 1.6.0
##reference=file:////ucsc.hg19.fasta
##contig=<ID=chrM,length=16571>
##contig=<ID=chr1,length=249250621>
##contig=<ID=chr2,length=243199373>
##contig=<ID=chr3,length=198022430>
##contig=<ID=chr4,length=191154276>
##contig=<ID=chr5,length=180915260>
##contig=<ID=chr6,length=171115067>
##contig=<ID=chr7,length=159138663>
##contig=<ID=chr8,length=146364022>
##contig=<ID=chr9,length=141213431>
##contig=<ID=chr10,length=135534747>
##contig=<ID=chr11,length=135006516>
##contig=<ID=chr12,length=133851895>
##contig=<ID=chr13,length=115169878>
##contig=<ID=chr14,length=107349540>
##contig=<ID=chr15,length=102531392>
##contig=<ID=chr16,length=90354753>
##contig=<ID=chr17,length=81195210>
##contig=<ID=chr18,length=78077248>
##contig=<ID=chr19,length=59128983>
##contig=<ID=chr20,length=63025520>
##contig=<ID=chr21,length=48129895>
##contig=<ID=chr22,length=51304566>
##contig=<ID=chrX,length=155270560>
##contig=<ID=chrY,length=59373566>
##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Imprecise structural variation">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="Confidence interval around POS">
##INFO=<ID=CIEND,Number=2,Type=Integer,Description="Confidence interval around END">
##INFO=<ID=CIGAR,Number=A,Type=String,Description="CIGAR alignment for each alternate indel allele">
##INFO=<ID=MATEID,Number=.,Type=String,Description="ID of mate breakend">
##INFO=<ID=EVENT,Number=1,Type=String,Description="ID of event associated to breakend">
##INFO=<ID=HOMLEN,Number=.,Type=Integer,Description="Length of base pair identical homology at event breakpoints">
##INFO=<ID=HOMSEQ,Number=.,Type=String,Description="Sequence of base pair identical homology at event breakpoints">
##INFO=<ID=SVINSLEN,Number=.,Type=Integer,Description="Length of insertion">
##INFO=<ID=SVINSSEQ,Number=.,Type=String,Description="Sequence of insertion">
##INFO=<ID=LEFT_SVINSSEQ,Number=.,Type=String,Description="Known left side of insertion for an insertion of unknown length">
##INFO=<ID=RIGHT_SVINSSEQ,Number=.,Type=String,Description="Known right side of insertion for an insertion of unknown length">
##INFO=<ID=BND_DEPTH,Number=1,Type=Integer,Description="Read depth at local translocation breakend">
##INFO=<ID=MATE_BND_DEPTH,Number=1,Type=Integer,Description="Read depth at remote translocation mate breakend">
##FORMAT=<ID=PR,Number=.,Type=Integer,Description="Spanning paired-read support for the ref and alt alleles in the order listed">
##FORMAT=<ID=SR,Number=.,Type=Integer,Description="Split reads for the ref and alt alleles in the order listed, for reads where P(allele|read)>0.999">
##FILTER=<ID=MaxDepth,Description="Sample site depth is greater than 3x the median chromosome depth near one or both variant breakends">
##FILTER=<ID=MaxMQ0Frac,Description="For a small variant (<1000 base), the fraction of reads with MAPQ0 around either breakend exceeds 0.4">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=INS,Description="Insertion">
##ALT=<ID=DUP:TANDEM,Description="Tandem Duplication">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	WGS20240089
chr12	6800414	MantaBND:17297:0:1:0:0:0:0	C	C]chr22:41540267]	.	PASS	SVTYPE=BND;MATEID=MantaBND:17297:0:1:0:0:0:1;BND_DEPTH=122;MATE_BND_DEPTH=145	PR:SR	89,20:135,16
chr22	41540267	MantaBND:17297:0:1:0:0:0:1	A	A]chr12:6800414]	.	PASS	SVTYPE=BND;MATEID=MantaBND:17297:0:1:0:0:0:0;BND_DEPTH=145;MATE_BND_DEPTH=122	PR:SR	89,20:135,16

**Comment by lgmgeo** [comment]
Can you add this VCF file? (not paste)

**Comment by bioinfomatio** [comment]
[Uploading 6800414.v1.vcf.gz…]()

**Comment by lgmgeo** [comment]
Sorry, I can't reproduce your data.

I run AnnotSV 3.4.2:
```
$ANNOTSV/bin/AnnotSV -SVinputFile ./test.vcf -outputFile ./test.annotated.tsv -tx ENSEMBL -genomeBuild GRCh37
```
And I obtained:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/f6ecc158-2620-46e7-8c7a-06d888dd8209)

**Comment by bioinfomatio** [comment]
https://github.com/bioinfomatio/public-/blob/main/6800414.v1.vcf.gz

**Comment by bioinfomatio** [comment]
[6800414.v1.vcf.gz](https://github.com/user-attachments/files/16125891/6800414.v1.vcf.gz)

**Comment by lgmgeo** [comment]
Same results
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/fc79bbcd-7b5f-4ffb-857d-2768d3729e63)

Did you run:
- The same command line?
```
$ANNOTSV/bin/AnnotSV -SVinputFile ./6800414.v1.vcf -outputFile ./6800414.v1..annotated.tsv -tx ENSEMBL -genomeBuild GRCh37
```
- The same AnnotSV version? (3.4.2)

**Comment by bioinfomatio** [comment]
I repeated your code, but the result is still RP11-1038A11.1.

![image](https://github.com/lgmgeo/AnnotSV/assets/160692531/fd561651-4658-4c74-931e-495e9580f482)


![image](https://github.com/lgmgeo/AnnotSV/assets/160692531/b927a124-2095-434d-a608-221eb3adbc71)

The reason for the different results may be that the genes.ensembl.sorted.bed file is different. Could you please upload the genes.ensembl.sorted.bed file?

**Comment by bioinfomatio** [comment]
[Uploading genes.ENSEMBL.sorted.zip…]()

**Comment by bioinfomatio** [comment]
[genes.ENSEMBL.sorted.zip](https://github.com/user-attachments/files/16139812/genes.ENSEMBL.sorted.zip)

**Comment by lgmgeo** [comment]
The genes.ensembl.sorted.bed annotation file is specific to each AnnotSV version.
So we should have the same file.
I really don't understand the problem.

Could another user please help and try to reproduce the bug?

**Comment by lgmgeo** [comment]
Ok, by replacing your file in my install, I finally reproduced the bug.
I get back to you asap

**Comment by lgmgeo** [comment]
You failed to indicate that you modified the genes.ENSEMBL.sorted.bed file yourself.
And you did it wrong...
This file needs to be sorted!
You added 2 lines at the start of the file, unsorted:
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/510bc837-9f6f-4eb4-830b-606ad478d9a2)

I develop and maintain AnnotSV for free.
I attach great importance to answering users' questions, even if it takes me a lot of time, so that this tool is useful to as many people as possible. So...
**As already mentioned, please detail your request when reporting a bug:**
**- Give the version of AnnotSV and the command line used**
**- Add/join the input file that allow to reproduce the bug**
**- Give all the information that could have an impact on the bug reported (modifications made in the installation or in the annotation files)**
