### ISSUE TITLE
Mapping of structural variant to intron or coding regions

### ISSUE THREAD

**Issue by priyambial123** [lgmgeo/AnnotSV#243]
Dear Geoffroy Véronique,

I have been using annotsv since its inception. Thank you for the great tool. Could you briefly explain the steps of  how do you find the location of gene overlapping the structural variant. AnnotSV also provides if the structural variant is within the intron of the gene. It would be helpful to understand how these structural variant affect the gene function

Thank you

Priya

**Comment by lgmgeo** [comment]
Hi Priya,

>  Could you briefly explain the steps of how do you find the location of gene overlapping the structural variant.

cf [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf)
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/77433c4c-f624-4369-8e7f-37c43732472d)

>  It would be helpful to understand how these structural variant affect the gene function

I recommend reading the the joint consensus recommendation of ACMG and ClinGen (Riggs et al., 2020)

Best,
Véronique

**Comment by priyambial123** [comment]
Thank you Véronique
