### ISSUE TITLE
Keep AnnotSV_ID consistent with SV_chrom

### ISSUE THREAD

**Issue by xiucz** [lgmgeo/AnnotSV#247]
Hi，
This may not be a common issue, but I often extract the chromosome ID from AnnotSV_ID (25_2_20000000_DEL_1) by parsing it using `split("_")[0]`. Could you please check where the problem might be occurring?

**AnnotSV 3.4.2**
```

AnnotSV -bedtools ~/bedtools-2.30.0/bin/bedtools \
-bcftools ~/bcftools/bcftools-1.12/bin/bcftools \
-annotationMode both -includeCI 0 -overlap 100 -benignAF 0.001 \
-overwrite 1 -genomeBuild GRCh37 -SVinputFile  test.vcf  -outputFile test -outputDir ./
```
![image](https://github.com/user-attachments/assets/3e77013a-e635-4bb3-a54d-2fcd5947e30f)

[test.vcf.txt](https://github.com/user-attachments/files/16347082/test.vcf.txt)

Best,
xiucz

**Comment by lgmgeo** [comment]
Quite strange indeed.
I get back to you asap

**Comment by lgmgeo** [comment]
OK, got it.
It is a stupide glitch if POS (e.g. "1") is contained in CHROM (e.g. "15")

I just added a fix in the patch_AnnotSV branch.
Can you confirm that your bug is fixed?

**Comment by xiucz** [comment]
![image](https://github.com/user-attachments/assets/32bb6ee5-ec9f-447b-aed2-8f621989fd5f)

I simply replaced `AnnotSV-write.tcl` with the one **from the new branch**, and things started to get more complicated...It seems like the SV_chrom column is missing.

**Comment by lgmgeo** [comment]
Ok, I will check that again

**Comment by lgmgeo** [comment]
My bad...
Can you have a new try?

**Comment by xiucz** [comment]
Success is just one step away.  Could you please remove the repeat part?
![image](https://github.com/user-attachments/assets/412b4042-7e6d-4b38-b409-3a31d8a361d5)
Best, 
xiucz

**Comment by lgmgeo** [comment]
Damned... Sorry, I'm out of my lab, I did it too quickly ;o(

Can you have a new try?

**Comment by xiucz** [comment]
I receive `25` again... Could you please try it first? Please see the attachment here.^_^

![image](https://github.com/user-attachments/assets/5b346be9-1281-4f2a-bce7-cd9e079efc87)
 
Best,
xiucz

**Comment by lgmgeo** [comment]
Everything is working well on my side...
Did you copy the file in the patch_AnnotSV branch?

**Comment by xiucz** [comment]
Thank you very much for your work. The issue has been resolved.
