### ISSUE TITLE
frameshift between full and split mode

### ISSUE THREAD

**Issue by methionine23** [lgmgeo/AnnotSV#248]
Hello, 
I found that some CNV calls involving two genes had different result between full vs split mode. Full mode returned NaN, while one of the split call predicted frameshift correctly. Is this behavior by design?  Thank you!

**Comment by methionine23** [comment]
Thanks!  I made an artificial variant and tested it on the web server. The full mode has frameshift filed empty, while split mode predicted yes. I didn't find an explanation in the documentation as I may have missed it. 
https://lbgi.fr/AnnotSV/result?id=qo71GNbvUi
https://lbgi.fr/AnnotSV/result?id=dWCiPEsbcN
Also I run v.3.4.2 using bed file, the split mode returned 2 rows, while the web server only returned one row for split mode. Maybe that is expected?

**Comment by lgmgeo** [comment]
>  The full mode has frameshift filed empty, while split mode predicted yes.

Ok, got it.

In the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf), you can see in the "Annotation columns available in the output file" section:
![image](https://github.com/user-attachments/assets/42c9abb2-e7bb-40f1-a0a0-401904724bbd)
![image](https://github.com/user-attachments/assets/dd2a6d22-83f2-4d1d-bcf3-a7822381caba)

As you can see, the `frameshift` is never filed for the "Full" lines.
Why?
You need to understand the full and split lines.

For each gene, only a single transcript from all transcripts available for this gene is reported in the following
order of preference:
- The transcript selected by the user with the "-txFile" option is reported
- The transcript with the longest overlapped CDS is reported
- If there is no difference in CDS length, the longest overlapped transcript is reported.

To resume, the `frameshift` value depends on the transcript of 1 gene. 

**Full and split lines:**
- Annotation on the “full” length of the SV. Every SV are reported, even those not covering a gene. This type
of annotation gives an estimate of the SV itself.
- Annotation of the SV “split” by gene. This type of annotation gives an opportunity to focus on each gene
overlapped by the SV. Thus, when a SV spans over several genes, the output will contain as many annotations lines as genes covered. This latter annotation is extremely powerful to shorten the identification of mutation implicated in a specific gene.

**Considering the “full” length annotation of one SV, AnnotSV does not report the Gene-based annotation (value
is set to empty), except for scores and percentages where AnnotSV reports the most pathogenic score or the
maximal percentage.**

I hope this helps you understand better,
Best,

Véronique

**Comment by lgmgeo** [comment]
> Also I run v.3.4.2 using bed file, the split mode returned 2 rows, while the web server only returned one row for split mode. Maybe that is expected?

The results are exactly the same between your local run (1 full line + 1 split line) and the web server.
It seems that you have selected the "COMPACT" mode in knotAnnotSV (web server) which only displays full lines.
cf https://github.com/mobidic/knotAnnotSV:
![image](https://github.com/user-attachments/assets/4292cb3e-7240-48af-b44d-eb74709dd12a)

**Comment by methionine23** [comment]
Thank you for the detailed information!
