### ISSUE TITLE
UCSC link failed to open the correct position

### ISSUE THREAD

**Issue by lmanchon** [lgmgeo/AnnotSV#249]
--Hi,

i use AnnotSV v3.2 and in the xlsm file the link to UCSC (AnnotSV ID column) failed, for example the link:

http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr7:30978636-31879265&hgt.out1=submit&highlight=hg38.chr7:30978636-31879265#aaedff%22%20target=%22_blank%22%20rel=%22noopener%20noreferrer%22

failed to open with the correct position and i don't know why.

Do i change some parameter in the config file ?

thank you --

**Comment by lgmgeo** [comment]
Really strange, this link works fine for me:
![image](https://github.com/user-attachments/assets/21672e31-9b49-4ac3-9989-9f035e571128)

This opens the UCSC Genome Browser in the “chr7:30,753,479-32,104,423” window (with “chr7:30,978,636-31,879,265” highlighted in blue).

**Comment by lgmgeo** [comment]
cf https://github.com/mobidic/knotAnnotSV:
![image](https://github.com/user-attachments/assets/5b15405b-076b-4924-ac39-ebd5251da425)

**Comment by lmanchon** [comment]
ok i understand now, 
you are right my target positions (chr7:30,978,636-31,879,265) are highlighted in blue but UCSC shift automatically the positions to chr7:30,753,479-32,104,423 in the banner.

**Comment by lgmgeo** [comment]
Absolutely (zoomed out by 1.5x)

**Comment by lmanchon** [comment]
good; problem is over; thank you;
