### ISSUE TITLE
VCF for false positive deletion and for compund etherozygosity

### ISSUE THREAD

**Issue by paolomaccallini-hub** [lgmgeo/AnnotSV#251]
Hi,

I am unsure about the VCF file for false positive discovery and compound heterozygosity. Can the VCF file generated from the GATK variant calling be inputted?

**Comment by lgmgeo** [comment]
Absolutely, yes.

cf [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf):
![image](https://github.com/user-attachments/assets/65737943-56fd-4129-9e7d-34223c010d49)

**Comment by paolomaccallini-hub** [comment]
Thank you, and congratulations on this tool!

**Comment by lgmgeo** [comment]
> I am using the online version, I added a VCF for compound heterozygosity analysis of 30 variants, but the output (.tsv) does not include the compound_htz(sample) column.

The "compound_htz(_sample_)" column exists by default for each of the samples from the "candidate SNV/indel" file.
e.g. compound_htz(sample1), compound_htz(sample2) ... compound_htz(sample30)

WARNING: sample names must be exactly the same between the SV and SNV/indel VCF files.
