### ISSUE TITLE
Invalid Path Error for Bedtools in AnnotSV 1.1.1

### ISSUE THREAD

**Issue by Jimaz** [lgmgeo/AnnotSV#252]
Hello!

I'm encountering an issue with AnnotSV where it fails to recognize the provided path for the bedtools command, resulting in an "Invalid path of the bedtools command - Exit" error." I've been running AnnotSV without any issues until now, using the same setup.

The bedtools binary exists at the specified path and has executable permissions. I confirmed the path by running bedtools directly from the terminal, which worked as expected.

![annotsv_error](https://github.com/user-attachments/assets/fa983065-eae2-4594-9501-a040fd5c2ab2)

Could you help investigate why AnnotSV isn't recognizing the bedtools path? Any guidance would be appreciated.

Environment:

- AnnotSV Version: 1.1.1
- Bedtools Version: 2.26.0

Thank you so much,

Jaime

**Comment by lgmgeo** [comment]
AnnotSV v1.1.1 was released on May 16, 2018.
It's such an old version...
My advice is to install the latest version (3.4.2)

**Comment by xiucz** [comment]
@lgmgeo 
I'm sorry, may I ask when the 3.4.**3** version is expected to be released?

**Comment by Jimaz** [comment]
Thank you so much!!
