### ISSUE TITLE
'TAD_coordinate' and 'ENCODE_experiment' columns missing in 3.4.2 result

### ISSUE THREAD

**Issue by Stikus** [lgmgeo/AnnotSV#253]
Hello, after update from 3.3.6 to 3.4.2 our output lost `TAD_coordinate` and `ENCODE_experiment` columns.

I haven't found any info about it in [changelog](https://github.com/lgmgeo/AnnotSV/blob/master/changeLog.txt) - that's why I'm asking is this intended.

```
Command: '/soft/AnnotSV-3.4.2/bin/AnnotSV -annotationsDir /ref/AnnotSV/3.4.2 -genomeBuild GRCh37 -SVinputFile /inputs/som_diploidSV.vcf -outputFile /outputs/test_som.annotsv.tsv '.
```
- 3.4.2 columns:

`AnnotSV_ID;SV_chrom;SV_start;SV_end;SV_length;SV_type;Samples_ID;ID;REF;ALT;QUAL;FILTER;INFO;FORMAT;chr19;Annotation_mode;CytoBand;Gene_name;Closest_left;Closest_right;Gene_count;Tx;Tx_version;Tx_start;Tx_end;Overlapped_tx_length;Overlapped_CDS_length;Overlapped_CDS_percent;Frameshift;Exon_count;Location;Location2;Dist_nearest_SS;Nearest_SS_type;Intersect_start;Intersect_end;RE_gene;P_gain_phen;P_gain_hpo;P_gain_source;P_gain_coord;P_loss_phen;P_loss_hpo;P_loss_source;P_loss_coord;P_ins_phen;P_ins_hpo;P_ins_source;P_ins_coord;po_P_gain_phen;po_P_gain_hpo;po_P_gain_source;po_P_gain_coord;po_P_gain_percent;po_P_loss_phen;po_P_loss_hpo;po_P_loss_source;po_P_loss_coord;po_P_loss_percent;P_snvindel_nb;P_snvindel_phen;B_gain_source;B_gain_coord;B_gain_AFmax;B_loss_source;B_loss_coord;B_loss_AFmax;B_ins_source;B_ins_coord;B_ins_AFmax;B_inv_source;B_inv_coord;B_inv_AFmax;po_B_gain_allG_source;po_B_gain_allG_coord;po_B_gain_someG_source;po_B_gain_someG_coord;po_B_loss_allG_source;po_B_loss_allG_coord;po_B_loss_someG_source;po_B_loss_someG_coord;GC_content_left;GC_content_right;Repeat_coord_left;Repeat_type_left;Repeat_coord_right;Repeat_type_right;Gap_left;Gap_right;SegDup_left;SegDup_right;ENCODE_blacklist_left;ENCODE_blacklist_characteristics_left;ENCODE_blacklist_right;ENCODE_blacklist_characteristics_right;ACMG;HI;TS;DDD_HI_percent;ExAC_delZ;ExAC_dupZ;ExAC_cnvZ;ExAC_synZ;ExAC_misZ;GenCC_disease;GenCC_moi;GenCC_classification;GenCC_pmid;NCBI_gene_ID;OMIM_ID;OMIM_phenotype;OMIM_inheritance;OMIM_morbid;OMIM_morbid_candidate;LOEUF_bin;GnomAD_pLI;ExAC_pLI;AnnotSV_ranking_score;AnnotSV_ranking_criteria;ACMG_class`

```
Command: '/soft/AnnotSV-3.3.6/bin/AnnotSV -annotationsDir /ref/AnnotSV/3.3.6 -genomeBuild GRCh37 -SVinputFile /inputs/som_diploidSV.vcf -outputFile /outputs/test_som.annotsv.tsv '.
```
- 3.3.6 columns:

`AnnotSV_ID;SV_chrom;SV_start;SV_end;SV_length;SV_type;Samples_ID;ID;REF;ALT;QUAL;FILTER;INFO;FORMAT;chr19;Annotation_mode;CytoBand;Gene_name;Gene_count;Tx;Tx_start;Tx_end;Overlapped_tx_length;Overlapped_CDS_length;Overlapped_CDS_percent;Frameshift;Exon_count;Location;Location2;Dist_nearest_SS;Nearest_SS_type;Intersect_start;Intersect_end;RE_gene;P_gain_phen;P_gain_hpo;P_gain_source;P_gain_coord;P_loss_phen;P_loss_hpo;P_loss_source;P_loss_coord;P_ins_phen;P_ins_hpo;P_ins_source;P_ins_coord;po_P_gain_phen;po_P_gain_hpo;po_P_gain_source;po_P_gain_coord;po_P_gain_percent;po_P_loss_phen;po_P_loss_hpo;po_P_loss_source;po_P_loss_coord;po_P_loss_percent;P_snvindel_nb;P_snvindel_phen;B_gain_source;B_gain_coord;B_gain_AFmax;B_loss_source;B_loss_coord;B_loss_AFmax;B_ins_source;B_ins_coord;B_ins_AFmax;B_inv_source;B_inv_coord;B_inv_AFmax;po_B_gain_allG_source;po_B_gain_allG_coord;po_B_gain_someG_source;po_B_gain_someG_coord;po_B_loss_allG_source;po_B_loss_allG_coord;po_B_loss_someG_source;po_B_loss_someG_coord;TAD_coordinate;ENCODE_experiment;GC_content_left;GC_content_right;Repeat_coord_left;Repeat_type_left;Repeat_coord_right;Repeat_type_right;Gap_left;Gap_right;SegDup_left;SegDup_right;ENCODE_blacklist_left;ENCODE_blacklist_characteristics_left;ENCODE_blacklist_right;ENCODE_blacklist_characteristics_right;ACMG;HI;TS;DDD_HI_percent;ExAC_delZ;ExAC_dupZ;ExAC_cnvZ;ExAC_synZ;ExAC_misZ;GenCC_disease;GenCC_moi;GenCC_classification;GenCC_pmid;OMIM_ID;OMIM_phenotype;OMIM_inheritance;OMIM_morbid;OMIM_morbid_candidate;LOEUF_bin;GnomAD_pLI;ExAC_pLI;AnnotSV_ranking_score;AnnotSV_ranking_criteria;ACMG_class`

Maybe it is result of Exomiser annotation 2202 -> 2402 update.

**Comment by lgmgeo** [comment]
You are right, nothing in the changelog. There has been no new modification in the AnnotSV code.
The information is located in the README:
![image](https://github.com/user-attachments/assets/14c0c7bc-dfff-4813-a77b-d3c0a0d1e322)


Actually, TAD annotations are no longer distributed by AnnotSV because each user needs different ENCODE experiments (with its good “Analysis” / ”Genome assembly”).

You need to download the ENCODE data of interest for your own usage. 
You can have more information on how to do in the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf), section "TAD boundaries annotations".

However, an easy thing to do if you are satisfied with the TAD v3.3.6 annotations is to copy the files from the v3.3.6 install into the v3.4.2 install:
“$ANNOTSV/share/AnnotSV/Annotations_Human/FtIncludedInSV/TAD/GRCh37” 
and/or
“$ANNOTSV/share/AnnotSV/Annotations_Human/ FtIncludedInSV/TAD/GRCh38” directories.


> Maybe it is result of Exomiser annotation 2202 -> 2402 update.

No link.


Best,
Véronique

**Comment by Stikus** [comment]
Thank you for fast answer, missed this part of README. We'll look into it.
