### ISSUE TITLE
v3.0.1和v3.4.1注释出的AnnotSV_ID列为啥不一致

### ISSUE THREAD

**Issue by hulicxy** [lgmgeo/AnnotSV#258]
v3.0.1和v3.4.1注释出的AnnotSV_ID列为啥不一致，例如：v3.0.1是1_62939617_75740744_DEL_1，v3.4.1是1_62939618_75740744_DEL_1，最新版的起始位置比旧版大一位数
cmd：bin/AnnotSV -svtBEDcol 4 -outputDir {output_dir} -outputFile {result_file_name} -SVinputFile {cnv_bed_file} -txFile {gene_tx}
谢谢！

**Comment by lgmgeo** [comment]
Sorry, your message is unreadable for me.
Can't help.
