### ISSUE TITLE
promblem in web serve of annotsv

### ISSUE THREAD

**Issue by lpsyy** [lgmgeo/AnnotSV#259]
[GA00_AO2_BB1_01_annotsv_new.bed.zip](https://github.com/user-attachments/files/17144001/GA00_AO2_BB1_01_annotsv_new.bed.zip)
@lgmgeo Hello, I am trying to use the web version of annotsv, and I appreciate the efficiency of this annotation tool. I am attempting to upload a merged structural variant file of a family to the server. My original file is in VCF format, which I merged using SURVIVOR from individual VCF files of family members. The initial upload prompted a warning about potential structural variants larger than 10M in my VCF file. To address this, I converted the VCF file to BED format using convert2bed from bedops. However, after the conversion, the END column displayed the same number of bases as the START column, likely because the END information was in the INFO field and couldn't be extracted during conversion. I then modified the post-conversion BED file according to the format specified by annotsv for bed input files. Unfortunately, upon re-uploading, I received an error message indicating invalid information in my file. I am seeking advice from the author and have attached my BED file for reference. Thank you in advance for your response!
<img width="1438" alt="Snipaste_2024-09-26_14-33-31" src="https://github.com/user-attachments/assets/f557a173-ecb2-4f90-8ced-ecb6a5b56e54">
<img width="1449" alt="Snipaste_2024-09-26_14-42-09" src="https://github.com/user-attachments/assets/2ad45b7a-d435-4bfd-9dc0-4d1c8194e9a4">

**Comment by lpsyy** [comment]
Thank you for your reply. After filtering out the rows with a higher number of bases in START than in END from the bed file, I was able to run annotsv on the web version. However, I now have new questions about the False positive deletion discovery options and Compound heterozygosity analysis options. What type of VCF file should I upload? Currently, I have a VCF file from joint calling of this family. Can I use that? Are there any restrictions on file size for these two options? Looking forward to your reply! @lgmgeo

**Comment by lgmgeo** [comment]
Sorry for the delay, I'm out of my office until November 29th.

Yes, you can use your SNV/indel VCF file. Be careful, the sample names should be exactly the same between this VCF and the SV VCF (cf [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf))

Same restriction file size (< 10 Mb)

**Comment by lpsyy** [comment]
Thank you for your reply. I appreciate your help in answering my questions. Wishing you all the best!
