### ISSUE TITLE
AnnotSV 2.4 Critical Bug (with GRCh38)

### ISSUE THREAD

**Issue by lgmgeo** [lgmgeo/AnnotSV#26]
Dear AnnotSV users,

A critical bug has been identified when using AnnotSV 2.4 only with the GRCh38 genome Build. This impacts the DGV dataset and the ranking.

I am actively working on it and a new release should be delivered as soon as possible.

Sorry for any inconvenience this critical bug might have caused, 

Best regards,

Véronique

**Comment by LiviaMoura** [comment]
Thank you, once again =)

**Comment by lgmgeo** [comment]
Thanks to you for pointing out this bug :o)

**Comment by lgmgeo** [comment]
Dear AnnotSV users,

The AnnotSV 2.5 source code is now downloadable on GitHub.
Annotations are then downloaded during the installation with the Makefile.

If you are using AnnotSV 2.4, we urge you to update both the source code and the annotations to the 2.5 version.

Sorry for any inconvenience this critical bug has been caused, 

Best regards,

Véronique

**Comment by Stikus** [comment]
Hello @lgmgeo . Is this bug fixed and should issue be closed?

Btw, according to https://github.com/lgmgeo/AnnotSV/blob/master/etc/AnnotSV/configfile#L56 and my tests changelog of 2.5.2 is incorrect:
```
overlapped tx length            *
overlapped CDS length		*
```
```
		The "tx length" column has been renamed "tx length overlapped"
	  	The "CDS length" column has been renamed "CDS length overlapped" 
```
Fix word order please.

**Comment by lgmgeo** [comment]
Yes it is. I'm going to close the issue.

Sorry for the typo in the changeLog.txt file. 
Correct column names are: "overlapped tx length" and "overlapped CDS length"
