### ISSUE TITLE
Information about Merged VCFs samples run from trios 

### ISSUE THREAD

**Issue by poddarharsh15** [lgmgeo/AnnotSV#260]
Hi @lgmgeo 
I am running AnnotSV on several samples (6 samples) which includes two trios from patients. Does AnnotSV support prioritizing structural variants (SVs) in trio samples, or is there a recommended approach for handling this use case? Thank you for your help!

**Comment by lgmgeo** [comment]
Hi @poddarharsh15,

Sorry for the dealy, I'm out of my office until November 29th.

Currently, AnnotSV do not support trio samples.
I would like to add a "barcode" feature, representing the presence/absence of SV (with homozygote/heterozygote status), to search for recurrence between families or group of individuals. cf https://github.com/lgmgeo/AnnotSV/issues/205
But not in a near future.

Best regards,
Véronique

**Comment by poddarharsh15** [comment]
Hi @lgmgeo,

Thank you for your response, and I hope you're enjoying your time away from the office.

I have a question regarding the inheritance information in AnnotSV. I will be working with a VCF file that has been merged from 55 samples (not trios, just probands/children). Is it possible to obtain mutation inheritance information (such as whether the mutations are Mendelian or de novo) in the TSV output files from AnnotSV?

Thank you for your assistance!

Best regards,
Harsh Poddar

**Comment by lgmgeo** [comment]
> Is it possible to obtain mutation inheritance information (such as whether the mutations are Mendelian or de novo) in the TSV output files from AnnotSV?

Sorry, such an option is not provided in AnnotSV
