### ISSUE TITLE
Wrong start-end interval annotation

### ISSUE THREAD

**Issue by abrusell** [lgmgeo/AnnotSV#265]
Hi,
in my last annotation with AnnotSV v.3.4 using GRCh38, I've noticed the software is reporting wrong start and end coordinates (and consequent annotation) for the SVs; they are different from the vcf file given as input
i.e., vcf structural variant:
`chr16   1457407 DEL00023881     ATGCTCAGAGACACGCGTGACGCGGCCCTTCCTGGAGACCAGAAGGACCGATGCTCAGAGACACGCGTGACGCGGCCCTTCCTGGAGACCAGAAGGACCGG   A       660     PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv1.1.6;END=1457508;PE=0;MAPQ=0;CT=3to5;CIPOS=-113,113;CIEND=-113,113;SRMAPQ=60;INSLEN=0;HOMLEN=161;SR=11;SRQ=0.996076;CONSENSUS=AAACTTAGCCAGGCGTGGTGGCGGGCACCTATAATCCCAGCTACTCGGGATGCTGAGGCAGGAGAATTGCTTGAACCTGGGAGGTGGAGGCTGCAGTGAGCTGAGATTGT.....;CE=1.95757      GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV 1/1:-36,-1.80618,0:18:PASS:550:236:353:1:0:0:0:6` 
is annotated in AnnotSV tsv output as:
<img width="1306" alt="Screenshot 2024-12-11 alle 15 32 36" src="https://github.com/user-attachments/assets/c2b0133a-c118-40ea-84ce-866385113316" />
with start-end coordinates "16:1457294-1457621" instead of "16:1457407-1457508". The SV_length is right (100), but the interval between AnnotSV coordinates is longer (from 1457294 to 1457621: 327 bp). Thus also annotations are wrong; in fact, it is reported as a frameshift DEL (from intron8 to exon9), instead of being reported as intronic. This happens with many other variants.
Why is it so?
Thanks

**Comment by lgmgeo** [comment]
Please, see https://github.com/lgmgeo/AnnotSV/issues/217

**Comment by abrusell** [comment]
I apologize for missing those issues
Thanks

**Comment by awgymer** [comment]
@lgmgeo sorry to revive an old issue but I assume that the expansion is used for annotation? If so it would seem like an expected use-case that one would want to annotate considering the CI intervals but retain the real/original POS/END in the output for consistency with the input VCF to allow accurate matching downstream? 

Would it be possible to add the original POS/END into the (tsv) output, either keeping the CI-adjusted values in their own columns, or simply adding a column to indicate whether annotation considered the CI intervals.

**Comment by lgmgeo** [comment]
You can set the `-includeCI` option to 0.

<img width="1461" height="52" alt="Image" src="https://github.com/user-attachments/assets/e25495ba-055a-4090-81d9-b28833edd940" />

**Comment by awgymer** [comment]
But this would then only annotate based on the standard POS/END? The aim here is to annotate with the widest range (CIPOS min -> CIEND max) as this option does, but to retain the "real"/original coordinates so that the output TSV/VCF correctly matches the POS/END of the input.

**Comment by lgmgeo** [comment]
I'm not entirely convinced. I think we should return the coordinates that were actually used for the annotation. Returning the original coordinates when they were not the ones used to perform the annotation doesn't really make sense to me, as it creates a mismatch between the reported coordinates and the annotation itself.

**Comment by awgymer** [comment]
That is one reason why I say it could be possible to return both. The issue right now is that there is a complete loss of that original information and it is impossible to directly map the variants based on coordinates anymore.

**Comment by lgmgeo** [comment]
The original variant ID is already reported, which provides traceability back to the input record if needed.
