### ISSUE TITLE
Annotation for other genome

### ISSUE THREAD

**Issue by ytguojian** [lgmgeo/AnnotSV#3]
Hi，
I have installed AnnotSV to annotate my own SV data. My study is about peach. So can this tool be used for peach? How could I build the genome? Because the default is human genome.
Cheers,
Jian

**Comment by lgmgeo** [comment]
Hi Jian,
Sorry for the late reply.
If sequence and annotation peach data are available for download in the UCSC Genome Browser
(https://hgdownload.soe.ucsc.edu/downloads.html), so yes AnnotSV could be used to annotate your own data.
If you are interested, please contact me directly by mail (veronique.geoffroy@inserm.fr)
Best regards,
Véronique
