### ISSUE TITLE
Failed to download the data source from ENSEMBL (hg38) 

### ISSUE THREAD

**Issue by daaaaande** [lgmgeo/AnnotSV#30]
Dear Igmgeo,
i tried downloading hg38 annotations, following things popped up:
downloading this:
wget ftp://ftp.ensembl.org/pub/current_gtf/homo_sapiens/Homo_sapiens.GRCh38.100.gtf.gz
did not work
- what worked instead was manaual download from ftp://ftp.ensembl.org/pub/current_gtf/homo_sapiens (100->102) . then renamed the file.

**Comment by lgmgeo** [comment]
Hi,
You did well by downloading the latest file version. 
As it was unclear for you, I will update the next README.
Best,
Véronique
