### ISSUE TITLE
Add HPO criteria and IDs to annotations

### ISSUE THREAD

**Issue by kalon33** [lgmgeo/AnnotSV#31]
Would it be possible to add HPO criteria and their IDs to annotations?

Best regards.

**Comment by lgmgeo** [comment]
Currently, HPO IDs are given by the user to describe the phenotype of the individual (-hpo options)

If I well understood, you want to add HPO IDs to annotation. Which annotations?
(if you think to pathogenic SV from public databases, good news, it will be provided in the next version)
And which criteria do you want to be added?
Can you give an example?

**Comment by lgmgeo** [comment]
Any news to detail your request?
