### ISSUE TITLE
hg38 annotation fail

### ISSUE THREAD

**Issue by daaaaande** [lgmgeo/AnnotSV#32]
dear Igmeo, many thanks for creating AnnotSV!

i was trying to install AnnotSV and annotate SV with hg38 data, however, the following message came up on first run:
WARNING: X, format (nb columns) is not good 89 vs 0 columns
WARNING: Reading Annotation file 20201208_gnomAD.LOEUF.pLI.annotations.tsv and X is seen multiple times.
WARNING: X, format (nb columns) is not good 89 vs 0 columns
...
WARNING: Y, format (nb columns) is not good 89 vs 0 columns
WARNING: Reading Annotation file 20201208_gnomAD.LOEUF.pLI.annotations.tsv and Y is seen multiple times.

...listing of the annotations to realized (December 09 2020 - 13:17)
	...Genes annotation
	(with share/AnnotSV/Annotations_Human/Genes/GRCh38/genes.RefSeq.sorted.bed)
	...Genes-based annotations
		...20201204_ClinGenAnnotations.tsv.gz
		(1129 gene identifiers and 2 annotations columns: HI_CGscore, TriS_CGscore)
		...20201204_HI.tsv.gz
		(19124 gene identifiers and 1 annotations columns: HI_DDDpercent)
		...20201208_ExAC.CNV-Zscore.annotations.tsv.gz
		(15673 gene identifiers and 3 annotations columns: delZ_ExAC, dupZ_ExAC, cnvZ_ExAC)
		...20201208_GeneIntolerance-Zscore.annotations.tsv.gz
		(18241 gene identifiers and 2 annotations columns: synZ_ExAC, misZ_ExAC)
		...20201204_OMIM-1-annotations.tsv.gz
		(15004 gene identifiers and 1 annotations columns: Mim Number)
		...20201204_OMIM-2-annotations.tsv.gz
		(15004 gene identifiers and 2 annotations columns: Phenotypes, Inheritance)
		...20201204_morbidGenes.tsv.gz
		(11845 gene identifiers and 1 annotations columns: morbidGenes)
		...20201204_morbidGenesCandidates.tsv.gz
		(3207 gene identifiers and 1 annotations columns: morbidGenesCandidates)
		...20201208_gnomAD.LOEUF.pLI.annotations.tsv
		(24 gene identifiers and -1 annotations columns: )
	...Annotations with features overlapping the SV
		...DGV Gold Standard frequency annotation
		...1000g events annotation
	...Annotations with features overlapped with the SV
		...Promoters annotation
	...Breakpoints annotations
		...Repeat annotation
		...Gap annotation
		...Segmental duplication annotation
		...ENCODE blacklist annotation

...annotation in progress (December 09 2020 - 13:17)
bad count "-1": must be integer >= 0
    while executing
"lrepeat $nbColumns($F) """
    (procedure "OrganizeAnnotation" line 843)
    invoked from within
"OrganizeAnnotation"
    (file "bin/AnnotSV" line 277)

- is my annotation file not good?
- why is the organization failing?
im trying to run it on a linux computer if that helps, do you need more info on that?

Thanks for your efforts in advance,
daaaaande

**Comment by lgmgeo** [comment]
Hi daaaaande,

Can you tell me which AnnotSV version you used?
And if you replace any annotation file?
What was your command line?

FYI, AnnotSV 3.0 is expected very soon... with updated annotation ;o)

Véronique

**Comment by daaaaande** [comment]
Hi! thanks for the quick reply!

version:
AnnotSV 2.5.2
Tcl/Tk version: 8.6

- downloaded all annotations (hg38, and the genome-unspecific ones aswell) manually due to the automatic process failing multiple times. this might be the biggest source of failure here (=me) :(

**Comment by lgmgeo** [comment]
...it is really difficult for me to help if your installation is not standard.
I need to reproduce what you did exactly and then to test.
Can you email me all the command you manually run?
veronique.geoffroy@inserm.fr
