### ISSUE TITLE
Frequency columns in annotation

### ISSUE THREAD

**Issue by Stikus** [lgmgeo/AnnotSV#33]
Hello, thanks for tool update.
We are using filtration of `AnnotSV` output in our pipelines (based on [annotsv_filter.cwl](https://github.com/genome/analysis-workflows/blob/master/definitions/tools/annotsv_filter.cwl)) and now we cannot use it's full functionality due to loss of various frequency columns.
What do you think - we should ask [analysis-workflows](https://github.com/genome/analysis-workflows) team about new filtration, or you should reintroduce some of these columns or any other ideas?

**Comment by lgmgeo** [comment]
Hi, 
This new release was designed to be the foundation of an improved structural variation annotation platform.
For example, benign SV are selected from different sources based on their frequencies and annotation, and already merged (to avoid multiple annotation columns). 
So I wouldn't be reintroducing old columns. And yes, it would be better to ask  analysis-workflows team about new filtration.
Sorry for any inconvenience that may have been caused,
Véronique

**Comment by Stikus** [comment]
Ok, thank you for answer. We already asked analysis-workflows team. Closing for now.
