### ISSUE TITLE
Problem with -annotationMode split

### ISSUE THREAD

**Issue by RSchwieger** [lgmgeo/AnnotSV#36]
Hello, I tried to run AnnotSV with the option -annotationMode split for the testcase in the repository. However, I got an error message as below. Do you have an idea what could cause this?

$ANNOTSV/bin/AnnotSV -annotationMode split -SVinputFile test.bed -outputFile ./test.annotated.tsv -svtBEDcol 4

Error message:

...annotation in progress (January 19 2021 - 10:19)  

...writing of ./test.annotated.tsv (January 19 2021 - 10:19) 
can't read "notSelected": no such variable
     while executing
 "if {$notSelected} {continue} "
     (procedure "OrganizeAnnotation" line 1198)
     invoked from within 
"OrganizeAnnotation"
     (file "/usr/src/app/AnnotSV/bin/AnnotSV" line 271)
--

**Comment by lgmgeo** [comment]
Hi,
Thanks for the report.
I just added a bug fix (v3.0.4). Everything should be in order now.
Sorry for any inconvenience that may have been caused.
Véronique
