### ISSUE TITLE
Bug with the "candidateGenesFiltering" option

### ISSUE THREAD

**Issue by Mkddb** [lgmgeo/AnnotSV#39]
Hi Veronique

First of all, Thanks a lot for creating such wonderful tool. It's really helpful and time-saver in annonation process.
I have a query regarding annotation mode output.

I am annotating a VCF file in default Annotation mode (values : both as default) 

Most of the SVs have two entries as "Full" and "Split".
but, some SVs only have "split" annotated mode entries.

Can you please check if there's some bug or i am missing some attribute in Annotation ?

Thanks in advance

**Comment by lgmgeo** [comment]
Hi,

Great, happy users make me happy ;o)

Your feedback could be the report of a new bug... 
Which AnnotSV version are you using? Are you running AnnotSV locally or on the web server?
Please, can you provide me the coordinates of such a SV with only a split annotation line?

Best regards,
Véronique

**Comment by Mkddb** [comment]
Yes Sure,

Thanks a lot for your prompt response.

I am using the most recent version v3.0.4 locally on my workstation.

Part of such "split" entries is here.

AnnotSV_ID	                      SV_chrom	SV_start	          SV_end	         SV_length	SV_type	Annotation_mode	Gene_name
X_6677291_7597370_DEL_1  	X	 6677291	         7597370	         -920079	           DEL	split	                         STS
1_161697868_161830548_DEL_1	1	161697868	161830548	-132640	           DEL	split	                         ATF6
1_171100129_171101954_DEL_1	1	171100129	171101954	-1825	           DEL	split	                         FMO3
9_12954447_13114176_DEL_1	9	12954447	13114176	-159729	           DEL	split	                         MPDZ
X_97533062_97589981_DEL_1	X	97533062	97589981	-56919	           DEL	split	                         DIAPH2
1_74518835_74519569_DEL_1	1	74518835	74519569	-734	                   DEL	split	                         TNNI3K
1_172416440_172422041_DEL_1	1	172416440	172422041	-5601	           DEL	split	                         C1orf105
15_24870556_24872357_DEL_1	15	24870556	24872357	-1801	           DEL	split	                         SNHG14
15_55413644_55421874_DEL_1	15	55413644	55421874	-8230	           DEL	split	                         DNAAF4

Since i am working around Deletions, Only DEL SV type is there in this list.

**Comment by lgmgeo** [comment]
Really strange... I can't reproduce what you said.
Here are the results of your first DEL example:
[2Q1mEaZ5Pd](https://lbgi.fr/AnnotSV/display?id=2Q1mEaZ5Pd)
The full line is present.

Can you tell me which command line you used exactly?

**Comment by lgmgeo** [comment]
Did you set the -candidateGenesFiltering option to "yes"?

**Comment by Mkddb** [comment]
Yes Veronique,

I am providing a candidategenefile and the candidateGenesFiltering option to yes. 
But, surprisingly i am getting Both "Full and split" entries for most of the variants, except  few as shared above.

Full command line used was 
$ANNOTSV/bin/AnnotSV -SVinputfile Manta_merged.vcf -SVinputInfo 1 -outputFile Manta_merged_annotatedbothmode.tsv -genomeBuild GRCh38 -REreport yes -candidateGenesFile full_gene_list.txt -candidateGenesFiltering yes

candidate gene file contains OMIM genes list fetched from Clinvar.

**Comment by lgmgeo** [comment]
Interesting!
You pointed out a bug with the  `candidateGenesFiltering` option. Only `split` lines should be reported in the output.
I will come back to you asap to fix that.

**Comment by lgmgeo** [comment]
Hi Mkddb,

Can you provide me the coordinates of such SV with full + split annotation lines?

Thanks,
Véronique

**Comment by lgmgeo** [comment]
In AnnotSV 3.0.4, the `candidateGenesFiltering` option selects now the "full" and "split" annotations overlapping a gene from the "candidateGenesFile"
My apologies, I haven't changed the documentation. I'm going to fix that.

But I can't understand why some of your SV only have "split" annotated lines.

Can you please run a small part of your data on the web server? And then send me the job ID by email (veronique.geoffroy@inserm.fr). So I could have a look on it?

**Comment by lgmgeo** [comment]
Got it!

**Comment by lgmgeo** [comment]
Hi Mkddb,

- **`candidateGenesFiltering` option:**
In AnnotSV 3.0 and higher, the `candidateGenesFiltering` option now selects the "full" and "split" annotations overlapping a gene from the "candidateGenesFile". Documentation is now updated.
- I just added a bug fix regarding this option (v3.0.5) to correctly select the full annotation lines

Please, let me know if everything is working fine on your side with v3.0.5

Véronique

**Comment by Mkddb** [comment]
Great,
I will check with the updated version and inform yor on the findings.

**Comment by Mkddb** [comment]
Hi Veronique

All the entries in VCF file are correct. Now, i can see both the "Full" and "Split" row entries, along with the CandidateGene filter applied. I tried with multiple VCFs and everything is working fine. Actually it makes more sense for the downstream reporting, to know both the Full and split annotations, even if one want to prioritize SVs based on candidate gene list.

Thanks a lot for the quick resolution. That's great.
Kind regards.

**Comment by lgmgeo** [comment]
Perfect! Thanks very much for the report!
