### ISSUE TITLE
Suggestion for improvement: add options for user to define path to Annotation files

### ISSUE THREAD

**Issue by zhouyangyu** [lgmgeo/AnnotSV#4]
In order for AnnotSV to work in a docker containers, users need to download source code and annotation files(1000g etc.) inside the container. Because annotation files are quite big, the huge size of the image makes code improvement cycle slow and difficult.

One solution to this is allow users to download annotation file once, and pass the directory to AnnotSV at run time. I added an option `-annotationfolder` in my folk (https://github.com/zhouyangyu/AnnotSV/commit/9389022fe9c743509f884c2ec0bcc02646aa27bf). I wish you could also add this options in your repo.

Cheers,
Joe

**Comment by lgmgeo** [comment]
Thank you Joe,
I will be done in next release,
Best,
Véronique

**Comment by lgmgeo** [comment]
Hi Joe,
The annotations directory can now be passed to AnnotSV at run time through the `-annotationsDir` option. 
Thanks again for your really interesting suggestion,
Véronique
