### ISSUE TITLE
Missing promotor annotations when running with "-tx ENSEMBL"

### ISSUE THREAD

**Issue by bartcharbon** [lgmgeo/AnnotSV#42]
Hi,

We have AnnotSV version 2.5 running and I'm trying to run the following command:
`/bin/AnnotSV -SVinputFile './input.vcf' -outputFile './output/annotSV.tsv' -tx ENSEMBL -typeOfAnnotation split -overwrite yes -hpo HP:0001234 > ./output/AnnotSV.log`

```
couldn't open "/share/AnnotSV/Annotations_Human/FtIncludedInSV/Promoter/GRCh37/promoter.500bp.ENSEMBL.sorted.bed.tmp": read-only file system
    while executing
"open $fichier a"
    (procedure "WriteTextInFile" line 2)
    invoked from within
"WriteTextInFile [join $L_allProm "\n"] $promoterFormatted.tmp"
    (procedure "checkPromoterFile" line 49)
    invoked from within
"checkPromoterFile"
    (file "/bin/AnnotSV" line 216)
```
The message seems to indicate a problem with the file system, however I assume the tool won't be writing in the annotation resources, and more important; it works fine if "-tx" is set to "RefSeq"

I noticed this file in the resources:
`/share/AnnotSV/Annotations_Human/FtIncludedInSV/Promoter/GRCh37/promoter.500bp.ENST.sorted.bed`
Where the filename contains "ENST" instead of "ENSEMBL" (I assume the ".tmp" file is derived from this one?).
I tried running with "ENST" as value for "-tx" but it is not an allowed value.

Is this a bug, or a problem at our end?

**Comment by lgmgeo** [comment]
Hi, 

Please just rename the /share/AnnotSV/Annotations_Human/FtIncludedInSV/Promoter/GRCh37/promoter.500bp.ENST.sorted.bed
to /share/AnnotSV/Annotations_Human/FtIncludedInSV/Promoter/GRCh37/promoter.500bp.ENSEMBL.sorted.bed
It should work.

Best,
Véronique

**Comment by bartcharbon** [comment]
Thanks for your quick reply!

I'll probably try moving to the latest version soon.
