### ISSUE TITLE
Can I turn off the "pathogenic/benign SV annotation" mode?

### ISSUE THREAD

**Issue by fjmuzengyiheng** [lgmgeo/AnnotSV#45]
Hi, THANKS a lot for providing this great tool for SV annotation.

The latest version (December 19, 2020: AnnotSV 3.0 is alive!) updated:
- Merge pathogenic SV annotation (from multiple sources)
- Merge benign SV annotation (from multiple sources)

and _Remove previous annotation columns from DDD, DGV, gnomAD, 1000g and IMH_

Allele Frequency seems to be a good filter item, but it can't be found now. (sad)

**Comment by lgmgeo** [comment]
Hi fjmuzengyiheng,

In version lower than v3.0, AnnotSV was reporting benign genomic regions **partially overlapping** the SV to annotate (>70%).
Now that I have a better understanding of the ACMG/ClinGen guidelines, I really believe that this criteria was not good enough to be used to filter SV.
The idea of AnnotSV 3.0 was to stick to the new ACMG/ClinGen criteria (based in part on benign/pathogenic SV). AnnotSV searches for benign genomic regions **completely overlapping** the SV to annotate. 

The "frequencies" from DDD, DGV, gnomAD, 1000g... are no longer reported with AnnotSV 3.0.
It's basically because the output was getting bigger and bigger (with the SV sources increase).

Actually, in v3.0, the frequencies has been used to create the benign/pathogenic SV data sources in AnnotSV.
For example, benign SV have been merged in AnnotSV from gnomAD, ClinVar, ClinGen, DGV, DDD, 1000g and IMH. The benign SV extraction method from each source is described in the README. As an example, putatively benign variants were selected from gnomAD i) if at least one population allele frequency > 1% OR ii) if the homozygous individuals count > 5.

So if you are interested in filtering SV from the frequencies, this is no longer possible...
The idea is to directly filter your SV with the “AnnotSV_ranking_score" and "ACMG_class" values (e.g. you can filter out the SV when ACMG_class = "1").

Best,
Véronique

**Comment by fjmuzengyiheng** [comment]
Thank you so much for explaining the detail to me. 
Now I understand the efforts you update AnnotSV to alive version 3.0.
I decide to use 3.0 for my pipeline. 
Thank you again for this outstanding tool.

**Comment by lgmgeo** [comment]
Happy users make me happy ;o)

**Comment by npoojitha415-commits** [comment]
> Hi fjmuzengyiheng,
> 
> In versions lower than v3.0, AnnotSV was reporting benign genomic regions **partially overlapping** the SV to annotate (>70%). Now that I have a better understanding of the ACMG/ClinGen guidelines, I really believe that this criterion was not good enough to be used to filter out SV. The idea of AnnotSV 3.0 was to stick to the new ACMG/ClinGen criteria (based in part on benign/pathogenic SV). AnnotSV searches for benign genomic regions **completely overlapping** the SV to annotate.
> 
> The "frequencies" from DDD, DGV, gnomAD, 1000g... are no longer reported with AnnotSV 3.0. It's basically because the output was getting bigger and bigger (with the SV sources increase).
> 
> Actually, in v3.0, the frequencies has been used to create the benign/pathogenic SV data sources in AnnotSV. For example, benign SV have been merged in AnnotSV from gnomAD, ClinVar, ClinGen, DGV, DDD, 1000g and IMH. The benign SV extraction method from each source is described in the README. As an example, putatively benign variants were selected from gnomAD i) if at least one population allele frequency > 1% OR ii) if the homozygous individuals count > 5.
> 
> So if you are interested in filtering SV from the frequencies, this is no longer possible... The idea is to directly filter your SV with the “AnnotSV_ranking_score" and "ACMG_class" values (e.g. you can filter out the SV when ACMG_class = "1").
> 
> Best, Véronique



> Hi fjmuzengyiheng,
> 
> In versions lower than v3.0, AnnotSV was reporting benign genomic regions **partially overlapping** the SV to annotate (>70%). Now that I have a better understanding of the ACMG/ClinGen guidelines, I really believe that this criterion was not good enough to be used to filter out SV. The idea of AnnotSV 3.0 was to stick to the new ACMG/ClinGen criteria (based in part on benign/pathogenic SV). AnnotSV searches for benign genomic regions **completely overlapping** the SV to annotate.
> 
> The "frequencies" from DDD, DGV, gnomAD, 1000g... are no longer reported with AnnotSV 3.0. It's basically because the output was getting bigger and bigger (with the SV sources increase).
> 
> Actually, in v3.0, the frequencies has been used to create the benign/pathogenic SV data sources in AnnotSV. For example, benign SV have been merged in AnnotSV from gnomAD, ClinVar, ClinGen, DGV, DDD, 1000g and IMH. The benign SV extraction method from each source is described in the README. As an example, putatively benign variants were selected from gnomAD i) if at least one population allele frequency > 1% OR ii) if the homozygous individuals count > 5.
> 
> So if you are interested in filtering SV from the frequencies, this is no longer possible... The idea is to directly filter your SV with the “AnnotSV_ranking_score" and "ACMG_class" values (e.g. you can filter out the SV when ACMG_class = "1").
> 
> Best, Véronique

**Comment by npoojitha415-commits** [comment]
Hi, 
I am using AnnotSV version 3.5.8, It reports some allele frequencies like "B_loss_AF_max, B_gain_AF_max, B_ins_AF_max, and B_inv_AF_max. what do these represent? 
If AnnotSV is already using the allele frequency while calculating the score, anything that is labelled as pathogenic or likely pathogenic i.e., score > 0.98 should have allele frequencies less than 1% in any given database as per my understand. However, some of these SVs seem to have much higher allele frequencies in gnomAD despite being labelled as ACMG 4 or 5 and having AnnotSv ranking score > 0.98.

**Comment by lgmgeo** [comment]
> "B_loss_AF_max, B_gain_AF_max, B_ins_AF_max, and B_inv_AF_max. 
what do these represent?

_cf_ https://bigest-icube.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf

> If AnnotSV is already using the allele frequency while calculating the score, anything that is labelled as pathogenic or likely pathogenic i.e., score > 0.98 should have allele frequencies less than 1% in any given database as per my understand. However, some of these SVs seem to have much higher allele frequencies in gnomAD despite being labelled as ACMG 4 or 5 and having AnnotSv ranking score > 0.98.

The simplest thing would be to show me an example of SV classified as pathogenic that you do not understand.

**Comment by npoojitha415-commits** [comment]
> The simplest thing would be to show me an example of SV classified as pathogenic that you do not understand.
[gnomad](https://gnomad.broadinstitute.org/region/1-108190703-108193180?dataset=gnomad_sv_r4)

[annot_sv.xlsx](https://github.com/user-attachments/files/29968525/annot_sv.xlsx)

The SV in the excel sheet has AnnotSV ranking score of 1 and ACMG=5; however, this region completely falls in the intronic region in gnomAD and has a very high allele frequency inluding many homozygotes, to be considered pathogenic.

**Comment by lgmgeo** [comment]
Here is the important annotations from your example (to understand the scoring):

<img width="860" height="45" alt="Image" src="https://github.com/user-attachments/assets/2e79bf1c-e390-4e9c-8494-96e2b81a6042" />

The comprehensive and detailed scoring guidelines are available in the [Scoring_Criteria_AnnotSV](https://github.com/lgmgeo/AnnotSV/blob/master/Scoring_Criteria_AnnotSV_v3.4.xlsx) file (see Table1 for your DEL)
- 2C-1 (SLC25A24, +0.90)
Overlap with known pathogenic Loss SV and coding sequence is involved (please look at the following columns: HI, OMIM_morbid, Location2, Overlapped_CDS_length) 
=> Your DEL overlaps a morbid OMIM gene: https://omim.org/entry/608744
- 5G (SLC25A24, +0.10)
5G. Inheritance information is unavailable or uninformative. The patient phenotype is nonspecific, but is consistent with what has been described in similar cases (PhenoGenius_specificity = "B" OR Exomiser_gene_pheno_score > 0.5). (PhenoGenius_specificity, Exomiser_gene_pheno_score, RE_gene)
=> Exomiser_gene_pheno_score > 0.5

Then, to fully understand, you should know that AnnotSV does not evaluate overlaps with benign SVs if there is overlap with a pathogenic region:
<img width="1494" height="43" alt="Image" src="https://github.com/user-attachments/assets/887756dc-a226-4c0e-a0ce-25b94a0b33b7" />

**Comment by npoojitha415-commits** [comment]
Understood. Thank you very much!
