### ISSUE TITLE
"Known pathogenic genes or genomic regions annotation" specific to the "INV" type are missing

### ISSUE THREAD

**Issue by mtl2021** [lgmgeo/AnnotSV#46]
Hi Veronique,
I am running AnnotSV v3.0.7 but I do not see all the 16 columns concerning the "_Known pathogenic genes or genomic regions annotation_";
The output I've obtained only reports the first 12 columns; (the 4 columns specific to the "inv" type seem to be missed). 
The [documentation](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf) (page 18) mentions 12 annotation columns (cf. "_Add **12** annotation columns_" but actually details a list of 16 columns (4 groups of 4 columns about the "gain", "loss", "ins" and "inv" types).

print screen from the latest documentation:
![Capture d’écran de 2021-04-15 17-38-33](https://user-images.githubusercontent.com/78079606/114897505-97012780-9e11-11eb-9dbe-860406f1a18a.png)

I would like to double check with you if the code or the documentation needs to be updated from this observation (or perhaps did I  miss a parameter in the command line).

note: all is correct about the 8 annotation columns for the "_Known benign genes or genomic regions annotation_"; (the 4 groups of 2 columns for the  "gain", "loss", "ins" and "inv" type are all reported in the AnnotSV output.

Thank you very much,
Kind regards,

**Comment by lgmgeo** [comment]
Hi,

Thanks for reporting this error in the documentation.
I just published a new release of the README (by removing the 4 "inv" columns). 

I apologise for the inconvenience,
Best,
Véronique

**Comment by mtl2021** [comment]
Thank you very much Véronique for your prompt reactivity, and all the improvements you do in AnnotSV,
Best regards,
