### ISSUE TITLE
dbVAR's Clinical SV & NCBI Curated Common SV

### ISSUE THREAD

**Issue by jomoxi** [lgmgeo/AnnotSV#48]
Are those db from dbVar included in AnnotSV?

Clinical SV
https://www.ncbi.nlm.nih.gov/dbvar/content/clinvar_summary

NCBI Curated Common SV
https://www.ncbi.nlm.nih.gov/dbvar/content/common_summary/

Thanks!

**Comment by lgmgeo** [comment]
All the annotation sources are described in the [README](https://www.lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf).

From dbVar, only the dbVarNR pathogenic SV are included.
Else:
- Clinical SV are included directly from ClinVar
- Known benign genes or genomic regions are included from gnomAD, 1000g...
