### ISSUE TITLE
Too slow when installing human genome

### ISSUE THREAD

**Issue by YangShi-PKU** [lgmgeo/AnnotSV#49]
Hi
Thanks for developing such an awesome tool, it brings so much convenience to my work. However when I tried to install AnnotSV on a HPC, where the internet connection is not so good, the "make PREFIX=. install-human-annotation" takes so much and always break up. I want to know if I can download the human genome on my PC and upload it to the HPC, then run "make PREFIX=. install-human-annotation" without downloading the genome.
Could you give some advice? Many thanks!

Yang

**Comment by lgmgeo** [comment]
Dear Yang,

Thanks for your interest in AnnotSV.

There are 2 ways to solve your problem:

- Make the complete AnnotSV install on your PC and then upload all the $ANNOTSV/ directory to the HPC.

- Or run `make PREFIX=. install-human-annotation` multiple times on the HPC until the download is complete. 
Indeed, the use of the "-C" curl command in the makefile tell curl to automatically find out where/how to resume the transfer. It then uses the given output/input files to figure that out.

Have fun with AnnotSV,

Véronique

**Comment by YangShi-PKU** [comment]
Thank you very much! I'll try your advice!

Yang
