### ISSUE TITLE
In-frame / out-frame annotation

### ISSUE THREAD

**Issue by bopohdr** [lgmgeo/AnnotSV#5]
I am working with WES-based CNV calls and a lot of them are intragenic CNVs. I want to prioritize intragenic duplications and analyze only those, which are out-of-frame and may result in frameshift effect. 
Is it possible to add annotation regarding in-frame and out-frame exons to the AnnotSV annotations that can be used for intragenic CNVs?

Best,
Dmitrijs

**Comment by lgmgeo** [comment]
Hi Dmitrijs,

Thanks for your suggestion, what you propose is an interesting feature!
I will see how to implement it but this will take some time (not for the next release) because the new ideas to investigate are piling up...

Best,
Véronique

**Comment by Jixin-Cao** [comment]
Can (lengthCDS/3) solve it?

**Comment by lgmgeo** [comment]
Absolutely, thank you.
I really need to implement this, I will do my best

**Comment by lgmgeo** [comment]
I just added a new commit ("Add the frameshift column") on the patch_AnnotSV branch.
The "frameshift" value is set to "yes" if (lengthCDS/3) is not equal to "0". Else the "frameshift" value is set to "no".
