### ISSUE TITLE
Can AnnotSV generate vcf-fomrat output? 

### ISSUE THREAD

**Issue by xiucz** [lgmgeo/AnnotSV#51]
Thank you.

**Comment by lgmgeo** [comment]
Hi,

Currently, AnnotSV doesn't offer the possibility of VCF output results and it is not planned in a near future.

Actually, it's an interesting feature but unfortunately really difficult to achieve:
AnnotSV builds 2 types of annotations, one based on the full-length SV (corresponding to the Annotation_mode = "full") and one based on each gene within the SV (corresponding to the Annotation_mode = "split"). In my opinion, it would not be well understandable to add back several annotation lines from the TSV output to the INFO part of one line of a VCF output.

However, let me know if you are interested in working ont that. I'm open for any new collaboration to improve AnnotSV.

Best,
Véronique

**Comment by xiucz** [comment]
@lgmgeo 

Thank you for your reply, and I accept your option. ^_^.
