### ISSUE TITLE
Cytoband annotation feature to AnnotSV  please.

### ISSUE THREAD

**Issue by xiucz** [lgmgeo/AnnotSV#52]
#Version 3.0
For large SV annotation,  can we add cytoband annotation feature to AnnotSV ? Please see here https://github.com/WGLab/doc-ANNOVAR/issues/144.

**Comment by lgmgeo** [comment]
Yes, for sure, that makes sense for me!
Thank you for your suggestion.
I will come back to you asap.

Véronique

**Comment by lgmgeo** [comment]
Hi,

I've just pushed a new commit (v3.0.8). The new code permits cytoband annotations to be added.

However, the AnnotSV annotation sources are updated only twice a year.
The next one is planned at the end of this summer.

If you need now cytoband annotations:
- Install the v3.0.8 AnnotSV
- Then run the following commands:
````
cd  $ANNOTSV/share/AnnotSV/Annotations_Human/Users/GRCh37/AnyOverlap
curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/TmpCytoband/cytoBand_GRCh37.bed
cd  $ANNOTSV/share/AnnotSV/Annotations_Human/Users/GRCh38/AnyOverlap
curl -C - -LO https://www.lbgi.fr/~geoffroy/Annotations/TmpCytoband/cytoBand_GRCh38.bed
````

All the best,
Véronique

**Comment by lgmgeo** [comment]
November 8, 2021: v3.1 is posted!

The cytoband annotations will be now downloaded during the installation process (Makefile).
