### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by brain-discourse** [lgmgeo/AnnotSV#53]
Hello,

I am trying to annotate CNV calls using a bed file and am getting the following error: 
`/var/spool/slurmd/job22081901/slurm_script: line 10: 11708 Segmentation fault` 

My annotation script is as follows:` /proj/projects/AnnotSV/bin/AnnotSV -SVinputFile 'sorted_combined.bed' -outputFile ./combined.annotated.tsv -svtBEDcol 4 -genomeBuild GRCh38 &>AnnotSV.log`. My log file (attached)displays no error but it stops abruptly giving me the segmentation fault 

```
AnnotSV 3.0.9

Copyright (C) 2017-2021 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.5

Application name used (defined with the "ANNOTSV" environment variable):
/proj/projects/AnnotSV


...downloading the configuration data (June 28 2021 - 15:04)
	...configuration data by default
	...configuration data from /proj/projects/AnnotSV/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data

...checking the annotation data sources

WARNING: No GeneHancer annotations available.
(Please, see in the README file how to add these annotations. Users need to contact the GeneCards team.)


...listing arguments
	******************************************
	AnnotSV has been run with these arguments:
	******************************************
	-REreport no
	-SVinputFile sorted_combined.bed
	-SVinputInfo 1
	-SVminSize 50
	-annotationMode both
	-annotationsDir /proj/projects/AnnotSV/share/AnnotSV
	-bcftools bcftools
	-bedtools bedtools
	-candidateGenesFiltering no
	-genomeBuild GRCh38
	-includeCI yes
	-metrics us
	-minTotalNumber 500
	-organism Human
	-outputDir .
	-outputFile combined.annotated.tsv
	-overlap 100
	-overwrite yes
	-promoterSize 500
	-rankFiltering 1 2 3 4 5 NA
	-reciprocal no
	-samplesidBEDcol -1
	-snvIndelPASS 0
	-svtBEDcol 4
	-tx RefSeq
	******************************************

...searching for SV overlaps with a gene or a regulatory elements
	...26945 genes overlapped with an SV`
```

I would be grateful if you could help me troubleshoot this issue. 

Thanks!

**Comment by lgmgeo** [comment]
Hi,

Your input file seems to be very large or to contain very large SV ("26945 genes overlapped with an SV").
This is what (I think) causes a segmentation fault.

A refactoring of AnnotSV from Tcl to Python is planned with the use of an SQLite database to fix this bug, but it could still take a few months...

To solve this you can split your input file into smaller files, run AnnotSV and then later merge them into a single output file.

Let me know if it doesn't work, you can also annotate your SV on the[ web site](https://lbgi.fr/AnnotSV/runjob), send me the job ID and then I could have a look at it to help you.

Best regards,

Véronique

**Comment by lgmgeo** [comment]
Can you also tell me which bedtools version was used?
The minimum bedtools version compatible with AnnotSV is version 2.25. 
(To check if the version is the good one, run `bedtools --version`)

**Comment by brain-discourse** [comment]
Hello, 

Thank you for your response. Would you happen to know the maximum file size/number of lines I could annotate using AnnotSV. I will try splitting my files based on that. I am using bedtools/2.29 for running the program. 

Thanks!

**Comment by lgmgeo** [comment]
```
Would you happen to know the maximum file size/number of lines I could annotate using AnnotSV
````
Sorry, no way... it all depends on the number of genes overlapped with the SV

**Comment by brain-discourse** [comment]
Hi, 
Thank you for helping out with this. I was able to make it work by breaking the file into smaller files and them compiling them.

**Comment by lgmgeo** [comment]
Great!
(sorry for the inconvenience)
Have fun with AnnotSV :o)
