### ISSUE TITLE
BND events from ClinSV output have unproper SV END, leading to partial annotation of events

### ISSUE THREAD

**Issue by kalon33** [lgmgeo/AnnotSV#56]
BND events from ClinSV have unproper SV end indicated, (SV END = SV START +1), leading to a wrong number of split annotations and affected genes.

Here is an example:

ClinSV VCF line:
   
`9	111153614	Lumpy_271090_1	N	N]18:22953141]	.	PASS	SVTYPE=BND;END=22953141;STRANDS=++:6;IMPRECISE;CIPOS=-6,9;CIEND=-10,9;CIPOS95=-1,3;CIEND95=-3,3;MATEID=271090_2;EVENT=271090;SU=6;PE=5;SR=1;LOCATION=9:111153614,18:22953141;CNV=0;CHR2=18;TOOL=Lumpy;EVTYPE=PE5,SR1,RD;PAFDGV=-1;PAC=0;PAFV=0;PAF1KG=-1;NUMG=2;GENES="AL162414.1,RBBP8";GDESC="RBBP8,ensembl_havana,transcript,ENST00000327155|AL162414.1,havana,transcript,ENST00000426204";HPO="|0000606:0000047:0000163:0005927:0009484:0009825:0000492:0009122:0000951:0001317:0000171:0004097:0000718:0011329:0009118:0002011:0002817:0010295:0004220:0100547:0010935:0006265:0004323:0011119:0010674:0006483:0001155:0006262:0001167:0011821:0001574:0000356:0000811:0000078:0012759:0001999:0011025:0012443:0001249:0000157:0001626:0001382:0000002:0011282:0001263:0004322:0000275:0005930:0009906:0002060:0000448:0000077:0011842:0040019:0012373:0001844:0008050:0012639:0100851:0100887:0002648:0004348:0001608:0004209:0001363:0002644:0000925:0001367:0007360:0000478:0002683:0100711:0011927:0001032:0000290:0000278:0005819:0011061:0001510:0100627:0000315:0001159:0001822:0011283:0002814:0007429:0000765:0040068:0001595:0012243:0000494:0000924:0001770:0005922:0008056:0000707:0011451:0040064:0006109:0010936:0000007:0011342:0010579:0001518:0009121:0009767:0200006:0000277:0005105:0011729:0000501:0000682:0000377:0001321:0011354:0000164:0100542:0011138:0100498:0000929:0009115:0011446:0001620:0004219:0000444:0000708:0001511:0006216:0009116:0011297:0000347:0000235:0011362:0000152:0004325:0012372:0000119:0009161:0009381:0004213:0012758:0002977:0000271:0009843:0001780:0000957:0009376:0000691:0007495:0005780:0009803:0000079:0000366:0005918:0000568:0002650:0012210:0009815:0000032:0030148:0003330:0000252:0004207:0000795:0010461:0000598:0009804:0100543:0000036:0002813:0011844:0000234:0000284:0000240:0001507:0010938:0003272:0010051:0000153:0000363:0011355:0030084:0012374:0009179:0006919:0006496:0009833:0012638:0007364:0004692:0006482:0000086:0009237:0002943:0001760:0006143:0000274:0011314:0000341:0001852"	GT:SU:PAFSU:PE:SR:DBP:DRF:DRA:MQBP:FT:PAFDRA:RARE	1/1:6:0:5:1:36:-1:-1:60:PASS:0:1`
   
AnnotSV annotated TSV lines (full and split):
   
`9_111153614_111153615_BND_1	9	111153614	111153615		BND	FS00505001	Lumpy_271090_1	N	N]18:22953141]	.	PASS	SVTYPE=BND;END=22953141;STRANDS=++:6;IMPRECISE;CIPOS=-6,9;CIEND=-10,9;CIPOS95=-1,3;CIEND95=-3,3;MATEID=271090_2;EVENT=271090;SU=6;PE=5;SR=1;LOCATION=9:111153614,18:22953141;CNV=0;CHR2=18;TOOL=Lumpy;EVTYPE=PE5,SR1,RD;PAFDGV=-1;PAC=0;PAFV=0;PAF1KG=-1;NUMG=2;GENES="AL162414.1,RBBP8";GDESC="RBBP8,ensembl_havana,transcript,ENST00000327155|AL162414.1,havana,transcript,ENST00000426204";HPO="|0000606:0000047:0000163:0005927:0009484:0009825:0000492:0009122:0000951:0001317:0000171:0004097:0000718:0011329:0009118:0002011:0002817:0010295:0004220:0100547:0010935:0006265:0004323:0011119:0010674:0006483:0001155:0006262:0001167:0011821:0001574:0000356:0000811:0000078:0012759:0001999:0011025:0012443:0001249:0000157:0001626:0001382:0000002:0011282:0001263:0004322:0000275:0005930:0009906:0002060:0000448:0000077:0011842:0040019:0012373:0001844:0008050:0012639:0100851:0100887:0002648:0004348:0001608:0004209:0001363:0002644:0000925:0001367:0007360:0000478:0002683:0100711:0011927:0001032:0000290:0000278:0005819:0011061:0001510:0100627:0000315:0001159:0001822:0011283:0002814:0007429:0000765:0040068:0001595:0012243:0000494:0000924:0001770:0005922:0008056:0000707:0011451:0040064:0006109:0010936:0000007:0011342:0010579:0001518:0009121:0009767:0200006:0000277:0005105:0011729:0000501:0000682:0000377:0001321:0011354:0000164:0100542:0011138:0100498:0000929:0009115:0011446:0001620:0004219:0000444:0000708:0001511:0006216:0009116:0011297:0000347:0000235:0011362:0000152:0004325:0012372:0000119:0009161:0009381:0004213:0012758:0002977:0000271:0009843:0001780:0000957:0009376:0000691:0007495:0005780:0009803:0000079:0000366:0005918:0000568:0002650:0012210:0009815:0000032:0030148:0003330:0000252:0004207:0000795:0010461:0000598:0009804:0100543:0000036:0002813:0011844:0000234:0000284:0000240:0001507:0010938:0003272:0010051:0000153:0000363:0011355:0030084:0012374:0009179:0006919:0006496:0009833:0012638:0007364:0004692:0006482:0000086:0009237:0002943:0001760:0006143:0000274:0011314:0000341:0001852"	GT:SU:PAFSU:PE:SR:DBP:DRF:DRA:MQBP:FT:PAFDRA:RARE	1/1:6:0:5:1:36:-1:-1:60:PASS:0:1	full	AL162414.1	1																																				IMH	9:65437054-134286391;9:80897169-125694547;9:89671547-130954998	q31.3	gpos25			NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA						0.290	0.285																																					NA`
   
`9_111153614_111153615_BND_1	9	111153614	111153615		BND	FS00505001	Lumpy_271090_1	N	N]18:22953141]	.	PASS	SVTYPE=BND;END=22953141;STRANDS=++:6;IMPRECISE;CIPOS=-6,9;CIEND=-10,9;CIPOS95=-1,3;CIEND95=-3,3;MATEID=271090_2;EVENT=271090;SU=6;PE=5;SR=1;LOCATION=9:111153614,18:22953141;CNV=0;CHR2=18;TOOL=Lumpy;EVTYPE=PE5,SR1,RD;PAFDGV=-1;PAC=0;PAFV=0;PAF1KG=-1;NUMG=2;GENES="AL162414.1,RBBP8";GDESC="RBBP8,ensembl_havana,transcript,ENST00000327155|AL162414.1,havana,transcript,ENST00000426204";HPO="|0000606:0000047:0000163:0005927:0009484:0009825:0000492:0009122:0000951:0001317:0000171:0004097:0000718:0011329:0009118:0002011:0002817:0010295:0004220:0100547:0010935:0006265:0004323:0011119:0010674:0006483:0001155:0006262:0001167:0011821:0001574:0000356:0000811:0000078:0012759:0001999:0011025:0012443:0001249:0000157:0001626:0001382:0000002:0011282:0001263:0004322:0000275:0005930:0009906:0002060:0000448:0000077:0011842:0040019:0012373:0001844:0008050:0012639:0100851:0100887:0002648:0004348:0001608:0004209:0001363:0002644:0000925:0001367:0007360:0000478:0002683:0100711:0011927:0001032:0000290:0000278:0005819:0011061:0001510:0100627:0000315:0001159:0001822:0011283:0002814:0007429:0000765:0040068:0001595:0012243:0000494:0000924:0001770:0005922:0008056:0000707:0011451:0040064:0006109:0010936:0000007:0011342:0010579:0001518:0009121:0009767:0200006:0000277:0005105:0011729:0000501:0000682:0000377:0001321:0011354:0000164:0100542:0011138:0100498:0000929:0009115:0011446:0001620:0004219:0000444:0000708:0001511:0006216:0009116:0011297:0000347:0000235:0011362:0000152:0004325:0012372:0000119:0009161:0009381:0004213:0012758:0002977:0000271:0009843:0001780:0000957:0009376:0000691:0007495:0005780:0009803:0000079:0000366:0005918:0000568:0002650:0012210:0009815:0000032:0030148:0003330:0000252:0004207:0000795:0010461:0000598:0009804:0100543:0000036:0002813:0011844:0000234:0000284:0000240:0001507:0010938:0003272:0010051:0000153:0000363:0011355:0030084:0012374:0009179:0006919:0006496:0009833:0012638:0007364:0004692:0006482:0000086:0009237:0002943:0001760:0006143:0000274:0011314:0000341:0001852"	GT:SU:PAFSU:PE:SR:DBP:DRF:DRA:MQBP:FT:PAFDRA:RARE	1/1:6:0:5:1:36:-1:-1:60:PASS:0:1	split	AL162414.1		ENST00000426204	111139245	111284836	1	0	0	no	3	intron2-intron2	UTR	13995	3'	111153614	111153615																						IMH	9:65437054-134286391;9:80897169-125694547;9:89671547-130954998	q31.3	gpos25			NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	9_111139300;9_111139536;9_111140601;9_111143171;9_111143379;9_111144945;9_111145008;9_111145287;9_111145479;9_111145915;9_111148224;9_111148260;9_111148596;9_111149333;9_111150273;9_111150369;9_111152895;9_111152905;9_111152929;9_111152932;9_111152935;9_111152949;9_111153004;9_111154930;9_111156367;9_111156576;9_111156653;9_111156794;9_111156798;9_111156957;9_111157189;9_111157243;9_111157397;9_111157782;9_111157798;9_111157828;9_111157881;9_111158272;9_111159409;9_111160572;9_111162173;9_111162622;9_111163254;9_111164565;9_111166684;9_111167067;9_111167277;9_111167891;9_111168163;9_111168343;9_111168867;9_111168869;9_111168874;9_111169933;9_111170926;9_111171405;9_111171425;9_111172292;9_111173448;9_111174026;9_111174126;9_111174336;9_111177313;9_111178437;9_111178614;9_111178644;9_111180122;9_111181429;9_111181873;9_111182207;9_111182402;9_111182787;9_111182847;9_111183338;9_111183340;9_111184405;9_111184421;9_111188301;9_111188604;9_111191221;9_111193570;9_111193665;9_111193992;9_111194596;9_111194889;9_111195254;9_111195664;9_111196663;9_111196864;9_111197851;9_111198067;9_111198292;9_111198414;9_111198601;9_111198629;9_111198726;9_111198854;9_111198946;9_111200637;9_111200885;9_111200952;9_111202084;9_111202517;9_111202674;9_111202694;9_111202696;9_111202697;9_111202773;9_111203260;9_111203523;9_111204099;9_111204330;9_111204682;9_111204984;9_111205130;9_111205199;9_111205241;9_111205535;9_111206323;9_111206910;9_111207101;9_111208426;9_111208440;9_111208809;9_111208954;9_111209432;9_111210218;9_111210811;9_111211273;9_111211501;9_111215066;9_111216731;9_111218604;9_111218615;9_111219399;9_111219401;9_111219416;9_111219427;9_111222525;9_111223195;9_111223374;9_111223635;9_111224275;9_111224458;9_111224664;9_111226117;9_111226396;9_111226814;9_111227708;9_111228525;9_111228573;9_111228927;9_111229482;9_111229818;9_111230785;9_111231309;9_111232737;9_111233195;9_111233728;9_111234561;9_111234764;9_111235399;9_111235428;9_111251468;9_111273995;9_111284723																																											full=NA`
   
As you can see, only one split is returned, and coordinates are wrong. Would it be possible to fix this?
   
Thanks for your help.

**Comment by lgmgeo** [comment]
Hi Nicolas,

Your ClinSV VCF contains breakends notation (SVTYPE=BND), in other words: breakpoints.
In your example, the BND is located at chr9:111153614.
AnnotSV only returns one split line corresponding to this BND. And the BND coordinates are corrects.

The position chr18:22953141 of the mate breakend is not annotated with AnnotSV from this input line.

Best regards,
Véronique
