### ISSUE TITLE
RefSeq Transcript Annotation

### ISSUE THREAD

**Issue by Mkddb** [lgmgeo/AnnotSV#57]
Hello Veronique,

Hope you are doing well out there.

I have a strange observation in the annotated Multisample VCF. 
One sample having 2 different deletions in the same VHL gene (3_10142185_10146511_DEL_1 and 3_10146632_10149782_DEL_1) got annotation from 2 different transcripts (NM_001354723 and NM_000551) leading to these entries in "Location" column: exon1-intron2 and exon2-intron2. A similar observation was there for few more genes such as NM_001141973 and NM_022089 transcripts for ATP13A2 gene for the same sample and few others.
Another case was 2 different samples with Deletions in the same gene CASP8 had 2 different annotations from transcripts NM_001080125 and NM_001228. 
while many other samples had annotation from a single RefSeq transcript despite the different Deletions in the same gene and the same sample. I am not able to understand on what basis "1 transcript got priority in 1 case and another for another Deletion in the same gene". can you please elaborate?
Coordinates are for the Hg38 version and AnnotSV3.0.6 for annotation.

Please check and help me with that.

Thanks,
Mkd

**Comment by lgmgeo** [comment]
Hi,

For each SV, only a single transcript from all transcripts available for the overlapped gene is reported in the following order of preference:
- The transcript selected by the user with the "-txFile" option is reported
- The transcript with the longest overlapped CDS is reported
- If there is no difference in CDS length, the longest overlapped transcript is reported.


_**Regarding your example with the _VHL_ gene:**_
Here are the GRCh38 coordinates of both transcripts (NM_001354723 and NM_000551):
```
chrom   start           end             strand  gene    transcript      CDSstart        CDSend          exonStarts                      exonEnds
3       10141777        10153666        +       VHL     NM_000551       10141847        10149965        10141777,10146513,10149786,     10142187,10146636,10153666,
3       10141777        10153666        +       VHL     NM_001354723    10141847        10143004        10141777,10142762,10149786,     10142187,10143021,10153666,
```

- First SV (3:10142185-10146511):
overlapped CDS with NM_000551 = 2
overlapped CDS with NM_001354723 = 244
=> NM_001354723 reported in AnnotSV

- Second SV (3:10146632-10149782):
overlapped CDS with NM_000551 = 4
overlapped CDS with NM_001354723 = 0
=> NM_000551 reported in AnnotSV

Best,
Véronique

**Comment by Mkddb** [comment]
Okay, got it.

Thanks for the clarification.

Best regards,
Mkd
