### ISSUE TITLE
Split annotation Exon_count reports at least 1 exon overlap for every gene overlap

### ISSUE THREAD

**Issue by rodrigotoro** [lgmgeo/AnnotSV#58]
Hi,

I am trying to figure out whether my AnnotSV output is expected or if this is a bug. To give some context, I am working with 96208 structural variants which are the result of re-genotyping multiple samples. AnnotSV reports that 58090 of these variants are overlapping at least one gene, as gathered from AnnotSV's full annotation rows. 

When I look at split annotation rows, the Exon_count column shows that for every single gene overlapped there is at least 1 exon being overlapped (the minimum value in the Exon_count column is 1), which seems unlikely. I am also pretty sure this is not the case as I have previously performed a similar analysis on the same dataset using other tools and I found many overlaps with genes that did not fall within exons. 

Any clue as to why this is happening? Or am I not interpreting the output correctly?

Thanks in advance!

**Comment by lgmgeo** [comment]
Hi,

Thank you for the report, it looks like a bug. I will get back to you asap with a debugged version.

Best,

Véronique

**Comment by rodrigotoro** [comment]
Hi Veronique,

Thanks for the clarification, I misunderstood the definition of Exon_count. I will take a closer look at your suggested columns!

Cheers,
Rodrigo
