### ISSUE TITLE
Support for GRCh38.p13

### ISSUE THREAD

**Issue by Eduardo-Auer** [lgmgeo/AnnotSV#65]
Hello. I have a VCF with structural variants called by Manta Structural Variant Caller (Illumina), and the reference genome used was GRCh38.p13. I would like to know if there will be future support for this reference genome to use AnnotSV.

**Comment by lgmgeo** [comment]
Sorry, the use of the GRCh38 patch release 13 (GRCh38.p13) is not planned in AnnotSV.

**Comment by Eduardo-Auer** [comment]
> Sorry, the use of the GRCh38 patch release 13 (GRCh38.p13) is not planned in AnnotSV.

Ok. Thank you for the response!
