### ISSUE TITLE
Problem installaling AnnotSV

### ISSUE THREAD

**Issue by lakhujanivijay** [lgmgeo/AnnotSV#7]
I am following the below steps to install AnnotSV and I encountered an error; find below the details 

1. Downloaded the latest installer from [this](https://www.lbgi.fr/AnnotSV/Sources/AnnotSV_latest.tar.gz) and unzipped using ` tar -zxvf AnnotSV_latest.tar.gz `

2. Downloaded and installed `tcsh`

`sudo apt-get install tcsh`

3. Go to  `AnnotSV_2.2` folder and type below command:
```
make PREFIX=. install
/bin/mv License.txt changeLog.txt commandLineOptions.txt README.AnnotSV_2.2.pdf ./share/doc/AnnotSV
/bin/mv share/tcl ./share/tcl8.6
Done
```

4. Then at this command; I am facing this issue:
```
make PREFIX=. install-human-annotation
find: ‘share/tcl/AnnotSV/’: No such file or directory
make: *** No rule to make target 'install-human-annotation'.  Stop.
```
My folder structure look like this (after step#3)
```
├── bin
│   └── AnnotSV
├── etc
│   └── AnnotSV
├── Makefile
└── share
    ├── doc
    └── tcl8.6

```
Could you please help? I am using Ubuntu 16
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

**Comment by lgmgeo** [comment]
Hi Vijay,

Actually, the AnnotSV installation is being modified from 2.2 (the version you downloaded on the AnnotSV website) to 2.3 (the version from GitHub, with the "make PREFIX=. install-human-annotation" command). 
Version 2.3 is going to be available really soon.

Currently, here are the commands you can use for a quick installation of version 2.2.3.
The sources can be cloned to any directory:

cd /’somewhere’/

git clone https://github.com/lgmgeo/AnnotSV.git

Then, the user can easily set the install in the /’somewhere’/AnnotSV/ directory:

cd /'somewhere'/AnnotSV

make PREFIX=. install

make PREFIX=. install-human-annotation

make PREFIX=. install-mouse-annotation

setenv ANNOTSV /’somewhere’/AnnotSV

And to test the installation:

cd /’somewhere’/AnnotSV/share/doc/AnnotSV/Example/

$ANNOTSV/bin/AnnotSV -SVinputFile test.bed -outputFile ./test.annotated.tsv -svtBEDcol 4

Let me know if you still have a problem,

Véronique

**Comment by lakhujanivijay** [comment]
Thanks @lgmgeo 

That solves my issue. One last question, is it necessary to run `make PREFIX=. install-mouse-annotation` when I am only working with human data?

**Comment by lgmgeo** [comment]
Great!
No, you're right, you don't need to install mouse annotation for working on human data.
Happy exploring with AnnotSV,
Véronique
