### ISSUE TITLE
Max file size

### ISSUE THREAD

**Issue by ashamehta** [lgmgeo/AnnotSV#70]
Hi Véronique,

Is there a maximum recommended file size/variant count for an SV input file? My AnnotSV run is hanging on this step:
```
...downloading the configuration data (December 06 2021 - 09:37)
	...configuration data by default
	...configuration data from tools/AnnotSV/AnnotSV_3.0.5/AnnotSV/etc/AnnotSV/configfile
	...configuration data given in arguments
	...checking all these configuration data
```
The input SV file is much larger than what I've previously used (1.8 GB, ~5x10^6 variants), so I suspect that's the issue, but wanted to confirm whether that would be expected. 

Thank you for your help!
-Asha
P.S. Haven't forgotten about https://github.com/lgmgeo/AnnotSV/issues/64 - will probably get to that early next year.

**Comment by lgmgeo** [comment]
Hi Asha,

Indeed, I suspect that your high SV count caused the problem. But I have never tried to annotate 5 million SV in a single run...
To solve this, you can split your input file into smaller files, run AnnotSV and then later merge them into a single output file.

Best,
Véronique

**Comment by ashamehta** [comment]
Ok, thank you! I will try that.
