### ISSUE TITLE
Transferring Genehancer from old installation

### ISSUE THREAD

**Issue by gevro** [lgmgeo/AnnotSV#71]
Hi,
How do I do the above?
Thanks.

**Comment by lgmgeo** [comment]
Hi Gevro,

You need to use your old “GeneHancer_**\<version**\>_for_annotsv.zip“ flat file.

Please have a look at the "b) Regulatory Elements annotations" section from the [README](https://lbgi.fr/AnnotSV/Documentation/README.AnnotSV_latest.pdf) file:

![image](https://user-images.githubusercontent.com/49909073/144981090-08ad8545-5970-4515-9f2f-007dbd86b36a.png)
![image](https://user-images.githubusercontent.com/49909073/144981908-5e1a1c84-003b-48ed-b825-133ddf123a43.png)

Best regards,

Véronique
