### ISSUE TITLE
start, end and length not adding up

### ISSUE THREAD

**Issue by anoronh4** [lgmgeo/AnnotSV#73]
i am testing annotsv and finding that the first few columns in certain examples do not make sense and I was hoping it could be clarified. i have the following vcf record:
```
17	60786420	Merged_DUP_17_60786420	N	]17:60786558]N	.	manta_MinSomaticScore	END=60786558;Callers=manta;NumCallers=1;CHR2=17;SVTYPE=DUP;SVLEN=138;STRANDS=-+;manta_CIPOS=0,3;manta_CIEND=0,3;manta_HOMLEN=3;manta_HOMSEQ=AGC;manta_SOMATIC;manta_SOMATICSCORE=17	manta_PR:manta_SR	36,0:77,5	46,0:107,0
```
when i search this by ID in the AnnotSV result, i see:
```
$ grep Merged_DUP_17_60786420 20211209_AnnotSV/test_mergedVcf.tsv | cut -f 1-5,17
17_60786420_60786424_DUP_1	17	60786420	60786424	138	full
17_60786420_60786424_DUP_1	17	60786420	60786424	138	split
17_60786420_60786424_DUP_1	17	60786420	60786424	138	split
```
the difference between `SV_start` and `SV_end` is 4, which is incorrect, even though the `SV_length` is 138, which is correct. I do not have `CIPOS` or `CIEND` fields, although even if i did use `manta_CIPOS` and `manta_CIEND` i would not arrive at 4.

**Comment by lgmgeo** [comment]
Hi anoronh4,

Indeed, it looks very strange...
I have pasted your SV input data into a VCF file and run AnnotSV v3.1, and the results are different from yours.

**First test (including CIPOS treatment):**
`$ANNOTSV/bin/AnnotSV -SVinputFile tutu.vcf -outputFile ./tutu.annotated.tsv`
```
AnnotSV_ID                      SV_chrom     SV_start        SV_end          SV_length       SV_type
17_60786420_60786561_DUP_1      17           60786420        60786561        138             DUP
```
**Second test (without CIPOS treatment):**
`$ANNOTSV/bin/AnnotSV -SVinputFile tutu.vcf -outputFile ./tutu.annotated.tsv -includeCI 0`
```
AnnotSV_ID                      SV_chrom     SV_start        SV_end          SV_length       SV_type
17_60786420_60786558_DUP_1      17           60786420        60786558        138             DUP
```

Are you using the lastest AnnotSV version? If not, please update.
If yes, please run your example on the web server (https://lbgi.fr/AnnotSV/runjob) and send me the job ID.

Best regards,
Véronique

**Comment by anoronh4** [comment]
I am using version AnnotSV 3.0.9, so perhaps not the absolute latest one but still pretty recent. i repeated with 3.1 and got results that matched your output. The webportal job is Tsob3Bkm7l and also matches. it's so great that this is working with symbolic calls (as defined [here](https://simpsonlab.github.io/2015/06/15/merging-sv-calls/))! 

Interesting that it incorporates CIPOS and CIEND even though the actual fields are manta_CIPOS and manta_CIEND. in theory an INFO field may include something like manta_CIPOS and <other_caller>_CIPOS, so i wonder AnnotSV would choose which one to use? is it whichever comes first in the info column?

**Comment by lgmgeo** [comment]
>Interesting that it incorporates CIPOS and CIEND even though the actual fields are manta_CIPOS and manta_CIEND. in my case an INFO field may include something like manta_CIPOS and delly_CIPOS in the same record, so i wonder AnnotSV would choose which one to use? is it whichever comes first in the info column?

Actually yes, AnnotSV keeps the one that comes first in the INFO column.
I realize that all this information is not reported in the README. Thanks for pointing it out.
I will add them to the README in a future release.

**Comment by Solenyalyl** [comment]
I have also met the same question, but it cannot be solved by installing a newer version of annotSV,because I have installed the newest version,v3.1.2,and when I run the example,it works fine,like this:
22_18894835_21464119_DEL_1      22      18894835        21464119        -2569284        DEL     Di George syndrom
22_18894835_21464119_DEL_1      22      18894835        21464119        -2569284        DEL     Di George syndrom
but when I input mant output vcf file, it output like this:
22_29683122_29683123_BND_1      22      29683122        29683123                BND     normal_202211,tumor_
22_29683122_29683123_BND_1      22      29683122        29683123                BND     normal_202211,tumor_
the breakpoint is not as such close as it shows.
how can I solve it?

**Comment by lgmgeo** [comment]
Sorry, I'm not sure I understand your question... 
Can you explain to me in more detail? Please, give a SV line from your VCF input file as well as the AnnotSV result. Then explain the problem encountered.

Else, you can be interested in https://github.com/lgmgeo/AnnotSV/issues/63?
