### ISSUE TITLE
how to find potential loss-of-function genes

### ISSUE THREAD

**Issue by AJ211** [lgmgeo/AnnotSV#74]
Hi Véronique,
    I am currently studying the structural variation of a cohort, hopine to find genes that may lose function due to homozygous deletions. I used AnnotSV to annotate all homozygous deletions, and found that there are many useful tags in the output file of AnnotSV, such as frameshift, P_loss_hpo, P_loss_phen, GnomAD_pLI, ExAC_pLI, etc. I think these tags should help me find genes that may lose function. Since there is so much information of these tags that I am completely lost, I would like to ask if you can give me some suggestions. In addition, the population I studied is a non-disease population, so there is no disease-related phenotypes.

thanks in advance
Jiao

**Comment by lgmgeo** [comment]
Hi Jiao,

Thank you for your interest in AnnotSV.

Not sure to understand your protocol... 
- You have studied a non-disease population, therefore a healthy population (how many individuals?)
- You called Structural Variation (SV) in this healthy cohort
- You kept the homozygous deletion (DEL)
- You want to identify genes that may lose function due to homozygous DEL? What do you mean? You want to find the genes encompassed by hom DEL and which lose their function, without any pathogenic impact (because your population is healthy)?

Perhaps will you be interested in the [LOEUF score from gnomAD](https://gnomad.broadinstitute.org/help#frequently-asked-questions) ?
![image](https://user-images.githubusercontent.com/49909073/145770375-52555ba9-7872-4683-885a-0d5eeb25489f.png)

Best regards,
Véronique

**Comment by AJ211** [comment]
Hi Véronique,
  Sorry I didn't make it clear. Yes I am studying a healthy population of ~1,000 individuals. Now I am focusing on the loss-of-function mutations can disrupt both copies of a given gene. I have run AnnotSV, but I don't know how to judge from the results of AnnotSV whether an SV will disrupt the function of a certain gene (produce loss-of-function gene). Moreover, I also want to associate the loss-of-function genes with RNA-seq data in my hand. I think the results of AnnotSV can give me some help to pick up the loss-of-function genes.

Jiao

**Comment by lgmgeo** [comment]
So you are looking in your healthy population for genes tolerant to loss of function? 
And then you will cross-check your results with RNA-seq data (to verify that no protein is present for these genes)?
Correct?

**Comment by AJ211** [comment]
Yes, it's completely correct.

**Comment by lgmgeo** [comment]
OK. 
Actually, I'm not used to thinking this way (I personally research pathogenic SVs that can elucidate a patient's clinic).

But let's try.
You need to look at the split lines (Annotation_mode = split), describing the SV effect on a single gene.
So, you can retrieve your gene and transcript name/ID (Gene_name and Tx). 
Please, keep in mind that for each gene, only a single transcript from all transcripts available for this gene is reported in the following order of preference:
- The transcript selected by the user with the "-txFile" option is reported
- The transcript with the longest overlapped CDS is reported
- If there is no difference in CDS length, the longest overlapped transcript is reported

Gene deletions lead to exon skipping, premature stop codon introductions, or frameshift mutations, thereby resulting in incorrect truncated proteins. Then, several tags are of interest for your study: 
- Overlapped_CDS_percent (if 100%, you can select this gene. Else, you need to determine a cutoff for a better filtering with this tag)
- Frameshift (be careful with your SV call algorithm, breakpoints are not always precise, not with the depth of coverage for example)
- Exon_count and Location
- OMIM_inheritance and OMIM_morbid (if equal to AD and yes, this gene is not interesting for you as you study a healthy cohort) 
- GnomAD_pLI and ExAC_pLI (not interesting if > 0.9)

Hope other users can help you,

Best, 
Véronique

**Comment by AJ211** [comment]
Hi Véronique
   I will fully consider your suggestions. and I am grateful for your help.

**Comment by lgmgeo** [comment]
```
So you are looking in your healthy population for genes tolerant to loss of function.
And then you will cross-check your results with RNA-seq data (to verify that no protein is present for these genes)
```
Did you manage to analyze your healthy cohort?
Which annotations did you ultimately use from AnnotSV? 
Was AnnotSV sufficient or did you need another tool?
Can you share your protocol with other users?

Thanks

**Comment by AJ211** [comment]
Sure. Finally I chose the annotation tage of "Overlapped_CDS_percent" in my study.
