### ISSUE TITLE
The software can't stop running though the annotate is finished.

### ISSUE THREAD

**Issue by Mirror-fish** [lgmgeo/AnnotSV#75]
Hi Véronique, I'm recently doing annotation on my bed file, and I split my big bed file (50MB) into serveral pieces (2.5MB).

But some small pieces finished annotation smoothly, while some pieces still running for days. I stopped the non-stop pieces, find the fact that the annotation is almost finished, but it still running and producing "full".

And this is what happened:

This is the “.annotated.tsv.tmp” file.
```
9	138081484	138087573	DEL	full
9	138137150	138137162	DEL	full
9	138141950	138141958	DEL	full
9	138159974	138159986	DEL	full
9	138187482	138187483	INS	full
9	138217086	138217098	DEL	full
	full
	full
	full
	full
	full
	full
	full
```
The software just don't stop producing "full", just like the below half of the “.annotated.tsv.tmp” file, and after 22 hours of running, maybe 95% of the “.annotated.tsv.tmp” file is consisted of the only "full" in a row.

This is the last row of my bed file:
```
9	138159974	138159986	DEL
9	138187482	138187483	INS
9	138217086	138217098	DEL
```
The last row of my bed file is same as the “.annotated.tsv.tmp” file. That's why I think the annotation is finished, but it's still running.

And I submitted a task to the website using the same bed file 24 hours ago, it's still running now, maybe it meets the same issue:
https://www.lbgi.fr/AnnotSV/result?id=I6xaCl7bX2

By the way, I produced 240 files and ran them on my own compute sites, 122 files finished smoothly and 118 files can't stop.

Jingyu.

**Comment by Mirror-fish** [comment]
Oh almost forgot, my code running annotSV is:
```
...../AnnotSV.tcl \
-svtBEDcol 4 \
-genomeBuild GRCh38 \
-SVinputFile $input > AnnotSV${name}.log
```

**Comment by lgmgeo** [comment]
Hi Jingyu,

Indeed, your report looks really strange...
Thanks to your job id (I6xaCl7bX2), I'll take a look and get back to you ASAP.

You seem to be using an older version of AnnotSV (in newer versions the main file is no longer called AnnotSV.tcl). Can you tell me which one you are using?

Véronique

**Comment by lgmgeo** [comment]
Got it!

In your BED input file, you have lines like:
```chr9    82999984        8.3e+07 DEL```
instead of
```chr9    82999984        83000000 DEL```

AnnotSV is simply lost with this bad BED format.

Please, format your BED files.

**Comment by Mirror-fish** [comment]
Oh, thank you so much for point out this flaw. I used R to create this file, so obviously I didn't set the class of the datas properly.

And, I checked my download history, it's AnnotSV 2.2. I downloaded this version directly from the server.... Oh, I didn't notice that the latest version is on the above.

Anyway, thank you so much, I'll download a new version and rerun it.
