### ISSUE TITLE
Difference in the manual and source code regarding gnomAD benign SV annotation

### ISSUE THREAD

**Issue by lacek** [lgmgeo/AnnotSV#76]
In the source code of v3.1.1, we have:

https://github.com/lgmgeo/AnnotSV/blob/7973cc4725f548cac3f9cd2dc843ed47c5b3f1e0/share/tcl/AnnotSV/AnnotSV-benignsv.tcl#L469-L474

On the other hand, in the [PDF manual](https://github.com/lgmgeo/AnnotSV/blob/v3.1.1/README.AnnotSV_3.1.pdf) page 24, the following requirements are mentioned:

> * at least one population allele frequency > 0.01 (i.e. 1%) (default, see the “-benignAF” option in
USAGE/OPTIONS) OR at least 5 homozygous individuals
> * “DUP” or “DEL” SV type

Differences observed:

* allele frequency threshold of 0.001 in code v.s. 0.01 in manual
* SV types of {DEL DUP INS INV} in code v.s. {DUP DEL} in manual

I wonder if one of them is not updated yet.

**Comment by lgmgeo** [comment]
Hi @lacek,

The source code you quoted is only used **to create** the annotation files (the ones downloaded when running `make PREFIX=. install-human-annotation`). Not during an AnnotSV annotation.

During an AnnotSV annotation, the allele frequency threshold used is defined with the following option:
```
-benignAF:                      Allele frequency threshold to select the benign SV in the data sources
                                Range values: [0.001-0.1], default = 0.01 (i.e. 1%)
```
As you can see, users can set this option to 0.001. So These SV need to be presents in the annotation files. 
But the default is well 0.01 as mentionned in the README.

Concerning the SV type, the ranking is done only for DUP and DEL, but I plan to improve that ranking in the futur (not near).
Some parts of the code (mentioning INS, INV) are already presents in this ending.

To conclude, you can believe the README ;o)

Best regards,
Véronique

**Comment by lacek** [comment]
Thank you very much for your detailed explanation. Sorry that I didn't check the code thoroughly.
