### ISSUE TITLE
Gene annotation not complete for both breakends

### ISSUE THREAD

**Issue by anoronh4** [lgmgeo/AnnotSV#77]
I am noticing that for TRA variants, i am getting annotation for only one breakend. For example, in my vcf i have the following record: 
```
2	74687222	TRA_2_74687222	N	N[21:44841983[	.	.	END=44841983;CHR2=21;SVTYPE=TRA;STRANDS=+-	manta_PR:manta_SR	87,2:384,2	59,0:154,0
```
Even though `END` and `CHR2` are clearly annotated, just as in DUP or DEL events, no gene/transcript information is annotated for the second endpoint. In this case ^ I got overlap with genes WBP1 and INO80B-WBP1, which are on chromosome 2, but no overlap with SIK1, which is on chromosome 21 and overlaps with the second breakend. I don't have more interest in one breakend than the other. Just wondering why, since DUP, DEL, etc. span both breakpoints, and it seems like a solution could be relatively straightforward. I am also wondering how the second breakpoint is annotated in other columns to the right as well--when is it excluded?

**Comment by lgmgeo** [comment]
Hi @anoronh4,

Translocation can be summarized as a set of 2  adjacencies, as described in the Variant Call Format specification [VCF v4.3](https://samtools.github.io/hts-specs/VCFv4.3.pdf) (Jun 2020):
![image](https://user-images.githubusercontent.com/49909073/150313840-f193ebff-403e-4678-ac48-7aed91d84382.png)

In your example, AnnotSV considers your SV as a complex rearrangement describing a single breakend:
AnnotSV_ID = 2_74687222_74687223_TRA_1

To annotate both breakpoints from your TRA, you need to have in your VCF the corresponding second breakend. Something like:
```
21	44841983	TRA_21_44841983	N	N[2:74687222[	.	.	END=74687222;CHR2=2;SVTYPE=TRA;STRANDS=+-	manta_PR:manta_SR	87,2:384,2	59,0:154,0
```

Best regards,
Véronique

**Comment by lgmgeo** [comment]
Hi @anoronh4 ,

With the new 3.3.1 AnnotSV version, the comprehension of the square-bracketed notations relies now on the [homogenization rules](https://github.com/EUCANCan/variant-extractor#homogenization-rules) from the [variant-extractor](https://github.com/EUCANCan/variant-extractor) tool (provided by Rodrigo Martin). 

_Duplication, inversion, deletion and insertion:_
As breakends are always reciprocal, AnnotSV returns just one full annotation per SV (one full annotation per breakend pair). For this reason, considering paired breakends, the ALT feature with the lowest position is returned. The other one is reported in the unannotated output file.

_Translocation:_
AnnotSV returns one full annotation for each breakend of the pair.

Regarding your comment, it is to notice that with one breakend, you can indeed always infer the other. 
So, AnnotSV now rescues the missing breakend when possible.

Best,

Véronique
